[Design] HistoryView 레이아웃 1차 PR
Samsamhada/Giwazip-Client-App pull request #13
Opened 2023-01-18 04:00 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- HistoryView Layout 코드를 분할하여 올리기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
 - 네비게이션 구성
   - [x] 방 이름(아파트 이름)
   - [x] 계약기간 표시 (네비게이션 타이틀 2줄)
   - [x] 환경설정 버튼 추가
- 시공내역 문의내역 화면
  - [ ] 게시물 셀이 보여지는 부분 스크롤
  - [ ] 게시물이 없을 때, 마이크로카피

## ToDo 📆 (남은 작업)
- 탭 구성
  - [ ] 시공내역 / 문의내역 탭 추가
- 날짜 구분선
  - [ ] 날짜와 선으로 날짜 구분 표시
- 게시물 셀
  - [ ] 비율 - 4:3
  - [ ] 게시물 하단 게시글 칸 구분 (opacity 0.7, 글자색 - White)
  - [ ] 시공내역에서 좌상단 카테고리 칩 표시
- 환경설정 버튼 기능 추가
  - [ ] 환경설정 버튼 클릭 시 환경설정 뷰로 이동

## ScreenShot 📷 (참고 사진)
- 사진 추후 첨부

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 아직 진행 중인 부분은 올리지 않았습니다. 
- 코드가 길어질 것 같아 미리 올리기 때문에 요상한 부분 있으면 알려주시면 감사하겠습니다.

2023-01-18 06:31 UTC, taek0622 requested changes
정상적으로 빌드가 되지 않네요.
아직 작업 중인 부분이라 일부만 올리느라 실수가 발생한 것 같은데, 수정 부탁드립니다.
더불어서 SceneDelegate에서 주석을 삭제해서 빈 function들은 아예 삭제해주셔도 괜찮을 것 같습니다.

2023-01-18 06:31 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }
p1;
해당 부분이 꼬인 것 같네요.
attribute function 일부가 잘린 것 같아요.
빌드되지 않아서 정상적으로 확인이 불가능합니다.

2023-01-18 06:31 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +}
p1;
해당 부분에도 잘못된 중괄호가 들어간 것 같습니다.

2023-01-18 12:59 UTC, taek0622 requested changes
추가적으로 수정할 부분을 발견해서 리뷰 남깁니다. 확인 부탁드려요.

2023-01-18 12:59 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +import SnapKit
p2;
컨벤션 중 내장 라이브러리와 써드 파티 라이브러리를 공백 라인으로 구분하는 [import 컨벤션](https://github.com/Samsamhada/Giwazip-Client-App/wiki/Swift-Code-Convention#1-4-import)이 있습니다. 확인 부탁드려요.

2023-01-18 13:09 UTC, taek0622 requested changes
추가로 코멘트 달 수 있을만한 부분이 보여서 코멘트 달아놓습니다.

2023-01-18 13:09 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }(UIView())
p5;
별도로 아무것도 하지 않는 뷰라면 위와 같은 코드도 좋지만, 아래와 같이도 작성할 수 있다는 거 참고하시면 좋을 것 같아요.
이 부분은 스타일의 문제이니 수정하지 않으셔도 좋습니다.
```swift
private let titleView = UIView()
```

2023-01-18 13:09 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +    private func navigationLayout() {
p5;
해당 부분을 별도의 함수로 빼는 것, 혹은 함수의 이름 둘 중에 하나에 대해서는 논의해보는 것도 좋을 것 같네요.
또한, 별도의 함수로 뺀다면 결국 이 부분도 레이아웃이기 때문에 viewDidLoad보다는 layout에서 호출하는 것이 더 명확할 것 같습니다.

2023-01-18 17:29 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +}
코드가 전면 수정하여 해결되었습니다.

2023-01-18 17:29 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +}
> p1;
> 해당 부분에도 잘못된 중괄호가 들어간 것 같습니다.

코드가 전면 수정하여 해결되었습니다.

2023-01-18 17:29 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }
> p1;
> 해당 부분이 꼬인 것 같네요.
> attribute function 일부가 잘린 것 같아요.
> 빌드되지 않아서 정상적으로 확인이 불가능합니다.

코드가 전면 수정하여 해결되었습니다.

2023-01-18 17:29 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +import SnapKit
5c1451a 반영했습니다.

2023-01-18 17:30 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    private func navigationLayout() {
> p5;
> 해당 부분을 별도의 함수로 빼는 것, 혹은 함수의 이름 둘 중에 하나에 대해서는 논의해보는 것도 좋을 것 같네요.
> 또한, 별도의 함수로 뺀다면 결국 이 부분도 레이아웃이기 때문에 viewDidLoad보다는 layout에서 호출하는 것이 더 명확할 것 같습니다.

조!아!요!

2023-01-18 18:26 UTC, taek0622 requested changes
고생하셨습니다~
전반적으로 코드가 전보다 많이 깔끔해졌네요. 많이 성장하신 것 같아서 흐뭇합니다.
전체적으로 아직 SnapKit에 대해 익숙하지 않아서 변경하면 좋을 것 같은 부분이 많았어요.
해당 부분에 리뷰 남겼으니 확인 바랍니다.
또, 일부에서 고치면 좋을 것 같은 부분, 질문 사항 남겼으니 확인 부탁드려요~

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.top.equalTo(snp.top)
p3;
이 부분은 `equalTo(snp.top)`보다는 `equalToSuperView()`가 좋은 사용 방법인 것 같습니다.

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.right.equalTo(snp.right).offset(-16)
p3;
이 부분은 `$0.left.right.equalToSuperView().inset(16)`처럼 바꿀 수 있겠네요.

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +        }
오 이 부분을 top.left와 같이 사용하지 않고 topMargin, leftMargin으로도 사용할 수 있네요.
새로운 사용 방법 알아갑니다. 굳이에요~

p3;
추가로 이 부분도 `$0.topMargin.leftMargin.equalTo(8)`처럼 하나로 통합할 수 있을 것 같습니다.
혹은 `$0.top.left.equalToSuperView().inset(8)`로도 사용할 수 있겠네요.

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.right.equalTo(chipFrame.snp.right).offset(-12)
p3;
이 부분도 아래와 같이 두 줄로 줄일 수 있을 것 같습니다.
```swift
$0.top.bottom.equalTo(chipFrame).inset(8)
$0.left.right.equalTo(chipFrame).inset(12)
```

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.bottom.equalTo(postImage.snp.bottom)
p3;
이 부분도 `$0.bottom.equalToSuperView()`로 변경할 수 있을 것 같습니다.

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.top.equalTo(descriptionBackground.snp.top).offset(12)
p3;
해당 부분도 아래와 같이 두 줄로 변경할 수 있을 것 같습니다.
```swift
$0.left.right.equalTo(descriptionBackground).inset(16)
$0.top.bottom.equalTo(descriptionBackground).inset(12)
```

이 정도면 SnapKit의 기본적인 사용법은 대략 설명된 것 같으니, 다음 파일부터 반복되는 리뷰는 생략하겠습니다.

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Cells/PostDateCell.swift
> +    private let divider2: UIView = {
p1;
디바이더 1, 2는 이름 바꿔주실 거라고 믿어 의심치 않습니다 ^^

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +    }()
p5;
해당 부분은 collectionView 내부에서 collectionView라는 이름의 상수를 하나 더 사용하고 있는데, 약간 헷갈릴 수 있을 것 같네요.
다만, 둘의 의미가 비슷한 의미이기 때문에 반드시 수정할 필요는 없고, 한번쯤 생각해봐주셔도 좋을 것 같습니다.

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +            $0.top.left.bottom.right.equalTo(view)
p3;
이 부분은 `$0.edges.equalToSuperView()`로도 바꿀 수 있답니다.

2023-01-18 18:26 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +            $0.center.equalTo(view.center)
p3;
이 부분도 `$0.center.equalToSuperView()`로 변경 가능하네요.

2023-01-18 18:26 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +        return cell
오 이 부분을 이렇게도 작성할 수 있네요.
cell을 UICollectionViewCell로 우선 초기화하고 저렇게 변경할 수 있다는 건 처음 알았습니다.
좋은 방식 알아갑니다.

참고로 이 방법 말고는 아래와 같은 방식으로도 사용할 수 있습니다. 코드 스타일의 차이라서 반영은 하지 않아도 좋습니다.
```swift
var cell = collectionView.dequeueReusableCell(withReuseIdentifier: HistoryCell.identifier, for: indexPath) as! HistoryCell

if indexPath.row == 0 {
    cell = collectionView.dequeueReusableCell(withReuseIdentifier: PostDateCell.identifier, for: indexPath) as! PostDateCell
}

return cell
```

2023-01-18 18:26 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +    var currentViewNum: Int = 0 {
p2;
해당 부분 접근지정자가 빠진 것 같습니다. 특별히 외부에서 접근해야할 목적이 아니라면 접근지정자를 붙여주세요.

2023-01-18 18:26 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +        pageViewController.didMove(toParent: self)
p5;
관리의 측면에서 필요한 것인지 잘 모르겠으나, pageContentView는 없애도 정상작동 할 것 같습니다.
만약 pageContentView를 제외시킨다면 아래와 같이 코드를 작성할 수 있겠네요.

```swift
view.addSubview(segmentedControl)
self.addChild(pageViewController)
view.addSubview(pageViewController.view)

segmentedControl.snp.makeConstraints {
  $0.top.equalTo(view.safeAreaLayoutGuide.snp.top).offset(12)
  $0.bottom.equalTo(pageViewController.view.snp.top).offset(-12)
  $0.left.equalTo(view.safeAreaLayoutGuide.snp.left).offset(16)
  $0.width.equalTo(180)
  $0.height.equalTo(20)
}

pageViewController.view.snp.makeConstraints {
  $0.width.equalTo(view.snp.width)
  $0.bottom.equalTo(view.snp.bottom)
}
pageViewController.didMove(toParent: self)
```

2023-01-18 18:26 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +                                         barMetrics: .default)
Question;
이 부분이 잘 이해가 안가는데, 혹시 한쪽은 selected, 한쪽은 normal인 이유가 있을까요?
둘 다 normal인 경우에도 보여지는 것 같아보이는데, 무슨 차이인지 궁금합니다~

2023-01-18 18:26 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +        selectedSegmentControl(control: segmentedControl)
p1;
이 문장은 삭제되어도 정상동작을 하네요.

2023-01-18 18:27 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }
> > p1;
> > 해당 부분이 꼬인 것 같네요.
> > attribute function 일부가 잘린 것 같아요.
> > 빌드되지 않아서 정상적으로 확인이 불가능합니다.
> 
> 코드가 전면 수정하여 해결되었습니다.

확인했습니다. 리뷰 리졸브합니다.

2023-01-18 18:27 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +}
> > p1;
> > 해당 부분에도 잘못된 중괄호가 들어간 것 같습니다.
> 
> 코드가 전면 수정하여 해결되었습니다.

확인했습니다. 리뷰 리졸브합니다.

2023-01-18 18:28 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +import SnapKit
> [5c1451a](https://github.com/Samsamhada/Giwazip-Client-App/commit/5c1451ae34fcea99394e7a66f98512a6dbae3385) 반영했습니다.

확인했습니다. 리뷰 리졸브할게요~

2023-01-18 18:39 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +    private func navigationLayout() {
> > p5;
> > 해당 부분을 별도의 함수로 빼는 것, 혹은 함수의 이름 둘 중에 하나에 대해서는 논의해보는 것도 좋을 것 같네요.
> > 또한, 별도의 함수로 뺀다면 결국 이 부분도 레이아웃이기 때문에 viewDidLoad보다는 layout에서 호출하는 것이 더 명확할 것 같습니다.
> 
> 해당 부분에 `navigationItem.titleView = titleView`로 되어 있으며, `titleView` 하위 `addSubView`가 있기에 `Layout`이면서도, `navigation`에 관한 부분이 섞여 모호하다고 생각하고 있던 부분인데 집어주셔서 감사합니다.

<img width="58" alt="스크린샷 2023-01-19 03 39 32" src="https://user-images.githubusercontent.com/81027256/213266446-e04a86ed-33f0-46d7-9459-58975c7768f7.png">
근데 이!댓!글! 어디갔나요? ㅋㅋㅋㅋ

2023-01-19 06:10 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +    var currentViewNum: Int = 0 {
> p2;
> 해당 부분 접근지정자가 빠진 것 같습니다. 특별히 외부에서 접근해야할 목적이 아니라면 접근지정자를 붙여주세요.

0622ff8 반영했습니다.

2023-01-19 06:11 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }()
> p5;
> 해당 부분은 collectionView 내부에서 collectionView라는 이름의 상수를 하나 더 사용하고 있는데, 약간 헷갈릴 수 있을 것 같네요.
> 다만, 둘의 의미가 비슷한 의미이기 때문에 반드시 수정할 필요는 없고, 한번쯤 생각해봐주셔도 좋을 것 같습니다.

d509d1b 수정~

2023-01-19 06:12 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.top.equalTo(snp.top)
> p3;
> 이 부분은 `equalTo(snp.top)`보다는 `equalToSuperView()`가 좋은 사용 방법인 것 같습니다.

44dc5f2 반영했습니다. 다른 Snp관련은 다 닫겠습니다.

2023-01-19 06:13 UTC, JUNY0110 commented on GiwazipClient/Cells/PostDateCell.swift
> +    private let divider2: UIView = {
> p1;
> 디바이더 1, 2는 이름 바꿔주실 거라고 믿어 의심치 않습니다 ^^

cf04424 임시 이름이었는데, 그냥 최종이름으로 바꿨습니다 ^^

2023-01-19 06:13 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +        selectedSegmentControl(control: segmentedControl)
> p1;
> 이 문장은 삭제되어도 정상동작을 하네요.

44dc5f2 snp 정리하면서 같이 삭제했네요 ~

2023-01-19 06:22 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +                                         barMetrics: .default)
> Question;
> 이 부분이 잘 이해가 안가는데, 혹시 한쪽은 selected, 한쪽은 normal인 이유가 있을까요?
> 둘 다 normal인 경우에도 보여지는 것 같아보이는데, 무슨 차이인지 궁금합니다~

정확한 이유는 모르겠지만, 애플 공식문서에서 선택된 세그먼트가 왼쪽, 선택되지 않은 세그먼트가 오른쪽일 때에는 그렇게 하라고 하네요. 
![스크린샷 2023-01-19 오후 3 21 07](https://user-images.githubusercontent.com/98405970/213370150-672d190c-df17-45d6-8e92-6ff10fe4acbd.png)

2023-01-19 12:54 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.top.equalTo(snp.top)
> > p3;
> > 이 부분은 `equalTo(snp.top)`보다는 `equalToSuperView()`가 좋은 사용 방법인 것 같습니다.
> 
> [44dc5f2](https://github.com/Samsamhada/Giwazip-Client-App/commit/44dc5f23fd61f5c1aa1a25a8a3a48de7a25a7f47) 반영했습니다. 다른 Snp관련은 다 닫겠습니다.

확인했습니다. 리뷰 리졸브합니다.

2023-01-19 12:55 UTC, taek0622 commented on GiwazipClient/Cells/PostDateCell.swift
> +    private let divider2: UIView = {
> > p1;
> > 디바이더 1, 2는 이름 바꿔주실 거라고 믿어 의심치 않습니다 ^^
> 
> [cf04424](https://github.com/Samsamhada/Giwazip-Client-App/commit/cf044240eafd9bd5fc1505caef206a2edb6f93cd) 임시 이름이었는데, 그냥 최종이름으로 바꿨습니다 ^^

해당 이름은 LineDot 보다는 DashedLine이나 DotLine이 더 적절할 것 같네요.

2023-01-19 12:56 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }()
> 

확인~ 리졸브~

2023-01-19 12:57 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +    var currentViewNum: Int = 0 {
> > p2;
> > 해당 부분 접근지정자가 빠진 것 같습니다. 특별히 외부에서 접근해야할 목적이 아니라면 접근지정자를 붙여주세요.
> 
> [0622ff8](https://github.com/Samsamhada/Giwazip-Client-App/commit/0622ff8db25a94dae6da2ed65ea9f766758a1604) 반영했습니다.

확인했습니다. 리뷰 리졸브합니다.

2023-01-19 12:58 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +        selectedSegmentControl(control: segmentedControl)
> 

확인했습니다. 리뷰 리졸브합니다.

2023-01-19 13:23 UTC, taek0622 requested changes
고생하셨습니다.
일부 수정이 필요해보이는 부분에 리뷰 남겼습니다. 확인 부탁드려요~

2023-01-19 13:23 UTC, taek0622 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		988C56DC2978349D00018F07 /* HistoryViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 988C56DB2978349D00018F07 /* HistoryViewController.swift */; };
p1;
HistoryViewController가 pbx에 두개가 깔려있는데, 하나 삭제해야할 것 같습니다.
988C56DB2978349D00018F07를 살리고 988C56CF29768F2D00018F07를 삭제해야할 것 같아요.

2023-01-19 13:23 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.borderColor = CGColor.init(red: 0/255, green: 0/255, blue: 0/255, alpha: 1)
p4;
해당 부분은 `UIColor.black.cgColor`로도 변경할 수 있을 것 같네요.

2023-01-19 13:23 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.top.left.equalTo(8)
p5;
이 부분이 뭐에 대한 equalTo인지 명확하지 못한 것 같습니다. equalTo에 그냥 숫자를 넣으면 자연스럽게 superView로 잡히고 있는 것 같긴 하지만, 조금 더 명확할 필요가 있을 것 같아요. 이 부분에 대해서 이야기 해보면 좋을 것 같네요.

2023-01-19 13:23 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +    }
p1;
해당 부분은 viewDidLoad를 override 하기보다는, setupNavigationTitle과 setupSegmentedControl을 attribute나 layout 등 다른 메서드에 넣는 것도 좋을 것 같네요.

혹은 꼭 viewDidLoad를 override해야한다면 이미 super로 attribute와 layout을 가져오고 있으므로 attribute와 layout은 이곳에서 빼는 것이 더 좋을 것 같습니다.

2023-01-19 13:23 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +        pageViewController.didMove(toParent: self)
Question;
해당 구문이 왜 필요한지 궁금합니다. 역할도 궁금해요. 해당 구문을 제외하고 실행해도 정상 작동하는 것 같네요.
공식 문서에서도 생략될 수 있는 경우가 있다고 하는 것 같아요. 그래서 이 구문이 정확히 어떤 역할을 하는지, 왜 필요하는 지 궁금합니다.

2023-01-19 13:23 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +        layout()
p1;
이미 BaseViewController의 viewDidLoad에서 attribute와 layout을 불러오고 있습니다. 이 경우 viewDidLoad가 여기에선 아예 빠져도 될 것 같네요.

2023-01-19 13:41 UTC, JUNY0110 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		988C56DC2978349D00018F07 /* HistoryViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 988C56DB2978349D00018F07 /* HistoryViewController.swift */; };
> p1;
> HistoryViewController가 pbx에 두개가 깔려있는데, 하나 삭제해야할 것 같습니다.
> 988C56DB2978349D00018F07를 살리고 988C56CF29768F2D00018F07를 삭제해야할 것 같아요.

…
ff7a688
소름.. 어케 찾으셨죠

2023-01-19 13:46 UTC, taek0622 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		988C56DC2978349D00018F07 /* HistoryViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 988C56DB2978349D00018F07 /* HistoryViewController.swift */; };
> > p1;
> > HistoryViewController가 pbx에 두개가 깔려있는데, 하나 삭제해야할 것 같습니다.
> > 988C56DB2978349D00018F07를 살리고 988C56CF29768F2D00018F07를 삭제해야할 것 같아요.
> 
> … [ff7a688](https://github.com/Samsamhada/Giwazip-Client-App/commit/ff7a68879ca2f418f99b5f98f95e2b4c030f8dda) 소름.. 어케 찾으셨죠

그냥.. 보이더라구요 ㅎㅎ

2023-01-19 14:23 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.borderColor = CGColor.init(red: 0/255, green: 0/255, blue: 0/255, alpha: 1)
> p4;
> 해당 부분은 `UIColor.black.cgColor`로도 변경할 수 있을 것 같네요.

8a8b636

2023-01-19 14:25 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.top.left.equalTo(8)
> p5;
> 이 부분이 뭐에 대한 equalTo인지 명확하지 못한 것 같습니다. equalTo에 그냥 숫자를 넣으면 자연스럽게 superView로 잡히고 있는 것 같긴 하지만, 조금 더 명확할 필요가 있을 것 같아요. 이 부분에 대해서 이야기 해보면 좋을 것 같네요.

276b9c5 
equalToSuperView가 조금 낫긴하지만 크게 차이가 없는 것 같습니다. 그럼에도 모호함이 느껴진다면, 코드스타일에 대해 다시 얘기해보는게 어떨까요? 현재 addSubView를 한쪽에 모아서 작성하니 레이아웃 작성 간 superView가 무엇을 말하는지 모호하다고 느껴집니다.

2023-01-19 14:26 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +    }
> p1; 해당 부분은 viewDidLoad를 override 하기보다는, setupNavigationTitle과 setupSegmentedControl을 attribute나 layout 등 다른 메서드에 넣는 것도 좋을 것 같네요.
> 
> 혹은 꼭 viewDidLoad를 override해야한다면 이미 super로 attribute와 layout을 가져오고 있으므로 attribute와 layout은 이곳에서 빼는 것이 더 좋을 것 같습니다.

7ace438 굿

2023-01-19 14:26 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +        layout()
> p1;
> 이미 BaseViewController의 viewDidLoad에서 attribute와 layout을 불러오고 있습니다. 이 경우 viewDidLoad가 여기에선 아예 빠져도 될 것 같네요.

7ace438 굿

2023-01-19 14:26 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +            $0.top.left.equalTo(8)
> > p5;
> > 이 부분이 뭐에 대한 equalTo인지 명확하지 못한 것 같습니다. equalTo에 그냥 숫자를 넣으면 자연스럽게 superView로 잡히고 있는 것 같긴 하지만, 조금 더 명확할 필요가 있을 것 같아요. 이 부분에 대해서 이야기 해보면 좋을 것 같네요.
> 
> [276b9c5](https://github.com/Samsamhada/Giwazip-Client-App/commit/276b9c555de98086a9b522a1ba8aa77bb114c876) equalToSuperView가 조금 낫긴하지만 크게 차이가 없는 것 같습니다. 그럼에도 모호함이 느껴진다면, 코드스타일에 대해 다시 얘기해보는게 어떨까요? 현재 addSubView를 한쪽에 모아서 작성하니 레이아웃 작성 간 superView가 무엇을 말하는지 모호하다고 느껴집니다.

네네 이부분은 내일 다시 얘기해보고 싶어서 남겼습니당~

2023-01-19 14:27 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.borderColor = CGColor.init(red: 0/255, green: 0/255, blue: 0/255, alpha: 1)
> > p4;
> > 해당 부분은 `UIColor.black.cgColor`로도 변경할 수 있을 것 같네요.
> 
> [8a8b636](https://github.com/Samsamhada/Giwazip-Client-App/commit/8a8b636be660c6440d8c39c079b28dd3390e5284)

확인했습니다. 리뷰 리졸브합니다~

2023-01-19 14:27 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +    }
> > p1; 해당 부분은 viewDidLoad를 override 하기보다는, setupNavigationTitle과 setupSegmentedControl을 attribute나 layout 등 다른 메서드에 넣는 것도 좋을 것 같네요.
> > 혹은 꼭 viewDidLoad를 override해야한다면 이미 super로 attribute와 layout을 가져오고 있으므로 attribute와 layout은 이곳에서 빼는 것이 더 좋을 것 같습니다.
> 
> [7ace438](https://github.com/Samsamhada/Giwazip-Client-App/commit/7ace4388b0d5a3fe2ad5df0e986274e84a0cbcd0) 굿

확인했습니다. 리뷰 리졸브합니다~

2023-01-19 14:28 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +        layout()
> > p1;
> > 이미 BaseViewController의 viewDidLoad에서 attribute와 layout을 불러오고 있습니다. 이 경우 viewDidLoad가 여기에선 아예 빠져도 될 것 같네요.
> 
> [7ace438](https://github.com/Samsamhada/Giwazip-Client-App/commit/7ace4388b0d5a3fe2ad5df0e986274e84a0cbcd0) 굿

확인했습니다. 리뷰 리졸브합니다~

2023-01-19 14:48 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +        pageViewController.didMove(toParent: self)
> Question;
> 해당 구문이 왜 필요한지 궁금합니다. 역할도 궁금해요. 해당 구문을 제외하고 실행해도 정상 작동하는 것 같네요.
> 공식 문서에서도 생략될 수 있는 경우가 있다고 하는 것 같아요. 그래서 이 구문이 정확히 어떤 역할을 하는지, 왜 필요하는 지 궁금합니다.

7cc9a2f
잘못작성한게 맞습니다. 확인 감사합니다.
`didMove`는 UIVC 또는 PageVC 같은 `ContainerVC`에 다른 VC가 추가/삭제 된 후에 호출이 되는 메서드입니다.
`didMove` 사용은 자식VC가 부모VC로부터 추가, 삭제되는 등의 상황에 반응할 수 있도록 만들어졌습니다. (`didSet`, `willSet`)이 생각나지 않나요? `didMove`는 VC전용 메서드라는 것에 차이가 있습니다.

하지만 현재 저희 앱에서는 pageVC가 부모(SegmentVC)로부터 추가, 삭제되는 경우가 없기 때문에 불필요한 코드가 맞습니다.
하지만 추가 삭제에 반응하는 VC를 만드는 메서드라면, 게시물이 추가될 때마다 반영되도록 networkManager 대신으로도 가능할 수 있겠다는 생각이 들지만 그 활용도까지는 잘 모르겠습니다.

ContainerVC가 얘기가 나온김에 보충설명을 하자면, 주로 ContentView를 관리하는 상위 ViewController라고 생각하면 될 것 같습니다.
기본 제공되는 System ContainerVC에는 UITabBarController, UINavigationController, UIPageViewController, UIViewController 등이 있습니다.
ContainerVC는 단일책임원칙(SRP)을 위해 나왔으며, 화면을 표시해주는 책임을 다른 객체로 분리합니다.
하지만 VC를 직접 생성해야하고, 의존성 주입을 해주는 코드가 필요하다기에 개념적으로만 알아둬도 좋을 것 같네요.

```SWIFT
   @IBAction func pushSecond(_ sender: Any) {
 
    navigationController?.pushViewController(secondVC, animated: true)
   }
```
**참고자료**
[didMove 참고자료](https://0urtrees.tistory.com/191)
[ContainerViewController 참고자료](https://woozzang.tistory.com/145)

2023-01-19 17:22 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +        pageViewController.didMove(toParent: self)
> > Question;
> > 해당 구문이 왜 필요한지 궁금합니다. 역할도 궁금해요. 해당 구문을 제외하고 실행해도 정상 작동하는 것 같네요.
> > 공식 문서에서도 생략될 수 있는 경우가 있다고 하는 것 같아요. 그래서 이 구문이 정확히 어떤 역할을 하는지, 왜 필요하는 지 궁금합니다.
> 
> [7cc9a2f](https://github.com/Samsamhada/Giwazip-Client-App/commit/7cc9a2fcedc236d872bfb1406c8f0d98e656ff77) 잘못작성한게 맞습니다. 확인 감사합니다.
> 
> _**didMove**_
> 
> `didMove`는 UIVC 또는 PageVC 같은 `ContainerVC`에 다른 VC가 추가/삭제 된 후에 호출이 되는 메서드입니다. `didMove` 사용은 자식VC가 부모VC로부터 추가, 삭제되는 등의 상황에 반응할 수 있도록 만들어졌습니다. (`didSet`, `willSet`)이 생각나지 않나요? `didMove`는 VC전용 메서드라는 것에 차이가 있습니다.
> 
> 하지만 현재 저희 앱에서는 pageVC가 부모(SegmentVC)로부터 추가, 삭제되는 경우가 없기 때문에 불필요한 코드가 맞습니다. 하지만 추가 삭제에 반응하는 VC를 만드는 메서드라면, 게시물이 추가될 때마다 반영되도록 networkManager 대신으로도 가능할 수 있겠다는 생각이 들지만 그 활용도까지는 잘 모르겠습니다.
> 
> _**ContainerViewController**_
> 
> ContainerVC가 얘기가 나온김에 보충설명을 하자면, 주로 ContentView를 관리하는 상위 ViewController라고 생각하면 될 것 같습니다. 기본 제공되는 System ContainerVC에는 UITabBarController, UINavigationController, UIPageViewController, UIViewController 등이 있습니다. ContainerVC는 단일책임원칙(SRP)을 위해 나왔으며, 화면을 표시해주는 책임을 다른 객체로 분리합니다. 하지만 VC를 직접 생성해야하고, 의존성 주입을 해주는 코드가 필요하다기에 개념적으로만 알아둬도 좋을 것 같네요.
> 
> ```swift
>    @IBAction func pushSecond(_ sender: Any) {
>  
>     navigationController?.pushViewController(secondVC, animated: true)
>    }
> ```
> 
> **참고자료** [didMove 참고자료](https://0urtrees.tistory.com/191) [ContainerViewController 참고자료](https://woozzang.tistory.com/145)

확인했습니다. 해당 부분에 대해서는 더 알아보고 이야기해보면 좋을 것 같네요.

2023-01-19 17:45 UTC, taek0622 reviewed
고생하셨습니다.
기존에 투명도 부분에서 문제가 생겨서 다르게 구현했던 부분에 대해 고칠 방법이 떠올라서 방법 제시해보았습니다.
해당 부분에 대해 확인 후에 같이 의견 나눠보고 싶어요~

2023-01-19 17:45 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.opacity = 0.8
p3;
해당 부분을 layer의 opacity로 주지않고 그냥 `$0.backgroundColor = UIColor(wthie: 1, alpha: 0.8)`과 같이 표현하면, 기존과 색은 같으면서 chipLabel을 chipFrame에 addSubView 했을 때, 함께 opacity가 먹는 문제가 해결됩니다.

2023-01-19 17:45 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.opacity = 0.7
p3;
마찬가지로 이곳도 layer의 opacity로 주지않고, `$0.backgroundColor = UIColor(white: 0, alpha: 0.7)`과 같이 주면 `descriptionBackgrouond.addSubView(postDescription)`을 해도 opacity가 글자에는 먹지 않게 됩니다.

2023-01-19 17:45 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +        postImage.addSubview(postDescription)
p4;
위 부분을 layer의 Opacity가 아니라, background로 고치고 이부분도 postImage에서 전부 addSubView를 하는게 아니라, 계층에 맞게 다시 addSubView를 먹이는 것이 어떨까요?

2023-01-19 17:45 UTC, taek0622 commented on GiwazipClient/Cells/PostDateCell.swift
> +    }(UIView())
p4;
이 부분 리뷰가 왜 숨겨졌는지 모르겠습니다만, LineDot이라는 이름보다는 DashLine이나 DotLine이 어떨까요?

2023-01-20 02:50 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.opacity = 0.8
> p3;
> 해당 부분을 layer의 opacity로 주지않고 그냥 `$0.backgroundColor = UIColor(wthie: 1, alpha: 0.8)`과 같이 표현하면, 기존과 색은 같으면서 chipLabel을 chipFrame에 addSubView 했을 때, 함께 opacity가 먹는 문제가 해결됩니다.

cf33db5 반영~

2023-01-20 02:52 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.opacity = 0.8
> p3;
> 해당 부분을 layer의 opacity로 주지않고 그냥 `$0.backgroundColor = UIColor(wthie: 1, alpha: 0.8)`과 같이 표현하면, 기존과 색은 같으면서 chipLabel을 chipFrame에 addSubView 했을 때, 함께 opacity가 먹는 문제가 해결됩니다.

cf33db5 반영~

2023-01-20 02:58 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.opacity = 0.8
> > p3;
> > 해당 부분을 layer의 opacity로 주지않고 그냥 `$0.backgroundColor = UIColor(wthie: 1, alpha: 0.8)`과 같이 표현하면, 기존과 색은 같으면서 chipLabel을 chipFrame에 addSubView 했을 때, 함께 opacity가 먹는 문제가 해결됩니다.
> 
> [cf33db5](https://github.com/Samsamhada/Giwazip-Client-App/commit/cf33db5f2df02b3d499f9f7045df24bdc73839af) 반영~

확인했습니다. 리뷰 리졸브할게요.

2023-01-20 03:10 UTC, JUNY0110 commented on GiwazipClient/Cells/PostDateCell.swift
> +    }(UIView())
> p4;
> 이 부분 리뷰가 왜 숨겨졌는지 모르겠습니다만, LineDot이라는 이름보다는 DashLine이나 DotLine이 어떨까요?

46bb71e 반영~

2023-01-20 03:10 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.opacity = 0.7
> p3;
> 마찬가지로 이곳도 layer의 opacity로 주지않고, `$0.backgroundColor = UIColor(white: 0, alpha: 0.7)`과 같이 주면 `descriptionBackgrouond.addSubView(postDescription)`을 해도 opacity가 글자에는 먹지 않게 됩니다.

5230c5c 반영~

2023-01-20 03:10 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +        postImage.addSubview(postDescription)
> p4;
> 위 부분을 layer의 Opacity가 아니라, background로 고치고 이부분도 postImage에서 전부 addSubView를 하는게 아니라, 계층에 맞게 다시 addSubView를 먹이는 것이 어떨까요?

5230c5c 반영~

2023-01-20 03:11 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +        $0.layer.opacity = 0.7
> 

확인했습니다. 리뷰 리졸브합니다~

2023-01-20 03:12 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +        postImage.addSubview(postDescription)
> > p4;
> > 위 부분을 layer의 Opacity가 아니라, background로 고치고 이부분도 postImage에서 전부 addSubView를 하는게 아니라, 계층에 맞게 다시 addSubView를 먹이는 것이 어떨까요?
> 
> [5230c5c](https://github.com/Samsamhada/Giwazip-Client-App/commit/5230c5cacba5c1c0aa7dc7cd00aebc931e217df6) 반영~

확인했습니다. 리뷰 리졸브합니다~

2023-01-20 04:06 UTC, taek0622 commented on GiwazipClient/Cells/PostDateCell.swift
> +    }(UIView())
확인했습니다. 리뷰 리졸브합니다~

2023-01-20 04:08 UTC, creohwan reviewed
고생하셨습니다!

2023-01-20 04:08 UTC, creohwan commented on GiwazipClient/Cells/HistoryCell.swift
> +    }
Q;
여기서 override init이 아닌, override private init으로 준 이유가 있으실까요?! 업자용에서는 다 override init이어서 혹시나 다른 이유가 있나 싶어서 여쭤봅니다!

2023-01-20 04:08 UTC, creohwan commented on GiwazipClient/Cells/PostDateCell.swift
> +            $0.left.centerY.equalToSuperview()
Q: 여기서 centerY.equalToSuperview() 의 의미는 superview의 centerY에 centerY를 맞춘다는 의미일까요?!

2023-01-20 04:08 UTC, taek0622 approved these changes
고생하셨습니다. 도중도중에 코드 스타일 등의 회의로 인해서 수정사항이 정말 많았는데, 전부 맞춰서 바로 고쳐주셔서 너무 감사합니다.
또, 스냅킷에 이제 어느정도 잘 적응하신 것 같네요.
앞으로도 잘 부탁드려요 에디~

2023-01-20 04:10 UTC, JUNY0110 commented on GiwazipClient/Cells/PostDateCell.swift
> +            $0.left.centerY.equalToSuperview()
> 

넵 맞습니다

2023-01-20 04:13 UTC, JUNY0110 commented on GiwazipClient/Cells/PostDateCell.swift
> +            $0.left.centerY.equalToSuperview()
> Q: 여기서 centerY.equalToSuperview() 의 의미는 superview의 centerY에 centerY를 맞춘다는 의미일까요?!

넵 맞습니다

2023-01-20 04:25 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +    }
> Q;
> 여기서 override init이 아닌, override private init으로 준 이유가 있으실까요?! 업자용에서는 다 override init이어서 혹시나 다른 이유가 있나 싶어서 여쭤봅니다!

있어도 없어도 크게 차이는 없긴합니다. 실제로 외부에서 건드릴 일은 거의 없으니까요

단순히 init(frame: CGRect)가 CollectionViewCell을 이루는 LifeCycle을 initialize하는 것을 말합니다.
근데 외부에서 `ProgressHeader.init(frame:  )`을 하게 되면 외부에서도 `init`에 접근이 가능하기 때문에 private을 반영했습니당

이렇게 보니 Cell의 LifeCycle도 BaseViewCell 등을 만들어서 통합관리가 가능하겠네요!

2023-01-20 04:30 UTC, creohwan approved these changes
스냅킷의 사용 변천사가 보이는 군요! 고생하셨습니다 : )

2023-01-20 04:35 UTC, merged