Design/12 enterview layout second
Samsamhada/Giwazip-Client-App pull request #17
Opened 2023-01-19 13:54 UTC by creohwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- EnterView 완료

## Key Changes 🔥 (주요 구현/변경 사항)
- 전화번호 입력 textfield 구현 (하이픈 + 8자 제한)
- 초대코드 입력 textfield 구현 ( 초대코류 오류시 알럿 처리 )
- 버튼 활성화 비활성화 조건 추가
- hidekeyboardWhenTappedAround() extension 추가

## ToDo 📆 (남은 작업)
- [ ] 추후 초대코드 확인 API 통신 구현 요

## ScreenShot 📷 (참고 사진)

https://user-images.githubusercontent.com/92836045/213458901-241013fd-30a1-4e74-8595-98ada343e06a.MP4

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 감사합니다!

## Reference 🔗
- textfield 키보드 종류
https://ikkison.tistory.com/18

## Close Issues 🔒 (닫을 Issue)
Close #12

2023-01-19 18:16 UTC, taek0622 requested changes
고생하셨습니다.
수정이 필요한 부분에 리뷰 남겼습니다.
또한, 저희 오토레이아웃에서 view.safeAreaLayoutGuide가 아니라 그냥 뷰에 맞추기로 했으므로 스냅킷 부분 수정 부탁드려요~

2023-01-19 18:16 UTC, ikanic commented on GiwazipClient/Views/EnterViewController.swift
> +    @objc func checkPhoneNumberLenght() {
p2;
checkPhoneNumberLenght의 마지막 부분에서 오타가 난 것 같습니다. 아마 Length가 원래 작성하시려던 이름일 것 같네요.

2023-01-19 18:16 UTC, ikanic commented on GiwazipClient/Views/EnterViewController.swift
> +    }
p1;
현재 전화번호는 전부 입력한 상태에서, 초대코드가 한글자라도 입력되어 있으면 버튼이 활성화되는 것 같은데, 초대코드가 6글자일 때만 활성화되도록 변경해야 할 것 같습니다.
또한, 어차피 초대코드가 6자리로 고정이므로 초대코드 입력을 최대 6자로 제한할 수는 없을까요?

2023-01-19 18:16 UTC, ikanic commented on GiwazipClient/Views/EnterViewController.swift
> +    }
p5;
저희 앱에서 경고창이 나오는 부분들이 몇 부분 있는데, 이 함수가 공통으로 사용될 수 있을 것 같네요.
이 친구를 UIViewController의 Extension으로 옮기는 것은 어떨까요?

p3; 또한 title과 message 사이에 공백이 없네요. nil,message` 사이에 공백이 한칸 필요해요~

2023-01-19 18:16 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +    }
아 이부분도 공통되는 부분이 많은데, 뭔가 뺄수 있을 듯 하면서도 애매하네요.. 방법 연구해보겠습니다.

p3;
keyboardWillHide에서 Notification:NSNOtification 사이에 공백이 한칸 필요해요~

2023-01-20 00:19 UTC, creohwan commented
a45674e 좌우 레이아웃 수정했습니다!

2023-01-20 00:23 UTC, creohwan commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> 아 이부분도 공통되는 부분이 많은데, 뭔가 뺄수 있을 듯 하면서도 애매하네요.. 방법 연구해보겠습니다.
> 
> p3; keyboardWillHide에서 Notification:NSNOtification 사이에 공백이 한칸 필요해요~

b3859eb 좋습니다!

2023-01-20 00:23 UTC, creohwan commented on GiwazipClient/Views/EnterViewController.swift
> +    @objc func checkPhoneNumberLenght() {
> p2; checkPhoneNumberLenght의 마지막 부분에서 오타가 난 것 같습니다. 아마 Length가 원래 작성하시려던 이름일 것 같네요.

b3859eb 으악! 어쩐지 뭔가 이상하다 싶었는데... 감사합니다 : )

2023-01-20 00:38 UTC, creohwan commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> p5; 저희 앱에서 경고창이 나오는 부분들이 몇 부분 있는데, 이 함수가 공통으로 사용될 수 있을 것 같네요. 이 친구를 UIViewController의 Extension으로 옮기는 것은 어떨까요?
> 
> p3; 또한 title과 message 사이에 공백이 없네요. nil,message` 사이에 공백이 한칸 필요해요~

9c11599 d1557c8 감사합니다! 
Alert+ 에 2개의 함수 만들었습니다. 첫 번째는 그냥 알림 알랏 (확인)이고, 두 번째는 특정한 행동을 요구하는 알랏입니다. (확인 or 취소) ( 지금 or 나중에) 등

2023-01-20 01:03 UTC, creohwan commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> p1; 현재 전화번호는 전부 입력한 상태에서, 초대코드가 한글자라도 입력되어 있으면 버튼이 활성화되는 것 같은데, 초대코드가 6글자일 때만 활성화되도록 변경해야 할 것 같습니다. 또한, 어차피 초대코드가 6자리로 고정이므로 초대코드 입력을 최대 6자로 제한할 수는 없을까요?

0c96a04 좋습니다~ 추후 자리수 제한하는 것이 또 필요하다면 checkStringLength 함수를 extension으로 빼는 것도 좋을 것 같습니다!~

2023-01-20 01:14 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +    @objc func checkPhoneNumberLenght() {
> > p2; checkPhoneNumberLenght의 마지막 부분에서 오타가 난 것 같습니다. 아마 Length가 원래 작성하시려던 이름일 것 같네요.
> 
> [b3859eb](https://github.com/Samsamhada/Giwazip-Client-App/commit/b3859ebb216a0abb9af603bc2070d104395a5d67) 으악! 어쩐지 뭔가 이상하다 싶었는데... 감사합니다 : )

확인했습니다. 리뷰 리졸브합니다.

2023-01-20 04:13 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> > p1; 현재 전화번호는 전부 입력한 상태에서, 초대코드가 한글자라도 입력되어 있으면 버튼이 활성화되는 것 같은데, 초대코드가 6글자일 때만 활성화되도록 변경해야 할 것 같습니다. 또한, 어차피 초대코드가 6자리로 고정이므로 초대코드 입력을 최대 6자로 제한할 수는 없을까요?
> 
> [0c96a04](https://github.com/Samsamhada/Giwazip-Client-App/commit/0c96a04b7500e32eebdbb206dc84f7a1e22c72f5) 좋습니다~ 추후 자리수 제한하는 것이 또 필요하다면 checkStringLength 함수를 extension으로 빼는 것도 좋을 것 같습니다!~

checkStringLength 메서드를 따로 빼서 공통으로 사용하고 있는 부분 아주 좋네요.
고객용에서는 이 뷰에서 밖에 사용되지 않지만, 업자용 어플에서는 Extension으로 빼도 좋을 것 같아요. 굳 입니다~

2023-01-20 04:16 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> > p5; 저희 앱에서 경고창이 나오는 부분들이 몇 부분 있는데, 이 함수가 공통으로 사용될 수 있을 것 같네요. 이 친구를 UIViewController의 Extension으로 옮기는 것은 어떨까요?
> > p3; 또한 title과 message 사이에 공백이 없네요. nil,message` 사이에 공백이 한칸 필요해요~
> 
> [9c11599](https://github.com/Samsamhada/Giwazip-Client-App/commit/9c115990b2b506b2e5a9fef5d7ef7797ccc9e850) [d1557c8](https://github.com/Samsamhada/Giwazip-Client-App/commit/d1557c8b07ed03cdadcfeda019a6ee6b14f4a6a3) 감사합니다! Alert+ 에 2개의 함수 만들었습니다. 첫 번째는 그냥 알림 알랏 (확인)이고, 두 번째는 특정한 행동을 요구하는 알랏입니다. (확인 or 취소) ( 지금 or 나중에) 등

확인했습니다. 당장은 버튼이 여러개 필요한 경우가 없지만, 필요한 경우가 생긴다면 두번째 경고창을 사용해도 좋을 것 같네요.

p5;
한 가지 제안해보자면, 두 메서드 전부 경고창에 대한 부분이고, 차이가 버튼의 개수의 차이라면 메서드를 오버로딩해보는 건 어떨까 생각이 들기도 합니다. 다만, 두 경고창이 아주 같은 역할이라고 하긴 어려워서 꼭 오버로딩을 하지 않아도 괜찮긴 할 것 같네요.

2023-01-20 04:19 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> > 아 이부분도 공통되는 부분이 많은데, 뭔가 뺄수 있을 듯 하면서도 애매하네요.. 방법 연구해보겠습니다.
> > p3; keyboardWillHide에서 Notification:NSNOtification 사이에 공백이 한칸 필요해요~
> 
> [b3859eb](https://github.com/Samsamhada/Giwazip-Client-App/commit/b3859ebb216a0abb9af603bc2070d104395a5d67) 좋습니다!

확인했습니다~

2023-01-20 04:27 UTC, taek0622 approved these changes
고생하셨습니다.
이번 디너 코드에는 익스텐션이 많네요.
여러 모로 활용 가능한 코드가 많아서 좋은 것 같습니다.
추가적인 리뷰는 없고, 전에 남겼던 리뷰에 약간의 코멘트 추가했습니다. 해당 부분 확인해주시면 감사할 것 같습니다~

2023-01-20 04:37 UTC, creohwan commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> > > p5; 저희 앱에서 경고창이 나오는 부분들이 몇 부분 있는데, 이 함수가 공통으로 사용될 수 있을 것 같네요. 이 친구를 UIViewController의 Extension으로 옮기는 것은 어떨까요?
> > > p3; 또한 title과 message 사이에 공백이 없네요. nil,message` 사이에 공백이 한칸 필요해요~
> > 
> > 
> > [9c11599](https://github.com/Samsamhada/Giwazip-Client-App/commit/9c115990b2b506b2e5a9fef5d7ef7797ccc9e850) [d1557c8](https://github.com/Samsamhada/Giwazip-Client-App/commit/d1557c8b07ed03cdadcfeda019a6ee6b14f4a6a3) 감사합니다! Alert+ 에 2개의 함수 만들었습니다. 첫 번째는 그냥 알림 알랏 (확인)이고, 두 번째는 특정한 행동을 요구하는 알랏입니다. (확인 or 취소) ( 지금 or 나중에) 등
> 
> 확인했습니다. 당장은 버튼이 여러개 필요한 경우가 없지만, 필요한 경우가 생긴다면 두번째 경고창을 사용해도 좋을 것 같네요.
> 
> p5; 한 가지 제안해보자면, 두 메서드 전부 경고창에 대한 부분이고, 차이가 버튼의 개수의 차이라면 메서드를 오버로딩해보는 건 어떨까 생각이 들기도 합니다. 다만, 두 경고창이 아주 같은 역할이라고 하긴 어려워서 꼭 오버로딩을 하지 않아도 괜찮긴 할 것 같네요.
> 
> 그리고 `makeRequestAlert`의 이름이 약간 모호하다는 생각이 들기도 합니다. 확인/취소가 가능하다는 의미라면 `makeConfirmAlert`도 괜찮을 것 같고, 여러 다른 이름 대안을 생각해보는 것이 좋을 것 같습니다. requset라는 단어가 요청을 의미하긴 하지만 주로 서버와의 통신에서 사용되다보니 약간 애매하다는 느낌이 들어서요.

bb64b3c 확인했습니다!~ 완전히 역할은 같진 않지만, 비슷한 것 같아서, 오버로딩 괜찮은 것 같아요!

2023-01-20 04:54 UTC, JUNY0110 requested changes
고생하셨습니다! 코드가 진짜 진짜 좋아진 것 같습니다

2023-01-20 04:54 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.keyboardType = .asciiCapable
default가 아닌 asciiCapable을 사용해서 특수문자나 한글입력을 막는 디테일 좋은 것 같습니다 👍

2023-01-20 04:54 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +
P2. 
버튼 글씨 색이 변경되지 않고 있는 것 같습니다

guard let 적극활용 굿

2023-01-20 04:54 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.addTarget(self, action: #selector(checkPhoneNumberLength), for: .editingChanged)
Q.
`.numberPad`를 사용해 키보드를 입력하면 이와같은 로그가 나타납니다.
numberPad 를 지원하는 게 없다는데 어떤 이유인지 잘 모르겠네요

`Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad;`

2023-01-20 04:56 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> 아 이부분도 공통되는 부분이 많은데, 뭔가 뺄수 있을 듯 하면서도 애매하네요.. 방법 연구해보겠습니다.
> 
> p3; keyboardWillHide에서 Notification:NSNOtification 사이에 공백이 한칸 필요해요~

공통사용이 적어서 따로 빼지 않아도 될 것 같습니다~

2023-01-20 04:56 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.addTarget(self, action: #selector(checkPhoneNumberLength), for: .editingChanged)
> Q. `.numberPad`를 사용해 키보드를 입력하면 이와같은 로그가 나타납니다. numberPad 를 지원하는 게 없다는데 어떤 이유인지 잘 모르겠네요
> 
> `Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad;`

해당 부분은 시뮬레이터 상에서 발생하는 워닝입니다.
하드웨어 키보드가 체크되어 있어서 발생하는 문제인데, 실제로 문제가 있진 않습니다.

2023-01-20 04:56 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.keyboardType = .asciiCapable
> default가 아닌 asciiCapable을 사용해서 특수문자나 한글입력을 막는 디테일 좋은 것 같습니다 👍

asciiCapable로도 특수문자는 들어간답니다. 하지만, 한글입력을 막은 것은 아주 좋네요.

2023-01-20 04:58 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +    }
> > 아 이부분도 공통되는 부분이 많은데, 뭔가 뺄수 있을 듯 하면서도 애매하네요.. 방법 연구해보겠습니다.
> > p3; keyboardWillHide에서 Notification:NSNOtification 사이에 공백이 한칸 필요해요~
> 
> 공통사용이 적어서 따로 빼지 않아도 될 것 같습니다~

해당 앱에서는 확실히 그런것 같습니다. 다만, 업자용 앱에서는 사용될 일이 많으므로 연구는 별도로 해보겠습니다.

2023-01-20 04:59 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.keyboardType = .asciiCapable
> 

오타입니다~

2023-01-20 05:01 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.addTarget(self, action: #selector(checkPhoneNumberLength), for: .editingChanged)
> > Q. `.numberPad`를 사용해 키보드를 입력하면 이와같은 로그가 나타납니다. numberPad 를 지원하는 게 없다는데 어떤 이유인지 잘 모르겠네요
> > `Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad;`
> 
> 해당 부분은 시뮬레이터 상에서 발생하는 워닝입니다. 하드웨어 키보드가 체크되어 있어서 발생하는 문제인데, 실제로 문제가 있진 않습니다.

글쎄요. 문제가 없는건 맞지만, 하드웨어 키보드를 체크하지 않아도 발생하는 워닝이라 질문했습니다~

2023-01-20 05:06 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.addTarget(self, action: #selector(checkPhoneNumberLength), for: .editingChanged)
> > 해당 부분은 시뮬레이터 상에서 발생하는 워닝입니다. 하드웨어 키보드가 체크되어 있어서 발생하는 문제인데, 실제로 문제가 있진 않습니다.
> 
> 글쎄요. 문제가 없는건 맞지만, 하드웨어 키보드를 체크하지 않아도 발생하는 워닝이라 질문했습니다~

해당 부분은 Xcode의 버그라는 보고가 있긴 합니다만, 하드웨어 키보드를 체크해제해서 문제가 해결되는 경우도 있고, 혹은 텍스트 필드의 사이즈를 조정해서 해결되는 경우도 있고, 그 무엇으로도 해결되지 않는 경우도 있다고 합니다.
다만, 실제로 에러가 아닌 경고일 뿐이고, 문제가 되는 부분은 아니어서 그냥 두어도 괜찮을 것 같습니다.

2023-01-22 02:50 UTC, creohwan commented on GiwazipClient/Views/EnterViewController.swift
> +
> P2. 버튼 글씨 색이 변경되지 않고 있는 것 같습니다
> 
> guard let 적극활용 굿

5746f9c 감사합니다~

2023-01-22 07:13 UTC, JUNY0110 approved these changes
고생하셨습니다~

2023-01-23 01:58 UTC, merged