[Feature] 문의내역 사진 업로드 셀 기능 추가
Samsamhada/Giwazip-Client-App pull request #25
Opened 2023-01-24 05:40 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 문의내역 사진 추가, 수정, 삭제할 수 있도록 하기 위함.
- 사진 없을 때, 사진 필수임을 사용자에게 알리기 위함
- 사진 최대 장수 제한하기 위함
- 사진 미리보기를 추가하기 위함.

## Key Changes 🔥 (주요 구현/변경 사항)
- 사진 업로드 / 사진 셀
  - [ ] 사진 업로드 가능한 셀 보여주기
  - [ ] 이미 업로드된 경우 사진 셀 보여주기
- 사진 업로드 셀 클릭
  - [ ] 사진 업로드 셀 클릭시 갤러리 형태로 포토 피커 보여주기
  - [ ] 포토 피커에서 최대 5개까지 사진 선택 가능
- 사진 셀
  - [ ] 사진이 업로드 되었을 경우 사진을 보여주는 셀 보여주기
  - [ ] 사진 셀 클릭시 사진 수정, 사진 삭제 가능

## ToDo 📆 (남은 작업)
- [ ] 이미지 순서가 바뀌는 버그
- [ ] 이미지가 사라지는 버그
- [ ] 사진 라이브러리 권한 알림

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 14 Pro - 2023-01-24 at 14 28 32](https://user-images.githubusercontent.com/98405970/214218687-bab16ff8-c287-48fd-966f-e1b2be4f1a1a.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 일부 버그가 있으나, 현재 작업한 내용까지 PR올렸습니다. 
- 추가 버그 발생 시 어떤 상황에서의 버그인지 체크해주시면 감사하겠습니다.
- **UIButtonConfiguration사용 이유**
  - 기존 ContentEdgeInsets는 iOS 15.0에서 Deprecated되어, 16버전까지는 지원이 되나, 이후 버전부터는 지원여부를 알 수 없기 때문임.
  - <img width="1038" alt="스크린샷 2023-01-24 오후 2 36 55" src="https://user-images.githubusercontent.com/98405970/214219755-a2c98421-6b13-4e31-8719-3c174f30efa9.png">
  - UIButtonConfiguration사용 시, 기본 버튼 UI에 CornerRadius가 반영되어 있는 것으로 보아, Apple에서는 일관된 기본 버튼 UI를 적용시키려는 것으로 생각되어지네요.

## Reference 🔗
- [PHPicker 참고자료](https://velog.io/@wannabe_eung/앨범의-이미지를-선택할-수-있는-PHPickerViewController를-알아보자)
- [UIButtonConfiguration 참고자료](https://velog.io/@wannabe_eung/iOS-UIButton-Configuration-사용해보기-in-iOS-15)

## Close Issues 🔒 (닫을 Issue)
Close #22.

2023-01-24 11:51 UTC, taek0622 requested changes
고생하셨습니다.
코드가 길지는 않지만, 전체적으로 뭔가 상당히 어렵네요.
고생 많으셨습니다. 일부 수정이 필요해보이는 부분에 리뷰 남겼습니다. 확인 부탁드려요~

2023-01-24 11:51 UTC, ikanic commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    }
p2;
해당 부분은 이미 디너가 만든 makeAlert 익스텐션이 존재합니다. 이미 만들어진 함수 사용을 하는 것이 더 좋을 것 같네요.
버튼에 액션을 붙이기 위해 Objc 함수는 하나 필요하니 내부 내용에서 makeAlert를 불러오면 될 것 같습니다.

2023-01-24 11:51 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var configuration = PHPickerConfiguration()
p4;
버튼 안의 configuration이라는 어트리뷰트와 PHPickerConfiguration 인스턴스인 configuration이라는 프로퍼티가 약간 헷갈리는데 프로퍼티 이름을 피커의 configuration이라는 느낌으로 약간 변경을 주면 어떨까요?

2023-01-24 11:51 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        present(actionSheet, animated: true)
p5;
해당 부분을 포함하도록 기존 alert extension을 변경할 수도 있을 것 같네요.
다만, 지금 상황에서는 actionSheet가 여러 뷰에서 사용되지는 않아서 이 부분은 그냥 두어도 괜찮을 것 같습니다.

2023-01-24 11:51 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var isChangedConfigure = false
Question;
이 프로퍼티가 어떤 용도로 사용되는지 잘 이해가 안 가는데 설명 부탁드립니다~

2023-01-24 13:10 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var isChangedConfigure = false
> Question;
> `isChangedConfigure` 프로퍼티가 어떤 용도로 사용되는지 잘 이해가 안 가는데 설명 부탁드립니다~

isChangedConfigure가 true이면, 사진추가
false이면, 사진 변경 시 사용하도록 하기 위한 Bool값입니다.

2023-01-24 13:15 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        present(actionSheet, animated: true)
> p5;
> 해당 부분을 포함하도록 기존 alert extension을 변경할 수도 있을 것 같네요.
> 다만, 지금 상황에서는 actionSheet가 여러 뷰에서 사용되지는 않아서 이 부분은 그냥 두어도 괜찮을 것 같습니다.

네 여기밖에 사용 안 될 것 같네요~

2023-01-24 13:24 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var isChangedConfigure = false
> > Question;
> > `isChangedConfigure` 프로퍼티가 어떤 용도로 사용되는지 잘 이해가 안 가는데 설명 부탁드립니다~
> 
> isChangedConfigure가 true이면, 사진추가 false이면, 사진 변경 시 사용하도록 하기 위한 Bool값입니다. 더 좋은 방법 있으면 추천해주시면 감사하겠습니다.

확인했습니다. 뭔가 사진 같긴한데 변수명이 configure라서 설정인가? 헷갈렸던 것 같아요. 설명 감사합니다.

2023-01-24 13:37 UTC, taek0622 requested changes
테스트 도중 오류를 발견하여 추가 리뷰 남깁니다.

2023-01-24 13:37 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            self.images.remove(at: self.selectedIndex)
p1;
해당 부분에서 문제 발생합니다.
두 코드의 순서가 바뀌어야할 것 같네요.

2023-01-24 14:28 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var configuration = PHPickerConfiguration()
> p4;
> 버튼 안의 configuration이라는 어트리뷰트와 PHPickerConfiguration 인스턴스인 configuration이라는 프로퍼티가 약간 헷갈리는데 프로퍼티 이름을 피커의 configuration이라는 느낌으로 약간 변경을 주면 어떨까요?

bb82cb4 pickerConfiguration으로 수정했습니다~

2023-01-24 14:29 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var configuration = PHPickerConfiguration()
> > p4;
> > 버튼 안의 configuration이라는 어트리뷰트와 PHPickerConfiguration 인스턴스인 configuration이라는 프로퍼티가 약간 헷갈리는데 프로퍼티 이름을 피커의 configuration이라는 느낌으로 약간 변경을 주면 어떨까요?
> 
> [bb82cb4](https://github.com/Samsamhada/Giwazip-Client-App/commit/bb82cb4aa3077ced9b5f1a12aaa4e43d91c0c2ce) pickerConfiguration으로 수정했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-01-24 14:31 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        present(actionSheet, animated: true)
> p5;
> 해당 부분을 포함하도록 기존 alert extension을 변경할 수도 있을 것 같네요.
> 다만, 지금 상황에서는 actionSheet가 여러 뷰에서 사용되지는 않아서 이 부분은 그냥 두어도 괜찮을 것 같습니다.

1ddadc1
ViewController  extension에 너무 많은 코드가 담겨있는 것 같아 makeActionSheet로 별도 extension을 분리하였습니다. 
재사용되지 않으나 별도 분리한 이유는 makeAlert와 통용해서 사용이 가능하다면 하나로 통합해보기 위함입니다.

2023-01-24 14:32 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    }
> p2;
> 해당 부분은 이미 디너가 만든 makeAlert 익스텐션이 존재합니다. 이미 만들어진 함수 사용을 하는 것이 더 좋을 것 같네요.
> 버튼에 액션을 붙이기 위해 Objc 함수는 하나 필요하니 내부 내용에서 makeAlert를 불러오면 될 것 같습니다.

1ddadc1
반영했습니다. 코드 수정 간 함께 적용되어 사진을 추가 첨부합니다.
<img width="764" alt="스크린샷 2023-01-24 오후 11 32 20" src="https://user-images.githubusercontent.com/98405970/214322003-f93889dd-22f6-4ac1-8dbb-ca0b25ea5be0.png">

2023-01-24 14:50 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        present(actionSheet, animated: true)
> > p5;
> > 해당 부분을 포함하도록 기존 alert extension을 변경할 수도 있을 것 같네요.
> > 다만, 지금 상황에서는 actionSheet가 여러 뷰에서 사용되지는 않아서 이 부분은 그냥 두어도 괜찮을 것 같습니다.
> 
> [1ddadc1](https://github.com/Samsamhada/Giwazip-Client-App/commit/1ddadc11a55a0890ede819b41439b4854503b460) ViewController extension에 너무 많은 코드가 담겨있는 것 같아 makeActionSheet로 별도 extension을 분리하였습니다. 재사용되지 않으나 별도 분리한 이유는 makeAlert와 통용해서 사용이 가능하다면 하나로 통합해보기 위함입니다.

기존 댓글이 사라졌네요.
좋은 시도인 것 같습니다. 그리고 이 커밋으로 훨씬 코드가 가독성이 좋아진 것 같네요. 아주 좋습니다. 굳~

2023-01-24 14:51 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    }
> > p2;
> > 해당 부분은 이미 디너가 만든 makeAlert 익스텐션이 존재합니다. 이미 만들어진 함수 사용을 하는 것이 더 좋을 것 같네요.
> > 버튼에 액션을 붙이기 위해 Objc 함수는 하나 필요하니 내부 내용에서 makeAlert를 불러오면 될 것 같습니다.
> 
> [1ddadc1](https://github.com/Samsamhada/Giwazip-Client-App/commit/1ddadc11a55a0890ede819b41439b4854503b460) 반영했습니다. 코드 수정 간 함께 적용되어 사진을 추가 첨부합니다. <img alt="스크린샷 2023-01-24 오후 11 32 20" width="764" src="https://user-images.githubusercontent.com/98405970/214322003-f93889dd-22f6-4ac1-8dbb-ca0b25ea5be0.png">

확인했습니다.
한가지, 해당 부분에서 디너가 짠 makeAlert 함수의 title이 nil일 때와 ""일 때의 결과물에 차이가 있어서 해당 부분에 대해 회의 때 이야기해보는 것이 좋을 것 같네요.

2023-01-25 00:46 UTC, creohwan reviewed
주절주절 생각나는 걸 그냥 적어보았던 것 같습니다.

확실히 제가 예전에 했던 코드보다 깔끔해진 것 같네요! 고생하셨습니다!

2023-01-25 00:46 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
>              $0.top.equalTo(view.safeAreaLayoutGuide.snp.top).offset(12)
p3;
view.safeAreaLayoutGuide.snp.top 까지 붙이신 특별한 이유가 있으실까요?
없다면 그냥 항상 쓰던 것처럼 쓰는 게, 일관성 있지 않을까?? 라는 생각이 들어서 여쭤봅니다! : )

```suggestion
        guidanceLabel.snp.makeConstraints {
            $0.top.equalTo(view.safeAreaLayoutGuide).offset(12)
```

2023-01-25 00:46 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            $0.bottom.equalToSuperview()
Q: 바텀에는 safearea가 안 들어가는 이유가 있을까요??!

2023-01-25 00:46 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    }
p3;
여기서 images.remove가 reloadData보다 위에 있어야 하지 않나?? 라는 생각이 듭니다!
혹시나 이미 reloadData가 된 이후, image.remove가 일어난다면, 사진이 삭제되지 않을 것 같아서 그럽니다!

2023-01-25 00:46 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        }
p3; 
현재 else 문을 보면, 이미지를 넣어주고, 그다음 if문을 다시 돌려서 images.count가 5개 밑이면 다시 emptyImage를 넣어주고, 다시 cell을 reload하는 것 같습니다. 만약 다시 reload되면 이미지를 넣어준 것이 필요없는 작업이 될 것 같습니다.

추가적으로 이미지 카운트 개수에 따라서, images를 변화시키고 있는데, 여기서 isChangedConfigure 까지 한 번에 변화시키면 더 깔끔하지 않을까?라는 생각이 듭니다. 

if (이미지 카운트가 6개일 때) {
 ...
 isChangedConfigure = false
 reload
} else if (이미지 카운트가 6개보다 작고, empty이미지가 없을 때) {
 ...
 reload
} else { 
 (셀에 이미지 입히기)
}

이런 식으로 하면 조금 더 효율적으로 돌아가지 않을까? 라는 생각이 듭니다!

+Q: images.count == 6 라는 조건만 있어도 될 것 같은데, && (images[0] == emptyImage) 까지 추가하신 이유가 있을까요??!

2023-01-25 00:46 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +                    self.didTapDeleteAction()
p5;
self.didTapDeleteAction() 이후에 isChangedConfigure = true 를 해주면 좋지 않을까? 라는 생각이 듭니다. 
```suggestion
                    self.didTapDeleteAction()
                    isChangedConfigure = true
```

2023-01-25 00:46 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        pickerConfiguration.selection = .default
Q: isChangedConfigure = false 를 해주는 이유가 있을까요?? 사진 변경만 하는 함수라면, 사진이 삭제되거나 추가되는 경우가 아니어서, 바뀔 이유가 없을 것 같아서요!

2023-01-25 00:46 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            isChangedConfigure = true
Q: isChangedConfigure = true가 여기에 꼭 필요할까요??!

2023-01-25 07:42 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            $0.bottom.equalToSuperview()
> Q: 바텀에는 safearea가 안 들어가는 이유가 있을까요??!

해당 뷰를 기와집과 동일하게 만들었을때, 앱을 실행하면 safeArea구역까지 버튼으로 채워져있어야하기에 safeArea를 제거하였습니다.

2023-01-25 07:55 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        pickerConfiguration.selection = .default
> Q: isChangedConfigure = false 를 해주는 이유가 있을까요?? 사진 변경만 하는 함수라면, 사진이 삭제되거나 추가되는 경우가 아니어서, 바뀔 이유가 없을 것 같아서요!

PHPViewControllerDelegate extension에서 isChangedConfigure를 이용해 사진을 추가 / 수정을 구분하고 있습니다.
```swift
self.images.insert(image, at: self.isChangedCondition ? self.selectedIndex + 1 : self.selectedIndex)
```

2023-01-25 08:06 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +                    self.didTapDeleteAction()
> p5; self.didTapDeleteAction() 이후에 isChangedConfigure = true 를 해주면 좋지 않을까? 라는 생각이 듭니다.

그렇게 하게 되면, ActionSheet를 띄움과 동시에 isChangedConfigure가 True로 바뀌어, 이미지가 반영되는 위치에서 문제가 생겨 기존 코드로 유지하였습니다.

2023-01-25 08:08 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            isChangedConfigure = true
> Q: isChangedConfigure = true가 여기에 꼭 필요할까요??!

최상단 빈이미지를 클릭했을 때, 조건을 다시 변경해줘야하므로 필요할 것 같습니다.
if문 밖으로 빼도 괜찮지만, 사용되지 않을 코드를 밖에서 사용하고 if문을 돌리는 것보다, 처음부터 사용하지 않도록 if문 안에 있는 게 낫지 않을까요?

2023-01-25 08:29 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        }
> p3; 현재 else 문을 보면, 이미지를 넣어주고, 그다음 if문을 다시 돌려서 images.count가 5개 밑이면 다시 emptyImage를 넣어주고, 다시 cell을 reload하는 것 같습니다. 만약 다시 reload되면 이미지를 넣어준 것이 필요없는 작업이 될 것 같습니다.
- 디너의 조언으로 코드가 더 깔끔해졌네요! 감사합니다

> 추가적으로 이미지 카운트 개수에 따라서, images를 변화시키고 있는데, 여기서 isChangedConfigure 까지 한 번에 변화시키면 더 깔끔하지 않을까?라는 생각이 듭니다.
- Configure조건은 Cell을 클릭할 때 변경하는 것이 코드 해석에서 더 자연스러울 것 같아 변경하지 않았습니다.

> +Q: images.count == 6 라는 조건만 있어도 될 것 같은데, && (images[0] == emptyImage) 까지 추가하신 이유가 있을까요??!
- 작업 간 버그때문에 만들었던 코드였는데, 지금은 문제가 없어서 지워도 될 것 같습니다. 확인 감사합니다.

5aaaddb

2023-01-25 08:30 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    }
> p3;
> 여기서 images.remove가 reloadData보다 위에 있어야 하지 않나?? 라는 생각이 듭니다!
> 혹시나 이미 reloadData가 된 이후, image.remove가 일어난다면, 사진이 삭제되지 않을 것 같아서 그럽니다!

d68e9c5

2023-01-25 08:36 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            self.images.remove(at: self.selectedIndex)
> p1; 사진 삭제 기능 사용시, 해당 부분에서 문제 발생합니다. 리로드 후에 사진을 삭제해서 발생하는 문제로, 두 코드의 순서가 바뀌어야할 것 같네요.
> 
> 추가로, 사진 변경쪽에도 문제가 있는 것 같습니다. 문제가 발생한 영상을 녹화했는데, 영상 용량 문제로 깃허브에 첨부할 수 없어서 개인 메신저로 보냈습니다.

d68e9c5
1. 재확인해도 사진 삭제관련 에러는 발견되지 않았으나, 코드의미상 더 적합하다 생각해 수정하였습니다.
2. 보라색 꽃을 추가할 때 발생하는 에러는 시뮬레이터 버그로, 실제 기기에서는 발생하지 않는 문제입니다.
<img width="1164" alt="스크린샷 2023-01-25 오후 5 35 46" src="https://user-images.githubusercontent.com/98405970/214516240-e5ad64b3-ee6a-4c33-94ee-8cb56e346a53.png">

[출처 - HEIC사진 클릭 시 에러](https://developer.apple.com/forums/thread/699155)

2023-01-25 10:02 UTC, creohwan reviewed
전체적으로 코드가 많이 깔끔해진 것 같습니다! 클라쪽에서 제가 짠 거는... 부끄럽군요 ㅋㅋ

+ isChangedCondition 변수명이 살짝 헷갈리는 것 같습니다! true이면 추가이고, false이면 변경인데... 뭔가 isChangedCondition true가 추가의 느낌 보다는 변경한다는 느낌이 드는 것 같아요! 더 좋은 변수명이 없을까요?? ex) true이면 사진이 추가되고, false이면 사진이 변경된다는 느낌의 변수명... 제가 좀 더 고민해보겠습니다 : )

2023-01-25 10:02 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            nextButton.isEnabled.toggle()
p1; 
토글로 되어 있으면, 사진을 1개씩 추가할 때마다, isEnabled이 변경되어서, 가능 불가능 가능 불가능 이렇게 바뀌는 것 같습니다!!

2023-01-25 10:02 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        images.remove(at: selectedIndex)
p1; 
현재는 showPHPicker()가 실행되고(갤러리가 올라오고), 바로 images.remove가 되는 구조입니다. 그런데 만약 변경하기 싫어서 cancel을 눌러버리면, 실제로 변경하지 않았지만, 해당 이미지가 배열에서 삭제되는 문제가 생깁니다!

cancel 했을 때 클라쪽에서 보이진 않지만... 실제 이미지 배열에서는 바로 삭제되더라고요!. reloade해주지 않아서 클라쪽에선 그대로 보이는 것 같아요~ 하지만 이것을 서버로 전송하는 것을 생각했을 때는 수정이 필요해보입니다!!

2023-01-25 10:02 UTC, creohwan commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +                    self.didTapDeleteAction()
> > p5; self.didTapDeleteAction() 이후에 isChangedConfigure = true 를 해주면 좋지 않을까? 라는 생각이 듭니다.
> 
> 그렇게 하게 되면, ActionSheet를 띄움과 동시에 isChangedConfigure가 True로 바뀌고, 이미지가 반영되는 위치에서 문제가 생겨 기존 코드로 유지하였습니다.

으악! 이건 제가 잘못생각한 것 같네요!

++ 여담이지만 제가 확인해본 결과, { delete in ~} 에서 뒤쪽에 있는 구문들은, 액션시트가 올라오고 해당 delete를 클릭하면 실행됩니다!!

2023-01-25 14:25 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        images.remove(at: selectedIndex)
> p1; 현재는 showPHPicker()가 실행되고(갤러리가 올라오고), 바로 images.remove가 되는 구조입니다. 그런데 만약 변경하기 싫어서 cancel을 눌러버리면, 실제로 변경하지 않았지만, 해당 이미지가 배열에서 삭제되는 문제가 생깁니다!
> 
> cancel 했을 때 클라쪽에서 보이진 않지만... 실제 이미지 배열에서는 바로 삭제되더라고요!. reloade해주지 않아서 클라쪽에선 그대로 보이는 것 같아요~ 하지만 이것을 서버로 전송하는 것을 생각했을 때는 수정이 필요해보입니다!!

a9fb295
굿! 저도 방금 발견해서 급히 수정했습니다. 자세히 확인해주셔서 감사합니다~

2023-01-25 14:25 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            nextButton.isEnabled.toggle()
> p1;
> 토글로 되어 있으면, 사진을 1개씩 추가할 때마다, isEnabled이 변경되어서, 가능 불가능 가능 불가능 이렇게 바뀌는 것 같습니다!!

0114502 
왜 자꾸 글자색이 바뀌지 했는데 그거였군요. 감사합니다~

2023-01-25 14:52 UTC, JUNY0110 commented
> 전체적으로 코드가 많이 깔끔해진 것 같습니다! 업자용에서 제가 짠 거는... 부끄럽군요 ㅋㅋ
> 
> * isChangedCondition 변수명이 살짝 헷갈리는 것 같습니다! true이면 추가이고, false이면 변경인데... 뭔가 isChangedCondition true가 추가의 느낌 보다는 변경한다는 느낌이 드는 것 같아요! 더 좋은 변수명이 없을까요?? ex) true이면 사진이 추가되고, false이면 사진이 변경된다는 느낌의 변수명... 제가 좀 더 고민해보겠습니다 : )
> 
> 고생하셨습니다 =D

59dea26
isChangedPHPickerRole로 수정했는데, 이런 변수는 어떨까요?

2023-01-25 14:56 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
>              $0.top.equalTo(view.safeAreaLayoutGuide.snp.top).offset(12)
> p3; view.safeAreaLayoutGuide.snp.top 까지 붙이신 특별한 이유가 있으실까요? 없다면 그냥 항상 쓰던 것처럼 쓰는 게, 일관성 있지 않을까?? 라는 생각이 들어서 여쭤봅니다! : )

3a14d7b
저는 .snp.top 등을 작성하는게 더 명확하고 자세한 코드가 아닐까 라고 생각했는데, 제거해도 해석이 모호해지지 않는 것 같네요 :)

2023-01-26 04:35 UTC, taek0622 requested changes
고생하셨습니다.
해당 PR에서 정말 많은 수정사항이 있었네요. 코드를 처음부터 다시보는데 새로운 코드를 보고있는 것 같아요.
너무 고생 많으셨고, 수정이 필요한 부분에 리뷰 남겼습니다. 확인 부탁드려요~

2023-01-26 04:35 UTC, ikanic commented on GiwazipClient/Extensions+/Alert+.swift
> +                         secondContext: String? = nil,
p1;
firstContext와 secondContext는 nil을 허용하면 안될 것 같습니다. 저 부분이 nil인 경우 어플이 튕기는 현상이 발생해요.
혹은 기본 값을 다른 것으로 줘야할 것 같습니다.

2023-01-26 04:35 UTC, ikanic commented on GiwazipClient/Extensions+/Alert+.swift
> +                         completion: (() -> Void)? = nil) {
p1;
해당 함수에서는 Completion이 사용되고 있지 않은데, 파라미터로 completion이 있네요.
사용하지 않을 파라미터라면 삭제 되어야할 것 같습니다.

2023-01-26 04:35 UTC, ikanic commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var uiButtonConfiguration = UIButton.Configuration.plain()
p5;
변수 이름이 너무 길어서 그런데 혹시 `buttonConfiguration`은 어떨까요? 큰 차이가 없긴 하지만, 조금이라도 변수 이름 길이를 줄이는게 좋을 것 같아요. 지금은 너무 길어서 읽기 어렵네요.

또한, plain을 filled로 바꿔도 `$0.configuration?.background.cornerRadius` 속성으로 코너를 변경할 수 있어서, filled로 설정해도 될 것 같습니다.

2023-01-26 04:35 UTC, ikanic commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        collectionView.contentInset.bottom = 80
p5;
여기는 습관처럼 컬렉션 뷰 위 레이어에 버튼을 주면서 이렇게 contentInset을 잡게 된 것 같은데, 현재 뷰는 히스토리 뷰처럼 컬렉션 뷰가 뷰의 세이프에리어 아래까지 올 필요가 없으므로, 컬렉션 뷰와 버튼의 constraint를 조정하는 것이 더 좋을 것 같습니다.
그렇게 하면 컬렉션 뷰의 contentInset을 잡을 필요가 없어질 것 같네요.

2023-01-26 04:35 UTC, ikanic commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        pickerConfiguration.selection = .default
p5;
지금은 변경할 사진을 누르자마자 선택이 되고 시트가 내려가게 되는데, 어떤 것이 선택되었는지 한번 확인한 후에 버튼 클릭으로 변경하는 것이 더 좋지 않을까요?

2023-01-26 04:35 UTC, ikanic commented on GiwazipClient/Views/PostingPhotoViewController.swift
>  extension PostingPhotoViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
p2;
UICollectionViewDelegate는 삭제해도 될 것 같습니다.
이미 UICollectionViewDelegateFlowLayout이 UICollectionViewDelegate를 상속받고 있는 것으로 알고 있어요.

2023-01-26 04:35 UTC, ikanic commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        }
p5;
지금 cell이 return되기 전에 collectionView가 리로드되고 있는데, 약간 로직이 이상한 것 같습니다.
셀에 새로운 내용이 반영된 다음에 리로드가 되야할 것 같은데, 조금 애매하네요.
나중에 뷰모델로 나누면서 바뀌면 좋을 것 같네요.

2023-01-26 10:10 UTC, JUNY0110 commented on GiwazipClient/Extensions+/Alert+.swift
> +                         completion: (() -> Void)? = nil) {
> p1;
> 해당 함수에서는 Completion이 사용되고 있지 않은데, 파라미터로 completion이 있네요.
> 사용하지 않을 파라미터라면 삭제 되어야할 것 같습니다.

9c6a232 반영했습니다. 
추가로 ActionSheet는 타이틀에 기본값이 있으면 기존 UI와 달라져 nil처리했습니다.

2023-01-26 10:10 UTC, JUNY0110 commented on GiwazipClient/Extensions+/Alert+.swift
> +                         secondContext: String? = nil,
> p1;
> firstContext와 secondContext는 nil을 허용하면 안될 것 같습니다. 저 부분이 nil인 경우 어플이 튕기는 현상이 발생해요.
> 혹은 기본 값을 다른 것으로 줘야할 것 같습니다.

9c6a232

2023-01-26 10:11 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var uiButtonConfiguration = UIButton.Configuration.plain()
> p5; 변수 이름이 너무 길어서 그런데 혹시 `buttonConfiguration`은 어떨까요? 큰 차이가 없긴 하지만, 조금이라도 변수 이름 길이를 줄이는게 좋을 것 같아요. 지금은 너무 길어서 읽기 어렵네요.
> 
> 또한, plain을 filled로 바꿔도 `$0.configuration?.background.cornerRadius` 속성으로 코너를 변경할 수 있어서, filled로 설정해도 될 것 같습니다.

59c9d01 반영~

2023-01-26 10:13 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        collectionView.contentInset.bottom = 80
> p5;
> 여기는 습관처럼 컬렉션 뷰 위 레이어에 버튼을 주면서 이렇게 contentInset을 잡게 된 것 같은데, 현재 뷰는 히스토리 뷰처럼 컬렉션 뷰가 뷰의 세이프에리어 아래까지 올 필요가 없으므로, 컬렉션 뷰와 버튼의 constraint를 조정하는 것이 더 좋을 것 같습니다.
> 그렇게 하면 컬렉션 뷰의 contentInset을 잡을 필요가 없어질 것 같네요.

7b73303 굿굿
다만 contentInset을 없애면 버튼과 Cell이 딱 붙게 되어, 20은 남겨두었습니다.

2023-01-26 10:14 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        pickerConfiguration.selection = .default
> p5;
> 지금은 변경할 사진을 누르자마자 선택이 되고 시트가 내려가게 되는데, 어떤 것이 선택되었는지 한번 확인한 후에 버튼 클릭으로 변경하는 것이 더 좋지 않을까요?

이건 현실적으로 어려울 것 같네요 ㅠ
PHPicker에서 지원하지 않는 것 같습니다.

2023-01-26 10:14 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
>  extension PostingPhotoViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
> p2;
> UICollectionViewDelegate는 삭제해도 될 것 같습니다.
> 이미 UICollectionViewDelegateFlowLayout이 UICollectionViewDelegate를 상속받고 있는 것으로 알고 있어요.

f0eed13 반영했습니다~

2023-01-26 12:04 UTC, taek0622 requested changes
수정에 대해 재 리뷰를 요청하셔서 확인하려했으나, 시작부터 레이아웃이 틀어지고, 사진 클릭도 되지 않는 탓에 기능을 제대로 확인해 볼 수 없네요.
제가 따온 브랜치가 시점이 안맞았나 싶어서 Pull도 받아보고, 그래도 안되서 브랜치를 로컬에서 아예 삭제한 뒤 다시 받아도 같은 문제가 발생합니다. 수정 후 재요청 부탁드립니다.
추가로 올리시기 전에 제대로 되는게 맞는지 테스트 한번 부탁드려요 :)

아래에 현재 상황 사진 첨부합니다.
<img src="https://user-images.githubusercontent.com/81027256/214830801-feffad8a-9831-486a-872c-71dc2195af74.png" width="300">

2023-01-26 12:14 UTC, JUNY0110 commented
> 

eb0f020 상상도 못한 정체 ㄴㅇㄱ
![image](https://user-images.githubusercontent.com/98405970/214832814-11448367-1365-41e2-a24f-4a9e4423fa5d.png)

2023-01-26 12:17 UTC, taek0622 commented
> > 
> 
> [eb0f020](https://github.com/Samsamhada/Giwazip-Client-App/commit/eb0f020cadca5b23382b1e7378b3517a246b5f84) 해결완료~ 상상도 못한 정체 ㄴㅇㄱ ![image](https://user-images.githubusercontent.com/98405970/214832814-11448367-1365-41e2-a24f-4a9e4423fa5d.png)

확인했습니다.

2023-01-26 12:18 UTC, taek0622 commented on GiwazipClient/Extensions+/Alert+.swift
> +                         secondContext: String? = nil,
> > p1;
> > firstContext와 secondContext는 nil을 허용하면 안될 것 같습니다. 저 부분이 nil인 경우 어플이 튕기는 현상이 발생해요.
> > 혹은 기본 값을 다른 것으로 줘야할 것 같습니다.
> 
> [9c6a232](https://github.com/Samsamhada/Giwazip-Client-App/commit/9c6a232cf75e9565ba5f480f80b442a8a34c23e5)

확인했습니다. 리뷰 리졸브합니다.

2023-01-26 12:20 UTC, ikanic commented on GiwazipClient/Extensions+/Alert+.swift
> +                         completion: (() -> Void)? = nil) {
> > p1;
> > 해당 함수에서는 Completion이 사용되고 있지 않은데, 파라미터로 completion이 있네요.
> > 사용하지 않을 파라미터라면 삭제 되어야할 것 같습니다.
> 
> [9c6a232](https://github.com/Samsamhada/Giwazip-Client-App/commit/9c6a232cf75e9565ba5f480f80b442a8a34c23e5) 반영했습니다. 추가로 ActionSheet는 타이틀에 기본값이 있으면 기존 UI와 달라져 nil처리했습니다.

확인했습니다. 리뷰 리졸브합니다~

2023-01-26 12:21 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +    private var uiButtonConfiguration = UIButton.Configuration.plain()
> > p5; 변수 이름이 너무 길어서 그런데 혹시 `buttonConfiguration`은 어떨까요? 큰 차이가 없긴 하지만, 조금이라도 변수 이름 길이를 줄이는게 좋을 것 같아요. 지금은 너무 길어서 읽기 어렵네요.
> > 또한, plain을 filled로 바꿔도 `$0.configuration?.background.cornerRadius` 속성으로 코너를 변경할 수 있어서, filled로 설정해도 될 것 같습니다.
> 
> [59c9d01](https://github.com/Samsamhada/Giwazip-Client-App/commit/59c9d013b61ccb88c1b924fc0f02ecb99dadaf29) 변수명 반영 [7b73303](https://github.com/Samsamhada/Giwazip-Client-App/commit/7b73303f45b0bac6818bf9552044c2b7731bb452) configuration수정했습니다. 추후 버전 15이하도 지원할 계획이 있다면, iOS15미만 버전에서도 적용될 수 있도록 추가 코드를 작성해봄이 어떤지 내일 회의에 반영하고 싶네요~

확인했습니다.
버전에 대해서는 회의에서 같이 이야기 해봐요. 굳~ :)

2023-01-26 12:22 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        collectionView.contentInset.bottom = 80
> > p5;
> > 여기는 습관처럼 컬렉션 뷰 위 레이어에 버튼을 주면서 이렇게 contentInset을 잡게 된 것 같은데, 현재 뷰는 히스토리 뷰처럼 컬렉션 뷰가 뷰의 세이프에리어 아래까지 올 필요가 없으므로, 컬렉션 뷰와 버튼의 constraint를 조정하는 것이 더 좋을 것 같습니다.
> > 그렇게 하면 컬렉션 뷰의 contentInset을 잡을 필요가 없어질 것 같네요.
> 
> [7b73303](https://github.com/Samsamhada/Giwazip-Client-App/commit/7b73303f45b0bac6818bf9552044c2b7731bb452) 굿굿 다만 contentInset을 없애면 버튼과 Cell이 딱 붙게 되어, 20은 남겨두었습니다.

확인했습니다. 리뷰 리졸브합니다~

2023-01-26 12:22 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        pickerConfiguration.selection = .default
> 

확인했습니다. 저도 찾아본 결과 여러가지 이유로 `PHPicker`에서 직접 구현이 어려운 것 같아서 반영되지 못하는게 맞는 것 같네요.

2023-01-26 12:27 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
>  extension PostingPhotoViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
> > p2;
> > UICollectionViewDelegate는 삭제해도 될 것 같습니다.
> > 이미 UICollectionViewDelegateFlowLayout이 UICollectionViewDelegate를 상속받고 있는 것으로 알고 있어요.
> 
> [f0eed13](https://github.com/Samsamhada/Giwazip-Client-App/commit/f0eed13011fa5e81c9a919aba7a490e34b241d01) 반영했습니다~

확인했습니다. 리뷰 리졸브합니다.

2023-01-26 12:44 UTC, taek0622 approved these changes
고생하셨습니다.
많은 수정이 있었는데, 거의 다 고치신 것 같네요. 남은 부분 몇개는 다음 PR에서 변경하기로 결정 되었구요.
약간 수정이 필요할 수 있을 것 같은 곳에 제안 하나, 또 코멘트 몇 개 남겼습니다. 확인해주시면 감사하겠습니다.
고생 많으셨습니다~ :)

2023-01-26 12:44 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            nextButton.isEnabled = (images.count) > 1 ? true : false
p4;
didSet 부분이 훨씬 간결하고 깔끔해져서 좋네요.
그런데, 괄호 부분이 약간 이상한 것 같습니다.
뭔가 `images.count > 1`이라는 조건을 구분하기 위해 `(images.count > 1)`과 같이 묶은게 아니라, 굳이 `images.count`만 묶여야 할 이유가 있을까요?

2023-01-26 12:44 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        $0.configuration?.contentInsets.bottom = 20
조금 더 UIButton의 Configuration에 대해 잘 사용할 수 있게 된 것 같아요.
에디가 Configuration을 사용해 주신 덕에, 많이 찾아보고 공부하면서 생각하고, 또 배워갈 수 있었던 것 같습니다. 굳~ :)

2023-01-26 12:44 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +        pickerConfiguration.filter = .any(of: [.images, .not(.livePhotos)])
이번에 PHPicker에 대해서도 쭉 한번 살펴보고 제대로 공부할 수 있는 좋은 기회가 되었던 것 같습니다.
그동안에도 계속 사용하던 기술이라 제대로 찾아볼 생각을 못하고 있었는데, 이번에 피커에 대해서 좀 더 집중적으로 파보면서 공부할 수 있는 좋은 기회였던 것 같아요. 아주 좋습니다. 굳~ :)

2023-01-26 12:59 UTC, JUNY0110 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            nextButton.isEnabled = (images.count) > 1 ? true : false
> p4;
> didSet 부분이 훨씬 간결하고 깔끔해져서 좋네요.
> 그런데, 괄호 부분이 약간 이상한 것 같습니다.
> 뭔가 `images.count > 1`이라는 조건을 구분하기 위해 `(images.count > 1)`과 같이 묶은게 아니라, 굳이 `images.count`만 묶여야 할 이유가 있을까요?

edfea0a

2023-01-26 13:00 UTC, merged

2023-01-26 13:01 UTC, taek0622 commented on GiwazipClient/Views/PostingPhotoViewController.swift
> +            nextButton.isEnabled = (images.count) > 1 ? true : false
> > p4;
> > didSet 부분이 훨씬 간결하고 깔끔해져서 좋네요.
> > 그런데, 괄호 부분이 약간 이상한 것 같습니다.
> > 뭔가 `images.count > 1`이라는 조건을 구분하기 위해 `(images.count > 1)`과 같이 묶은게 아니라, 굳이 `images.count`만 묶여야 할 이유가 있을까요?
> 
> [edfea0a](https://github.com/Samsamhada/Giwazip-Client-App/commit/edfea0a2d71c63277328a5be319ca2849524cc16)

확인했습니다. 리뷰 리졸브합니다.