[Feature] 사진 확대 축소 제스쳐 기능 추가
Samsamhada/Giwazip-Client-App pull request #26
Opened 2023-01-25 16:07 UTC by creohwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
-  사진 확대 축소 제스쳐 기능 추가

## Key Changes 🔥 (주요 구현/변경 사항)
-  사진 확대 축소 제스쳐 기능 추가

## ToDo 📆 (남은 작업)

## ScreenShot 📷 (참고 사진)
https://user-images.githubusercontent.com/92836045/214614303-a8567b06-1a64-483c-ab7b-6b13f0f0c039.mp4

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 구현하긴 했습니다!! 추가적으로 구현해야할 게 있으면 말씀해주세요!

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #19

2023-01-25 16:42 UTC, taek0622 requested changes
고생하셨습니다.
스크롤 뷰로 핀치를 적용한 부분 코드가 상당히 복잡하면서도 재밌네요.
업자용 앱 개발 때보다도 코드 실력이 많이 늘었다는 게 눈에 확 보이네요.
코드에서 약간의 수정이 필요한 부분과, 질문 남겼습니다. 확인 부탁드려요~

2023-01-25 16:42 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +    // MARK: - Property
p3;
`MARK: -`는 위 아래로 한 줄씩 띄우는  컨벤션이 있습니다~

2023-01-25 16:42 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +    var postImage: UIImageView = {
p2;
사진을 불러오는 부분이므로 lazy var로 선언되는 것이 더 나을 것 같습니다.
또한, 만약 외부에서 접근할 일이 없다면 private이 필요할 것 같네요.

2023-01-25 16:42 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +        let pinch = UIPinchGestureRecognizer(target: self, action: #selector(controlPinch))
p1;
위에서 pinch가 이미 선언되어 있습니다. 해당 부분을 위의 pinch의 내용에 반영하는 것이 좋을 것 같네요.

2023-01-25 16:42 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +    private func setupPintch() {
p3;
여기는 `setupPinch`가 오타가 난 것 같네요.

2023-01-25 16:42 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +class PostImageView: BaseViewController, UIGestureRecognizerDelegate {
p1;
UIGestureRecognizerDelegate가 사용되지 않고 있는 것 같습니다.

2023-01-25 16:42 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +     }
Question;
이 함수의 역할이 정확히 무엇을 하는 것일까요?

p3;
return 부터 } 까지의 인덴트가 이상합니다.

2023-01-25 16:42 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +            let top = 0.5 * (newHeight * scrollView.zoomScale > zoomView.frame.height ? (newHeight - zoomView.frame.height) : (scrollView.frame.height - scrollView.contentSize.height))
p5;
코드 리딩에 약간의 혼란이 있어서, 아래처럼 한번 더 괄호로 묶어주시는 건 어떨까요?
```suggestion
            let left = 0.5 * ((newWidth * scrollView.zoomScale > zoomView.frame.width) ?
                              (newWidth - zoomView.frame.width) : (scrollView.frame.width - scrollView.contentSize.width))
            let top = 0.5 * ((newHeight * scrollView.zoomScale > zoomView.frame.height) ? (newHeight - zoomView.frame.height) : (scrollView.frame.height - scrollView.contentSize.height))
```

2023-01-26 01:36 UTC, taek0622 commented
p2;
추가로 현재 pinch가 없어도 전부 정상작동하는 걸로 보아, pinch 부분이 전혀 사용이 안되고 있는 것 같네요.
기본 스크롤뷰의 기능으로 사용되고 있는 것 같아요.

2023-01-26 03:17 UTC, JUNY0110 requested changes
고생하셨습니다~ 업자용 작성할 때 해결하기 어려웠었는데 이렇게 해결할 수 있었네요!

2023-01-26 03:17 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageView.swift
> +    private let scrollView = UIScrollView()
p1.
View에 속해있어야할 것 같습니다~

2023-01-26 03:17 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageView.swift
> +        scrollView.showsHorizontalScrollIndicator = false
```suggestion
    private let scrollView: UIScrollView = {
        $0.zoomScale = 1.0
        $0.minimumZoomScale = 1.0
        $0.maximumZoomScale = 3.0
        $0.contentInsetAdjustmentBehavior = .never
        $0.showsVerticalScrollIndicator = false
        $0.showsHorizontalScrollIndicator = false
        return $0
    }(UIScrollView())
```
이런식으로도 가능할 것 같습니다~

2023-01-26 03:17 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageView.swift
> +        scrollView.delegate = self
p5.
다른 scrollView 속성을 scrollView로 빼게되면,
scrollView.frame은 layout
scrollView.delegate는 attribute로 빠질 수 있을 것 같네요!
그러면 함수를 따로 빼지 않아도 될 것 같아요

scrollView.frame을 view.bounds에 맞추면 이미지틀을 잡는 게 쉽게 해결될 수 있는 문제였네요. 굿굿

2023-01-26 03:17 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageView.swift
> +    }
p5. 
postImage도 layout과 attribute로 분리하면 함수를 사용하지 않아도 될 것 같습니다.

2023-01-26 03:17 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageView.swift
> +
Q.
pinchGesture가 없어도 동작이 동일한데, 사용한 이유가 있을까요?

2023-01-27 11:30 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +    // MARK: - Property
> p3; `MARK: -`는 위 아래로 한 줄씩 띄우는 컨벤션이 있습니다~

0a3fab7 으악! 반영했습니다~

2023-01-27 11:30 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +    var postImage: UIImageView = {
> p2; 사진을 불러오는 부분이므로 lazy var로 선언되는 것이 더 나을 것 같습니다. 또한, 만약 외부에서 접근할 일이 없다면 private이 필요할 것 같네요.

0a3fab7 반영했습니다~

2023-01-27 11:31 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +    private func setupPintch() {
> p3; 여기는 `setupPinch`가 오타가 난 것 같네요.

0a3fab7 반영했습니다~

2023-01-27 11:31 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +class PostImageView: BaseViewController, UIGestureRecognizerDelegate {
> p1; UIGestureRecognizerDelegate가 사용되지 않고 있는 것 같습니다. 그리고 파일 이름과 클래스 이름이 `PostImageView`로 끝나고 있는데, `ViewController`로 끝나야할 것 같습니다.

0a3fab7 반영했습니다~

2023-01-27 11:31 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +    private let scrollView = UIScrollView()
> p1. View에 속해있어야할 것 같습니다~

0a3fab7 반영했습니다~

2023-01-27 11:35 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +        let pinch = UIPinchGestureRecognizer(target: self, action: #selector(controlPinch))
> p1; 위에서 pinch가 이미 선언되어 있습니다. 해당 부분을 위의 pinch의 내용에 반영하는 것이 좋을 것 같네요.
> 
> 추가로 전체적으로 pinch가 전혀 사용되고 있지 않은 것 같아요. pinch 부분을 제외해도 정상 작동 하고 있습니다. 아마 스크롤뷰의 기본 핀치로 작동이 되고 있는 것 같아요. 별도의 Pinch 부분을 삭제해도 될 것 같습니다.

67008df 반영했습니다~ 이것저것 시도하다가, 완성되자마자 기뻐서, 그냥 풀리쾌 올렸던 것 같습니다 ㅋㅋ 덕분에 더 깔끔해졌어요!

2023-01-27 11:42 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +        scrollView.showsHorizontalScrollIndicator = false
> 이런식으로도 가능할 것 같습니다~

f3938f8 오~ 감사합니다~!

2023-01-27 11:43 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +            let top = 0.5 * (newHeight * scrollView.zoomScale > zoomView.frame.height ? (newHeight - zoomView.frame.height) : (scrollView.frame.height - scrollView.contentSize.height))
> p5; 코드 리딩에 약간의 혼란이 있어서, 아래처럼 한번 더 괄호로 묶어주시는 건 어떨까요?
> 
> 추가로 ScrollViewDidZoom 함수의 실행 과정을 한번 설명해주시면 좋을 것 같습니다. 코드 리딩으로 파악한다고 파악하긴 했지만, 대략적인 예측이고 정확한 동작은 코드 작성자 분이 더 잘 알 것 같아서요.

333cd3b 반영했습니다~!

2023-01-27 12:02 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +    // MARK: - Property
> > p3; `MARK: -`는 위 아래로 한 줄씩 띄우는 컨벤션이 있습니다~
> 
> [0a3fab7](https://github.com/Samsamhada/Giwazip-Client-App/commit/0a3fab74001a3c67114a82f050f8159350cb4935) 으악! 반영했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-01-27 12:03 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +    var postImage: UIImageView = {
> > p2; 사진을 불러오는 부분이므로 lazy var로 선언되는 것이 더 나을 것 같습니다. 또한, 만약 외부에서 접근할 일이 없다면 private이 필요할 것 같네요.
> 
> [0a3fab7](https://github.com/Samsamhada/Giwazip-Client-App/commit/0a3fab74001a3c67114a82f050f8159350cb4935) 반영했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-01-27 12:04 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +        let pinch = UIPinchGestureRecognizer(target: self, action: #selector(controlPinch))
> > p1; 위에서 pinch가 이미 선언되어 있습니다. 해당 부분을 위의 pinch의 내용에 반영하는 것이 좋을 것 같네요.
> > 추가로 전체적으로 pinch가 전혀 사용되고 있지 않은 것 같아요. pinch 부분을 제외해도 정상 작동 하고 있습니다. 아마 스크롤뷰의 기본 핀치로 작동이 되고 있는 것 같아요. 별도의 Pinch 부분을 삭제해도 될 것 같습니다.
> 
> [67008df](https://github.com/Samsamhada/Giwazip-Client-App/commit/67008dfebf4ee21152cb204f03e05ba3ce0eb1af) 반영했습니다~ 이것저것 시도하다가, 완성되자마자 기뻐서, 그냥 풀리쾌 올렸던 것 같습니다 ㅋㅋ 덕분에 더 깔끔해졌어요!
> 
> 여러 함수로 뺀 이유는, 선언부분과, 역할부분을 명확히 나누는 게 어쩌면 더 가독성이 좋을 것 같아서, 시도해보긴 했었습니다~

확인했습니다~

2023-01-27 12:05 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +    private func setupPintch() {
> > p3; 여기는 `setupPinch`가 오타가 난 것 같네요.
> 
> [0a3fab7](https://github.com/Samsamhada/Giwazip-Client-App/commit/0a3fab74001a3c67114a82f050f8159350cb4935) 반영했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-01-27 12:05 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +class PostImageView: BaseViewController, UIGestureRecognizerDelegate {
> > p1; UIGestureRecognizerDelegate가 사용되지 않고 있는 것 같습니다. 그리고 파일 이름과 클래스 이름이 `PostImageView`로 끝나고 있는데, `ViewController`로 끝나야할 것 같습니다.
> 
> [0a3fab7](https://github.com/Samsamhada/Giwazip-Client-App/commit/0a3fab74001a3c67114a82f050f8159350cb4935) 반영했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-01-27 12:06 UTC, taek0622 commented on GiwazipClient/Views/PostImageView.swift
> +            let top = 0.5 * (newHeight * scrollView.zoomScale > zoomView.frame.height ? (newHeight - zoomView.frame.height) : (scrollView.frame.height - scrollView.contentSize.height))
> > p5; 코드 리딩에 약간의 혼란이 있어서, 아래처럼 한번 더 괄호로 묶어주시는 건 어떨까요?
> > 추가로 ScrollViewDidZoom 함수의 실행 과정을 한번 설명해주시면 좋을 것 같습니다. 코드 리딩으로 파악한다고 파악하긴 했지만, 대략적인 예측이고 정확한 동작은 코드 작성자 분이 더 잘 알 것 같아서요.
> 
> [333cd3b](https://github.com/Samsamhada/Giwazip-Client-App/commit/333cd3b7ef8f80711c8eb7706b20dffc85f39d13) 반영했습니다~!

확인했습니다. 리뷰 리졸브합니다~

2023-01-27 12:09 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +
> Q. pinchGesture가 없어도 동작이 동일한데, 사용한 이유가 있을까요?

5f083ca 핀치 삭제했습니다~! 처음에 핀치로 하다가, 그다음 스크롤뷰로 넘어오면서, 잔재물이 되었습니다! 주의하고 풀리쾌 올리겠습니다~

2023-01-27 13:02 UTC, JUNY0110 approved these changes
코드가 더욱 간결해져서 보기 좋네요! 고생하셨습니다.

2023-01-27 13:02 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageViewController.swift
> +        $0.contentInsetAdjustmentBehavior = .never
scrollView가 navigationBar만큼 inset되는 것을 없애기 위한 코드군요 좋은 메소드인 것 같습니다

2023-01-27 13:02 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageViewController.swift
> +
Q.
현재 사용되지 않는 것 같은데 추후 추가될 내용이 있는걸까요?

2023-01-27 13:02 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageViewController.swift
> +        return self.postImage
p5.
self.를 넣지 않아도 괜찮을 것 같습니다. 이미 extension 내 다른 변수에서도 사용되지 않기도 하구요

2023-01-27 13:03 UTC, creohwan commented on GiwazipClient/Views/PostImageView.swift
> +     }
> Question; 이 함수의 역할이 정확히 무엇을 하는 것일까요?
> 
> p3; return 부터 } 까지의 인덴트가 이상합니다.

스크롤 뷰에서 어떤 뷰를 확대 축소할 것인지를 알려주는 함수입니다! 
코멘트에 자세히 남기겠습니다~!

2023-01-27 13:08 UTC, creohwan commented
전체적으로 코드를 깔끔하게 수정했습니다. 핀치 제스처 스크롤뷰 등 다양한 방법으로 시도하다가, 마지막에 성공해서 기쁜 나머지, 그냥 풀리쾌를 올렸던 것 같습니다.

+ viewForZooming(in:) 에 관하여
이 함수는 스크롤 뷰에서 어떤 뷰를 확대 축소 시킬 것인지를 return 해주는 함수입니다.

ex) 지금은 고양이사진 과 블로그사진 두 개의 뷰를, 스크롤 뷰에 넣었습니다. 그리고 첫번째는 고양이사진을 확대 축소하는 것입니다.
<img width="769" alt="스크린샷 2023-01-27 22 02 07" src="https://user-images.githubusercontent.com/92836045/215093841-d499208b-54c8-4149-9f8d-ba2b182b8c74.png">

https://user-images.githubusercontent.com/92836045/215093959-11b829f2-82e9-45ba-a8fa-556c1cfce868.mp4

ex) 지금은 블로그사진을 확대 축소하는 것입니다.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/92836045/215094345-9c6e86a3-20aa-460c-bb71-da96c08d752e.png">
https://user-images.githubusercontent.com/92836045/215094313-7d77e46f-b717-4437-becb-4cf85385e0b4.mp4





참조 링크 
애플 공식 문서: https://developer.apple.com/documentation/uikit/uiscrollviewdelegate/1619426-viewforzooming
블로그: https://soooprmx.com/swift-uiscrollview/

2023-01-27 13:11 UTC, creohwan commented on GiwazipClient/Views/PostImageViewController.swift
> +
> Q. 현재 사용되지 않는 것 같은데 추후 추가될 내용이 있는걸까요?

730fa2a 삭제했습니다! 감사합니다~!

2023-01-27 13:12 UTC, creohwan commented on GiwazipClient/Views/PostImageViewController.swift
> +        return self.postImage
> p5. self.를 넣지 않아도 괜찮을 것 같습니다. 이미 extension 내 다른 변수에서도 사용되지 않기도 하구요

저도 무의식적으로 self를 쓰긴 했는데 그렇군요!
그렇다면 보통 언제 self 쓰는 경우가 있을까요??!

2023-01-27 14:09 UTC, taek0622 requested changes
고생하셨습니다.
전체적으로 코드가 많이 정돈 되었네요.
수정이 필요해보이는 부분에 리뷰 남겼습니다. 의도치 않은 동작일거라고 판단하여 리뷰 남겼는데, 만약 의도하신 동작이라면 그에 맞게 답변 달아주셔도 좋습니다.

2023-01-27 14:09 UTC, taek0622 commented on GiwazipClient/Views/PostImageViewController.swift
> +    }
p1;
코드가 상당히 짧아져서 저번이랑 동작이 같을 수가 없을 것 같다고 생각했는데, 역시 동작이 같지 않네요.
바뀐 코드의 동작보다 바뀌기 전의 코드 동작이 앱 상에서 더 깔끔한 것 같습니다.

동작이 다른 부분은 contentInset 부분인데요.
바뀌기 전의 코드에서는 확대 후에 사진을 여기저기 옮겨도 사진의 프레임이 화면의 프레임보다 안쪽으로 들어올 수 없었는데요.
바뀐 후의 코드는 확대 후에 사진을 여기저기 옮기면 사진의 프레임이 화면의 중앙까지 올 수 있게 변경 되었네요.

2023-01-28 06:23 UTC, JUNY0110 commented on GiwazipClient/Views/PostImageViewController.swift
> +        return self.postImage
> > p5. self.를 넣지 않아도 괜찮을 것 같습니다. 이미 extension 내 다른 변수에서도 사용되지 않기도 하구요
> 
> 저도 무의식적으로 self를 쓰긴 했는데 그렇군요! 그렇다면 보통 언제 self 쓰는 경우가 있을까요??!

self는 클래스나 구조체의 인스턴스 자신을 말하는데, .을 찍어서 소속을 구분합니다. `PostImageViewController.postImage`처럼 말이죠
그런데, 인스턴스는 클래스 외부에서만 접근할 수 있어서 `PostImageViewController` 내에서는 `PostImageViewController.postImage`라고 사용할 수 없습니다. 그래서 클래스 내부에서 프로퍼티와 일반변수의 이름이 같을 때, 구분하기 위해 사용하는 것이 self. 라고 할 수 있습니다.

하지만 현재 postImage와 중복된 이름이 없기 때문에 사용하지 않아도 될 것 같네요.
[self참고자료](https://velog.io/@junsuboy/Swift-self란)

2023-01-28 06:52 UTC, taek0622 commented on GiwazipClient/Views/PostImageViewController.swift
> +        return self.postImage
> > 저도 무의식적으로 self를 쓰긴 했는데 그렇군요! 그렇다면 보통 언제 self 쓰는 경우가 있을까요??!
> 
> self는 클래스나 구조체의 인스턴스 자신을 말하는데, .을 찍어서 소속을 구분합니다. `PostImageViewController.postImage`처럼 말이죠. 그런데, 인스턴스는 클래스 외부에서만 접근할 수 있어서 `PostImageViewController` 내에서는 `PostImageViewController.postImage`라고 사용할 수 없습니다. 그래서 기본적으로는 생략되어 사용되지만, 클래스 내부에서 프로퍼티와 일반변수의 이름이 같을 때, 구분하기 위해 사용하는 것이 self. 라고 할 수 있습니다.
> 
> 하지만 현재 postImage와 중복된 이름이 없기 때문에 사용하지 않아도 될 것 같네요. [self참고자료](https://velog.io/@junsuboy/Swift-self%EB%9E%80) [self사용에 대한 가벼운 고찰](https://doit-leed.tistory.com/94)

에디가 너무 잘 정리해주셔서 좋은 답변이 되었을 것 같은데, 하나 약간 보충해봅니다.

사실 `self`를 명시적으로 붙여주는 가장 큰 이유가 클래스 내부 프로퍼티와 일반 변수를 구분하기 위함이긴 하지만, 동시에 프로퍼티의 위치를 말해주기도 합니다.
저 또한 `self` 키워드를 최소화하는 방식을 좋아하긴 하지만, `self`를 최소화하는 것이 항상 좋은 방법이라고 말할 수는 없습니다.

프로젝트 규모가 점점 커지고, 클래스가 많아지면 어느 클래스에 어떤 프로퍼티가 있었는지 정확히 기억하지 못하게 될 때도 있습니다. 또한 서로 다른 클래스에 비슷한 이름을 가진 프로퍼티가 있을 수도 있죠. 그럴 때 self 키워드로 현재 클래스의 내부 프로퍼티라는 것을 명확히 알려줄 수 있습니다.
물론, Xcode 등의 IDE의 코드 하이라이팅으로도 어느정도 구분할 수 있습니다만, 개인마다 사용하는 IDE, 테마에 따라 하이라이팅 방법이 다를 수 있기 때문에 코드 하이라이팅이 외부 프로퍼티와 내부 프로퍼티를 명확히 구분해준다는 보장을 할 수 없죠.
그래서 간결성보다는 `self`를 명시적으로 붙여서 명확성을 높이는 경우도 있답니다.

다만, 이는 개발자와 팀이 코드 하이라이팅에 대한 부분이나, 프로퍼티에 대한 부분을 더 잘 정하고 가면 어느정도 해결할 수 있는 부분이기도 하여 저도 `self`를 최소화하는 것을 선호하긴 합니다.
어떻게 보면 선호도의 차이일 수도 있어서 해당 주제에 대해 월요일 회의에서 다시 한번 이야기 해보고 싶네요.

에디 좋은 자료와 정리 매우 감사합니다~ :)

2023-01-29 03:04 UTC, JUNY0110 approved these changes
고생하셨습니다~

2023-01-30 06:24 UTC, taek0622 approved these changes
고생하셨습니다.

2023-01-30 14:55 UTC, merged