[Design] 게시물 상세화면 레이아웃
Samsamhada/Giwazip-Client-App pull request #29
Opened 2023-01-28 11:06 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 게시물 상세화면 레이아웃을 추가하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- [x] (문의내역에서 들어왔을 경우) 네비게이션 우측에 수정 버튼
- [x] 화면 상단에 스크린 너비로 사진
  - 이미지 전환 시 썸네일 전환
- [x] 큰 사진 하단에 5개 썸네일 사진
  - 썸네일 클릭 시 이미지 전환
  - 현재 이미지 순서와 동일한 썸네일에 Stroke
- [x] 썸네일 하단에 divider
- [x] divider 아래에 게시글
  - 게시글 ScrollView 작업

## ScreenShot 📷 (참고 사진)
![Simulator Screen Recording - iPhone 14 - 2023-01-28 at 19 49 24](https://user-images.githubusercontent.com/98405970/215262882-fe3d5c60-034b-41f0-aac4-b6e837c4cead.gif)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- image/thumbnailCollectionView 모두 하나의 확장자 delegate, dataSource로 묶음
- 선택한 썸네일 이미지(didSelectItemAt: )에 대한 index값과 현재 보여지는 이미지의 indexPath가 동일할 때, 썸네일 stoke 반영
- 선택한 썸네일 이미지를 클릭 시, scrollToItem을 이용해 보여지는 이미지 전환
- ScrollViewWillEndDragging을 통해 selectedIndex에 현재 페이지 반영하여 썸네일 이미지의 동일한 indexPath에 설정 반영
- selectedIndex값 변경 시 didSet을 활용해 뷰 reload

## Close Issues 🔒 (닫을 Issue)
Close #27.

2023-01-28 12:28 UTC, taek0622 requested changes
고생하셨습니다.
전체적으로 컬렉션뷰 2개에 스크롤뷰 1개까지 뭔가 기능이 똘똘 뭉친 뷰 같은 느낌이네요.
이런 저런 작업으로 많이 고생하셨을 것으로 보입니다.
일부 수정이 필요한 부분에 코멘트, 그리고 많~은 질문 남겼습니다. 확인 부탁드려요.

추가적으로, 현재 collectionView가 스크롤 될 때, 아래와 같은 워닝들이 스크롤을 할때마다 발생하게 됩니다.
```shell
2023-01-28 21:26:06.570802+0900 GiwazipClient[94675:4170450] The behavior of the UICollectionViewFlowLayout is not defined because:
2023-01-28 21:26:06.570938+0900 GiwazipClient[94675:4170450] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2023-01-28 21:26:06.571093+0900 GiwazipClient[94675:4170450] The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x158713650>, and it is attached to <UICollectionView: 0x158832600; frame = (0 97.6667; 393 294.667); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000026f2eb0>; backgroundColor = <UIDynamicSystemColor: 0x600003d133c0; name = systemBackgroundColor>; layer = <CALayer: 0x6000028158c0>; contentOffset: {1043.6666666666667, 0}; contentSize: {1965, 294.66666666666669}; adjustedContentInset: {1.4210854715202004e-14, 0, 0, 0}; layout: <UICollectionViewFlowLayout: 0x158713650>; dataSource: <GiwazipClient.PostingViewController: 0x15990ac40>>.
2023-01-28 21:26:06.572739+0900 GiwazipClient[94675:4170450] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
```
어떤 문제인지 정확히는 모르겠지만, 일부 설정으로 해결할 수 있다고 하는 것 같습니다. 저 부분에 대해서 어떤 문제인지 같이 파악해보면 좋을 것 같아요.

2023-01-28 12:28 UTC, ikanic commented on GiwazipClient/Views/PostingViewController.swift
> +class PostingViewController: BaseViewController {
p5;
뷰 이름이 Posting이 되니까 게시물을 위한 사진이나 설명을 쓰는 뷰랑 헷갈리는데, PostViewController는 어떨까요?
혹은 PostDetailView도 좋구요. 조금더 게시물이라는 느낌을 주는게 좋을 것 같습니다.

2023-01-28 12:28 UTC, ikanic commented on GiwazipClient/Views/PostingViewController.swift
> +    var selectedIndex = 0 {
p2;
외부에서 접근할 일이 없는 부분 같은데, 접근지정자가 빠진 것 같습니다.

2023-01-28 12:28 UTC, ikanic commented on GiwazipClient/Views/PostingViewController.swift
> +            thumbnailCollectionView.reloadData()
Comment;
수정이 필요한 부분은 아니고, 아실거라고 생각하지만 해당 부분은 `[imageCollectionView, thumbnailCollectionView].forEach { $0.reloadData }`와 같이도 표현할 수 있답니다.
다만 현재 부분은 지금이 더 명확해서 고칠만한 부분은 아니고, 그냥 이런 식으로도 활용할 수 있다는 것 한번 말씀드려봅니다.

2023-01-28 12:28 UTC, ikanic commented on GiwazipClient/Views/PostingViewController.swift
> +        flowLayout.minimumLineSpacing = .zero
Question;
minimumLineSpacing이 CollectionView Cell들간의 최소간격을 정해주는 것이라는 것은 알겠는데, 이 부분이 빠지면 상단의 사진과 하단의 썸네일 모두 정상작동하지 않고, 사진을 바꿀수가 없게 되네요.
왜 이렇게 동작되는지 궁금합니다~

2023-01-28 12:28 UTC, ikanic commented on GiwazipClient/Views/PostingViewController.swift
> +        collectionView.alwaysBounceHorizontal = true
Question;
`alwaysBounceHorizontal`는 스크롤이 가로 컨텐츠의 끝에 도달했을 때 튀어오를지 여부를 결정하는 속성으로 알고 있는데요.
현재 이 부분은 true, false 바꾸면서 테스트해봐도 결과에 차이가 없는 것 같네요.
해당 부분이 어떻게 사용되고 있는지 궁금합니다~

2023-01-28 12:28 UTC, ikanic commented on GiwazipClient/Views/PostingViewController.swift
> +        flowLayout.minimumLineSpacing = 12
Question;
여기서는 minimumLineSpacing이 정상적으로 작동하고 있는게 맞을까요?
이렇게 저렇게 실험해봤는데 별 차이가 안보여서요. 0~100 사이에 숫자로 변경해서 테스트 해봤는데 차이가 나지 않는 것 같습니다.
차이가 없다면 아예 삭제되는게 나을 수도 있을 것 같습니다.

2023-01-28 12:28 UTC, ikanic commented on GiwazipClient/Views/PostingViewController.swift
> +                                     height: screenWidth / 6)
Question;
뭔가 왜인지는 모르겠지만, iPhone SE 기종 기준으로 /6까지는 썸네일 4개까지 밖에 안나오네요. /7을하면 SE 기종에서 5개가 나오기 시작합니다. `UIScreen.main.bounds`가 기종별 화면 크기를 가져오는 것으로 알고 있었는데, 뭔가 다른 로직으로 반영되고 있는 것일까요? 조금 더 조사가 필요해보입니다.

2023-01-28 12:28 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +        }
p4;
현재 스크롤뷰 자체가 인셋을 먹고 있는데, 인셋을 스크롤뷰가 아닌 설명 부분에 주는 것이 어떨까요?
스크롤뷰에 인셋이 들어가게되면서 가장자리에서 스크롤할경우에는 스크롤이 되지 않는 문제가 발생합니다.

Question;
추가로 인셋이 22인 이유가 있을까요? 보통 가장자리 인셋을 4의 배수인 16 정도로 주는 경우가 많아서 여쭤봅니다~

2023-01-28 12:28 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +            cell.layer.borderColor = CGColor(red: 0, green: 0, blue: 0, alpha: 1)
p5;
해당 부분은 `CGColor(~)` 방법보다는 `UIColor.black.cgColor`라는 방법을 사용하면 어떨까요? 이렇게 하면 검정색이라는 것이 더 한눈에 잘 보일 것 같습니다.

2023-01-28 12:28 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +                                             animated: true)
collectionView의 `scrollToItem` 메서드로 원하는 아이템을 보여줄 수 있네요.
이런 메서드가 있는지 처음 알았습니다. 에디 덕분에 활용하게 좋은 메서드 하나 알아가네요. 굳~ :)

p2;
한가지 말씀드리자면, 이 부분은 셀 자체에 대한 레이아웃 등이 아니라, 셀을 클릭했을 때의 동작을 표현하는 부분인 것 같아서, didSelectItemAt 쪽으로 이동하는게 더 맞지 않을까 생각이 듭니다.

2023-01-28 12:28 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +        if selectedIndex != indexPath.item { cell.layer.borderWidth = 0 }
p2;
이 부분은 다시 한번 if문이 나올 필요 없이 else로 붙여도 될 것 같습니다.

2023-01-28 15:58 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +                                             animated: true)
> 

이 부분에 대해 추가로 얘기를 나누고 싶은 부분이 있어서 didSelectItemAt이 아닌 cellForItemAt에 두었습니다.
만약 상단 이미지를 클릭해서 세부이미지를 볼 수 있고,
세부이미지 내에서 셀을 넘기는 것이 가능하도록 구현한다면,
다시 게시물뷰로 돌아왔을 때, 해당 이미지가 보이도록 해야할 것 같습니다.
그렇게 했을 때, scrollToItem이 cellForItemAt에 있어야 하기 때문에, 
월요일에 의견이 반영되지 않는다면 didSelectItemAt으로 옮기겠습니다.

2023-01-28 17:51 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +        if selectedIndex != indexPath.item { cell.layer.borderWidth = 0 }
> p2;
> 이 부분은 다시 한번 if문이 나올 필요 없이 else로 붙여도 될 것 같습니다.

9013a8a
if문이 더 읽기 쉽다고 생각했는데, else가 나은가보군요!

2023-01-28 17:51 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +            cell.layer.borderColor = CGColor(red: 0, green: 0, blue: 0, alpha: 1)
> p5;
> 해당 부분은 `CGColor(~)` 방법보다는 `UIColor.black.cgColor`라는 방법을 사용하면 어떨까요? 이렇게 하면 검정색이라는 것이 더 한눈에 잘 보일 것 같습니다.

9013a8a 동의합니다~

2023-01-28 17:51 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +    var selectedIndex = 0 {
> p2;
> 외부에서 접근할 일이 없는 부분 같은데, 접근지정자가 빠진 것 같습니다.

6ec3098

2023-01-28 17:52 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +    var selectedIndex = 0 {
> > p2;
> > 외부에서 접근할 일이 없는 부분 같은데, 접근지정자가 빠진 것 같습니다.
> 
> [6ec3098](https://github.com/Samsamhada/Giwazip-Client-App/commit/6ec3098c0336868a5673fdae042457a231c0db9c)

확인했습니다. 리뷰 리졸브합니다~

2023-01-28 17:53 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +            cell.layer.borderColor = CGColor(red: 0, green: 0, blue: 0, alpha: 1)
> > p5;
> > 해당 부분은 `CGColor(~)` 방법보다는 `UIColor.black.cgColor`라는 방법을 사용하면 어떨까요? 이렇게 하면 검정색이라는 것이 더 한눈에 잘 보일 것 같습니다.
> 
> [9013a8a](https://github.com/Samsamhada/Giwazip-Client-App/commit/9013a8a62eac02633ff9aa0dc2572eb6822b2576) 동의합니다~

확인했습니다. 리뷰 리졸브합니다~

2023-01-28 17:54 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +        if selectedIndex != indexPath.item { cell.layer.borderWidth = 0 }
> > p2;
> > 이 부분은 다시 한번 if문이 나올 필요 없이 else로 붙여도 될 것 같습니다.
> 
> [9013a8a](https://github.com/Samsamhada/Giwazip-Client-App/commit/9013a8a62eac02633ff9aa0dc2572eb6822b2576) if문이 더 읽기 쉽다고 생각했는데, else가 나은가보군요!

확인했습니다. if문도 읽기에 나쁘진 않았지만, 이미 위에서 조건이 명확하게 보이는 터라 else로도 충분할 거라고 생각했습니다.
리뷰 리졸브합니다~

2023-01-28 17:57 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +                                     height: screenWidth / 6)
> Question;
> 뭔가 왜인지는 모르겠지만, iPhone SE 기종 기준으로 /6까지는 썸네일 4개까지 밖에 안나오네요. /7을하면 SE 기종에서 5개가 나오기 시작합니다. `UIScreen.main.bounds`가 기종별 화면 크기를 가져오는 것으로 알고 있었는데, 뭔가 다른 로직으로 반영되고 있는 것일까요? 조금 더 조사가 필요해보입니다.

d6fe68d
저도 그 부분이 이상하다 생각했었는데, 원인을 얼추 알게 된 것 같습니다.
현재 collectionView는 horizon처럼 보이지만, 단순히 가로로 나열되어있을 뿐, 실제로는 vertical이 적용된 상태입니다.
그래서 minimuminteritemSpacing의  default value가 10으로 잡혀있었고, width가 부족하니 4개까지밖에 표현되지 않았던 것입니다.

interItemSpacing 간격을 0 으로 줄였고, cell이 여럿 있고 최소 간격이 남은 공간을 채우지 못할 때에 자동으로 동일한 간격으로 채워주고 있어 해결되었습니다.

2023-01-28 17:58 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +        collectionView.alwaysBounceHorizontal = true
> Question;
> `alwaysBounceHorizontal`는 스크롤이 가로 컨텐츠의 끝에 도달했을 때 튀어오를지 여부를 결정하는 속성으로 알고 있는데요.
> 현재 이 부분은 true, false 바꾸면서 테스트해봐도 결과에 차이가 없는 것 같네요.
> 해당 부분이 어떻게 사용되고 있는지 궁금합니다~

89fe426
cell이 horizontal로 이동되고 있어 bounce를 적용해야 자연스러운 줄 알았는데, 반영이 안 되는 상태였군요. 삭제했습니다~

2023-01-28 18:00 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +class PostingViewController: BaseViewController {
> p5;
> 뷰 이름이 Posting이 되니까 게시물을 위한 사진이나 설명을 쓰는 뷰랑 헷갈리는데, PostViewController는 어떨까요?
> 혹은 PostDetailView도 좋구요. 조금더 게시물이라는 느낌을 주는게 좋을 것 같습니다.

20a06f2

> p5;
> 뷰 이름이 Posting이 되니까 게시물을 위한 사진이나 설명을 쓰는 뷰랑 헷갈리는데, PostViewController는 어떨까요?
> 혹은 PostDetailView도 좋구요. 조금더 게시물이라는 느낌을 주는게 좋을 것 같습니다.

20a06f2 좋습니다~

2023-01-28 18:03 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +class PostingViewController: BaseViewController {
> > p5;
> > 뷰 이름이 Posting이 되니까 게시물을 위한 사진이나 설명을 쓰는 뷰랑 헷갈리는데, PostViewController는 어떨까요?
> > 혹은 PostDetailView도 좋구요. 조금더 게시물이라는 느낌을 주는게 좋을 것 같습니다.
> 
> [20a06f2](https://github.com/Samsamhada/Giwazip-Client-App/commit/20a06f21927830f9473eb065dc3be56bf650a857) 좋습니다~

확인했습니다. 한가지 이야기해보면 좋을만한 부분이 `PostCell` 부분인데요. 지금은 PostView의 Cell이니까 저렇게 이름 지었다 정도로 이해할 수 있지만, 실제로 저 부분은 사진만을 보여주는 부분이라 `PostPhotoCell` 등으로 했어도 괜찮을 것 같은데, 뷰 이름을 꼭 따라가야할 이유가 있었을까요?

2023-01-28 18:03 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +        collectionView.alwaysBounceHorizontal = true
> > Question;
> > `alwaysBounceHorizontal`는 스크롤이 가로 컨텐츠의 끝에 도달했을 때 튀어오를지 여부를 결정하는 속성으로 알고 있는데요.
> > 현재 이 부분은 true, false 바꾸면서 테스트해봐도 결과에 차이가 없는 것 같네요.
> > 해당 부분이 어떻게 사용되고 있는지 궁금합니다~
> 
> [89fe426](https://github.com/Samsamhada/Giwazip-Client-App/commit/89fe426e4cd4ae0a8946d17e1fd268d3ffe16fb2) cell이 horizontal로 이동되고 있어 bounce를 적용해야 자연스러운 줄 알았는데, 반영이 안 되는 상태였군요. 삭제했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-01-28 18:03 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +        flowLayout.minimumLineSpacing = .zero
> Question;
> minimumLineSpacing이 CollectionView Cell들간의 최소간격을 정해주는 것이라는 것은 알겠는데, 이 부분이 빠지면 상단의 사진과 하단의 썸네일 모두 정상작동하지 않고, 사진을 바꿀수가 없게 되네요.
> 왜 이렇게 동작되는지 궁금합니다~

글쎄요; 왜 인지는 저도 잘 모르겠네요

2023-01-28 18:05 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +        flowLayout.minimumLineSpacing = 12
> Question;
> 여기서는 minimumLineSpacing이 정상적으로 작동하고 있는게 맞을까요?
> 이렇게 저렇게 실험해봤는데 별 차이가 안보여서요. 0~100 사이에 숫자로 변경해서 테스트 해봤는데 차이가 나지 않는 것 같습니다.
> 차이가 없다면 아예 삭제되는게 나을 수도 있을 것 같습니다.

d6fe68d
LineSpacing이 아닌 InterItemSpacing으로 수정했습니다.

2023-01-28 18:07 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +        }
> p4; 현재 스크롤뷰 자체가 인셋을 먹고 있는데, 인셋을 스크롤뷰가 아닌 설명 부분에 주는 것이 어떨까요? 스크롤뷰에 인셋이 들어가게되면서 가장자리에서 스크롤할경우에는 스크롤이 되지 않는 문제가 발생합니다.
> 
> Question; 추가로 인셋이 22인 이유가 있을까요? 보통 가장자리 인셋을 4의 배수인 16 정도로 주는 경우가 많아서 여쭤봅니다~

559c71c
Figma에 디자인되어있는대로 만들었었고, 해당 패딩값에 대해 추가논의를 위해 일부러 22로 그대로 만들었습니다. (그러면 누군가 발견하고 의문을 품을테니까요)
스크롤뷰 및 패딩 16으로 수정했습니다.

2023-01-28 18:11 UTC, JUNY0110 commented
> 고생하셨습니다. 전체적으로 컬렉션뷰 2개에 스크롤뷰 1개까지 뭔가 기능이 똘똘 뭉친 뷰 같은 느낌이네요. 이런 저런 작업으로 많이 고생하셨을 것으로 보입니다. 일부 수정이 필요한 부분에 코멘트, 그리고 많~은 질문 남겼습니다. 확인 부탁드려요.
> 
> 추가적으로, 현재 collectionView가 스크롤 될 때, 아래와 같은 워닝들이 스크롤을 할때마다 발생하게 됩니다.
> 
> ```shell
> 2023-01-28 21:26:06.570802+0900 GiwazipClient[94675:4170450] The behavior of the UICollectionViewFlowLayout is not defined because:
> 2023-01-28 21:26:06.570938+0900 GiwazipClient[94675:4170450] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
> 2023-01-28 21:26:06.571093+0900 GiwazipClient[94675:4170450] The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x158713650>, and it is attached to <UICollectionView: 0x158832600; frame = (0 97.6667; 393 294.667); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000026f2eb0>; backgroundColor = <UIDynamicSystemColor: 0x600003d133c0; name = systemBackgroundColor>; layer = <CALayer: 0x6000028158c0>; contentOffset: {1043.6666666666667, 0}; contentSize: {1965, 294.66666666666669}; adjustedContentInset: {1.4210854715202004e-14, 0, 0, 0}; layout: <UICollectionViewFlowLayout: 0x158713650>; dataSource: <GiwazipClient.PostingViewController: 0x15990ac40>>.
> 2023-01-28 21:26:06.572739+0900 GiwazipClient[94675:4170450] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
> ```
> 
> 어떤 문제인지 정확히는 모르겠지만, 일부 설정으로 해결할 수 있다고 하는 것 같습니다. 저 부분에 대해서 어떤 문제인지 같이 파악해보면 좋을 것 같아요.

저는 이 문제가 발생하지 않는데 지금도 발생하는지 확인 부탁드려요~

2023-01-28 18:11 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +                                     height: screenWidth / 6)
> 

확인했습니다. 해당 부분에 대해 조금 더 찾아봤는데, collectionView가 horizontal일 때와 vertical일 때 동작이 미묘하게 다른게 상당히 어지럽네요.
이미 에디는 찾아보셔서 아실 거라고 생각되지만, 조금더 공부가 필요한 저와 모르실 수도 있을 디너를 위해 아래에 레퍼런스 첨부해봅니다.

- [kel.log - UICollectionView Spacing이 헷갈리는 사건에 대하여...](https://velog.io/@leeinae/UICollectionView-Spacing%EC%9D%B4-%ED%97%B7%EA%B0%88%EB%A6%AC%EB%8A%94-%EC%82%AC%EA%B1%B4%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC)

2023-01-28 18:15 UTC, taek0622 commented
> > 고생하셨습니다. 전체적으로 컬렉션뷰 2개에 스크롤뷰 1개까지 뭔가 기능이 똘똘 뭉친 뷰 같은 느낌이네요. 이런 저런 작업으로 많이 고생하셨을 것으로 보입니다. 일부 수정이 필요한 부분에 코멘트, 그리고 많~은 질문 남겼습니다. 확인 부탁드려요.
> > 추가적으로, 현재 collectionView가 스크롤 될 때, 아래와 같은 워닝들이 스크롤을 할때마다 발생하게 됩니다.
> > ```shell
> > 2023-01-28 21:26:06.570802+0900 GiwazipClient[94675:4170450] The behavior of the UICollectionViewFlowLayout is not defined because:
> > 2023-01-28 21:26:06.570938+0900 GiwazipClient[94675:4170450] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
> > 2023-01-28 21:26:06.571093+0900 GiwazipClient[94675:4170450] The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x158713650>, and it is attached to <UICollectionView: 0x158832600; frame = (0 97.6667; 393 294.667); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x6000026f2eb0>; backgroundColor = <UIDynamicSystemColor: 0x600003d133c0; name = systemBackgroundColor>; layer = <CALayer: 0x6000028158c0>; contentOffset: {1043.6666666666667, 0}; contentSize: {1965, 294.66666666666669}; adjustedContentInset: {1.4210854715202004e-14, 0, 0, 0}; layout: <UICollectionViewFlowLayout: 0x158713650>; dataSource: <GiwazipClient.PostingViewController: 0x15990ac40>>.
> > 2023-01-28 21:26:06.572739+0900 GiwazipClient[94675:4170450] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 어떤 문제인지 정확히는 모르겠지만, 일부 설정으로 해결할 수 있다고 하는 것 같습니다. 저 부분에 대해서 어떤 문제인지 같이 파악해보면 좋을 것 같아요.
> 
> 저는 이 문제가 발생하지 않는데 지금도 발생하는지 확인 부탁드려요~

네 여전히 문제가 발생합니다. 다만, SE 기종으로 돌렸을 때는 문제가 발생하지 않고, iPhone 14 Pro로 돌렸을 때는 발생하는 걸로 보아 기종에 따른 레이아웃 문제인 것 같습니다. 좀 더 같이 찾아보고 해결 부탁드려요~

2023-01-28 18:16 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +        }
> > p4; 현재 스크롤뷰 자체가 인셋을 먹고 있는데, 인셋을 스크롤뷰가 아닌 설명 부분에 주는 것이 어떨까요? 스크롤뷰에 인셋이 들어가게되면서 가장자리에서 스크롤할경우에는 스크롤이 되지 않는 문제가 발생합니다.
> > Question; 추가로 인셋이 22인 이유가 있을까요? 보통 가장자리 인셋을 4의 배수인 16 정도로 주는 경우가 많아서 여쭤봅니다~
> 
> [559c71c](https://github.com/Samsamhada/Giwazip-Client-App/commit/559c71c8020af8a0cfb6d2302bb59dd689669100) Figma에 디자인되어있는대로 만들었었고, 해당 패딩값에 대해 추가논의를 위해 일부러 22로 그대로 만들었습니다. (그러면 누군가 발견하고 의문을 품을테니까요) 스크롤뷰 및 패딩 16으로 수정했습니다.

확인했습니다. 리뷰 리졸브합니다~

2023-01-28 18:18 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +        flowLayout.minimumLineSpacing = 12
> > Question;
> > 여기서는 minimumLineSpacing이 정상적으로 작동하고 있는게 맞을까요?
> > 이렇게 저렇게 실험해봤는데 별 차이가 안보여서요. 0~100 사이에 숫자로 변경해서 테스트 해봤는데 차이가 나지 않는 것 같습니다.
> > 차이가 없다면 아예 삭제되는게 나을 수도 있을 것 같습니다.
> 
> [d6fe68d](https://github.com/Samsamhada/Giwazip-Client-App/commit/d6fe68d42b2fe8f0cb74dea69f0972e0f5b4d2ab) LineSpacing이 아닌 InterItemSpacing으로 수정했습니다.

확인했습니다. 해당 부분이 InterItem으로 수정된 이유는 아래의 리뷰에서 제가 첨부한 레퍼런스로 확인했기 때문에 별도로 질문하지 않겠습니다.

2023-01-29 02:29 UTC, creohwan reviewed
고생하셨습니다~! 콜렉션 뷰로 스크롤을 구현한 게 재밌군요! 몇가지 궁금한 점 코멘트로 남겼습니다

+ 현재 레이아웃에 살짝 문제가 있는 것 같습니다! 관련하여 해당 이미지 첨부해요! 저도 어느 부분에서 문제가 있는지 다시 한번 보도록 하겠습니다~

![스크린샷 2023-01-29 11 09 55](https://user-images.githubusercontent.com/92836045/215301097-76f93299-2e87-43ee-982a-0cf7ee212d9e.png)

2023-01-29 02:29 UTC, creohwan commented on GiwazipClient/Views/PostViewController.swift
> +        collectionView.isPagingEnabled = true
collectionView.isPagingEnabled = true 로 해서 1장씩만 넘길 수 있도록 한 것 좋습니다!~

2023-01-29 02:29 UTC, creohwan commented on GiwazipClient/Views/PostViewController.swift
> +    }
p3;
여기서 return 5는 imageCollectionView와 thumbnailCollectionView를 각각 5개씩 return하는 걸까요? (제가 print문을 찍어서 확인해보니 imageCollectionView는 1개, thumbnailCollectionView 5개로 확인되는 것 같아서요! 아닐 수도 있습니다~! =D)

Q: imageCollectionView와 thumbnailCollectionView중 무엇이 먼저 return 될까요? 순서는 어떻게 정해지는지 궁금합니다~! 

또한 밑에 func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell 함수에서도 어떤 CollectionView가 먼저 들어가는지도 궁금합니다~!

2023-01-29 02:29 UTC, creohwan commented on GiwazipClient/Views/PostViewController.swift
> +        flowLayout.minimumLineSpacing = .zero
Q:flowLayout.minimumLineSpacing = .zero 로 주신 이유가 있을까요??!

2023-01-29 02:29 UTC, creohwan commented on GiwazipClient/Views/PostViewController.swift
> +        let pageNumber = targetContentOffset.pointee.x / scrollView.frame.width
pageNumber를 이렇게 알아내는 방법이 있군요~!

2023-01-29 02:47 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +class PostingViewController: BaseViewController {
> 확인했습니다. 한가지 이야기해보면 좋을만한 부분이 `PostCell` 부분인데요. 지금은 PostView의 Cell이니까 저렇게 이름 지었다 정도로 이해할 수 있지만, 실제로 저 부분은 사진만을 보여주는 부분이라 `PostPhotoCell` 등으로 했어도 괜찮을 것 같은데, 뷰 이름을 꼭 따라가야할 이유가 있었을까요?

이미 PostingPhotoCell이 있어 PostPhotoCell로 하면 모호해 헷갈리기쉬울 것 같습니다. 차라리 VC와 같은 이름을 주는 것이 더 명확하게 전달이 되지 않을까요?

2023-01-29 02:50 UTC, JUNY0110 commented on GiwazipClient/Views/PostViewController.swift
> +        collectionView.isPagingEnabled = true
> Q: collectionView.isPagingEnabled = true 로 한 이유가, cell을 하나씩 넘기도록 하기 위함 맞을까요??!

넵 맞습니다.
`isPagingEnabled = true`를 하면 cell을 넘길 때 cell단위로 끊어가며 넘길 수 있습니다.

2023-01-29 03:00 UTC, JUNY0110 commented on GiwazipClient/Views/PostViewController.swift
> +    }
> p3; 여기서 return 5는 imageCollectionView와 thumbnailCollectionView를 각각 5개씩 return하는 걸까요? (제가 print문을 찍어서 확인해보니 imageCollectionView는 1개, thumbnailCollectionView 5개로 확인되는 것 같아서요! 아닐 수도 있습니다~! =D)
> 
> Q: imageCollectionView와 thumbnailCollectionView중 무엇이 먼저 return 될까요? 순서는 어떻게 정해지는지 궁금합니다~!
> 
> Q: 또한 밑에 func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell 함수에서도 어떤 CollectionView가 먼저 들어가는지도 궁금합니다~!

1. 각각 5개씩 return되고 있는 것이 맞습니다. `didSelectAt`으로 indexPath 프린트찍으면 확인이 가능합니다.
2. 거의 동시에 될 것 같네요. collectionView에 대해 같은 delegate와 extension, cell을 사용하고 있기 때문입니다.
3. 2번과 동일합니다. 하지만 if문이 있기 때문에 미묘한 차이로 thumbnailView가 조금 늦게 호출될 수는 있겠네요

2023-01-29 03:01 UTC, JUNY0110 commented on GiwazipClient/Views/PostViewController.swift
> +        flowLayout.minimumLineSpacing = .zero
> Q:flowLayout.minimumLineSpacing = .zero 로 주신 이유가 있을까요??!

- `flowLayout.minimumLineSpacing `은 기본값이 10입니다.
-  하지만 저희가 보여줄 이미지는 이미지 간의 사이 간격이 없어야 하므로 `.zero`로 반영하였습니다.

2023-01-29 04:17 UTC, JUNY0110 commented
> 네 여전히 문제가 발생합니다. 다만, SE 기종으로 돌렸을 때는 문제가 발생하지 않고, iPhone 14 Pro로 돌렸을 때는 발생하는 걸로 보아 기종에 따른 레이아웃 문제인 것 같습니다. 좀 더 같이 찾아보고 해결 부탁드려요~

3ad45ad
iphone14 Pro의 width는 393으로 layout이 소수점이 있어 발생하는 문제로 보입니다.
그래서 기기마다 너비가 다르기에 에러가 발생하기도, 안 하기도 하는 것이었습니다.
cell관련 전체 layout을 round처리하여 추가로 발생할 수 있는 layout에러가 없도록 하였습니다.

height는 Double타입인데 왜 294.75면 안 되는지 이유는 잘 모르겠네요. 추가로 파악되면 글 남기겠습니다~

2023-01-29 06:04 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +class PostingViewController: BaseViewController {
> > 확인했습니다. 한가지 이야기해보면 좋을만한 부분이 `PostCell` 부분인데요. 지금은 PostView의 Cell이니까 저렇게 이름 지었다 정도로 이해할 수 있지만, 실제로 저 부분은 사진만을 보여주는 부분이라 `PostPhotoCell` 등으로 했어도 괜찮을 것 같은데, 뷰 이름을 꼭 따라가야할 이유가 있었을까요?
> 
> 이미 PostingPhotoCell이 있어 PostPhotoCell로 하면 모호해 헷갈리기쉬울 것 같습니다. 차라리 VC와 같은 이름을 주는 것이 더 명확하게 전달이 되지 않을까요?

현재로서는 뷰랑 이름을 같게해도 잘 보이긴 합니다만, 만약 다른 뷰에서 여러 셀이 필요해진다면 또 다른 이야기가 될 것 같아서 조금 더 용도와 의미에 맞게 셀의 이름을 정하면 어떨까 해서 의견 내봤습니다.
우선 현재 부분은 `PostingPhoto`와 헷갈릴 가능성이 있다는 의견에 동의해서 그대로 가도 좋을 것 같네요.
다만, 셀의 이름은 고객용 어플 회의 초기에도 이야기 나왔듯이 용도에 맞는 이름에 대해 다시 한번 이야기 해보는 것이 좋을 것 같습니다.

2023-01-29 06:25 UTC, taek0622 commented on GiwazipClient/Views/PostViewController.swift
> +    }
> > p3; 여기서 return 5는 imageCollectionView와 thumbnailCollectionView를 각각 5개씩 return하는 걸까요? (제가 print문을 찍어서 확인해보니 imageCollectionView는 1개, thumbnailCollectionView 5개로 확인되는 것 같아서요! 아닐 수도 있습니다~! =D)
> > Q: imageCollectionView와 thumbnailCollectionView중 무엇이 먼저 return 될까요? 순서는 어떻게 정해지는지 궁금합니다~!
> > Q: 또한 밑에 func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell 함수에서도 어떤 CollectionView가 먼저 들어가는지도 궁금합니다~!
> 
> 1. 각각 5개씩 return되고 있는 것이 맞습니다. `didSelectAt`으로 indexPath 프린트찍으면 확인이 가능합니다.
> 2. 거의 동시에 될 것 같네요. collectionView에 대해 같은 delegate와 extension, cell을 사용하고 있기 때문입니다.
> 3. 2번과 동일합니다. 하지만 if문이 있기 때문에 미묘한 차이로 thumbnailView가 조금 늦게 호출될 수는 있겠네요

해당 답변에 보충 설명 합니다.

Q: imageCollectionView와 thumbnailCollectionView중 무엇이 먼저 return 될까요? 순서는 어떻게 정해지는지 궁금합니다~!
=> 이 질문에 대한 답은 CollectionView만 말씀드리자면 imageCollectionView가 먼저 return 됩니다. UIKit의 addSubview 순서에 따라 뷰가 배치되기 때문입니다.

Q: 또한 밑에 func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell 함수에서도 어떤 CollectionView가 먼저 들어가는지도 궁금합니다~!
=> 이 질문에 대한 답은 직접 print문으로 찍어보면서 알 수 있었는데요. 순서상 thumbnailView가 더 늦게 호출될거라고 생각했지만, 의외로 thumbnailView의 cell들이 모두 나온 후에 imageCollectionView의 Cell이 나오는 것을 확인할 수 있었습니다.
테스트는 총 30번 진행했으며, 30번 모두 같은 순서로 나오는 것을 확인했습니다. 다른 사진을 클릭했을 때의 동작도 확인했습니다.

조금 보기 어려우실 수 있겠지만, 아래에 사진 첨부합니다.
<img width="517" alt="스크린샷 2023-01-29 15 24 28" src="https://user-images.githubusercontent.com/81027256/215309018-cf80fab6-d473-4263-a1eb-11cd25cfdb2e.png">
<img width="517" alt="스크린샷 2023-01-29 15 24 53" src="https://user-images.githubusercontent.com/81027256/215309041-f4362739-c932-47c2-afef-2f611dab8801.png">
<img width="511" alt="스크린샷 2023-01-29 15 25 45" src="https://user-images.githubusercontent.com/81027256/215309083-d491356b-fe2b-44fc-bb36-5821e1046a60.png">

2023-01-29 06:33 UTC, taek0622 commented
추가적으로 리뷰라고 하긴 좀 어렵고, 시뮬레이터 실행시 일부 워닝에 대해서 공유해봅니다.
<img width="517" alt="스크린샷 2023-01-29 15 32 38" src="https://user-images.githubusercontent.com/81027256/215309356-d5ce486c-7653-4751-a73b-20b384e32ac3.png">
시뮬레이터 실행시 위와 같은 2개의 워닝이 출력될 때가 있는데, 해당 부분은 시뮬레이터 상에서 해당 부분을 정상적으로 사용할 수 없어 출력되는 워닝으로, 실 기기에서는 아무 문제 없이 사용할 수 있습니다.

2023-01-30 15:24 UTC, JUNY0110 commented on GiwazipClient/Views/PostingViewController.swift
> +                                             animated: true)
> collectionView의 `scrollToItem` 메서드로 원하는 아이템을 보여줄 수 있네요. 이런 메서드가 있는지 처음 알았습니다. 에디 덕분에 활용하게 좋은 메서드 하나 알아가네요. 굳~ :)
> 
> p2; 한가지 말씀드리자면, 이 부분은 셀 자체에 대한 레이아웃 등이 아니라, 셀을 클릭했을 때의 동작을 표현하는 부분인 것 같아서, didSelectItemAt 쪽으로 이동하는게 더 맞지 않을까 생각이 듭니다.

733bb15
회의 결과 옮기기로 하였기에 반영하였습니다. 
추가로 함수를 일부 수정하였으니 같이 확인해주시면 될 것 같습니다

2023-01-30 15:34 UTC, taek0622 commented on GiwazipClient/Views/PostingViewController.swift
> +                                             animated: true)
> > collectionView의 `scrollToItem` 메서드로 원하는 아이템을 보여줄 수 있네요. 이런 메서드가 있는지 처음 알았습니다. 에디 덕분에 활용하게 좋은 메서드 하나 알아가네요. 굳~ :)
> > p2; 한가지 말씀드리자면, 이 부분은 셀 자체에 대한 레이아웃 등이 아니라, 셀을 클릭했을 때의 동작을 표현하는 부분인 것 같아서, didSelectItemAt 쪽으로 이동하는게 더 맞지 않을까 생각이 듭니다.
> 
> [733bb15](https://github.com/Samsamhada/Giwazip-Client-App/commit/733bb15d3bb3bba738f0dff881df1046b16a099b) 회의 결과 옮기기로 하였기에 반영하였습니다. 추가로 함수를 일부 수정하였으니 같이 확인해주시면 될 것 같습니다

확인했습니다. 리뷰 리졸브합니다~

2023-01-30 15:38 UTC, taek0622 approved these changes
고생하셨습니다.
해당 뷰가 로직이 기존 어플이랑 많이 다르다보니, 새로운게 많아서 궁금한 것도 많고 질문도 정말 많았는데, 하나하나 열심히 답해주셔서 너무 감사합니다.
에디 덕분에 새로운 부분 많이 알아가는 것 같아요. 굳~ :)

2023-01-30 15:38 UTC, ikanic commented on GiwazipClient/Views/PostViewController.swift
> +    }
ㅎㅎ 누가 고안해줬는지 아주 좋은 코드네요.
잘 반영한 것 같습니다. 에디가 함수를 조금이라도 더 많이 활용할 기회가 있었으면 좋겠다 생각했는데, 좋은 경험인 것 같아요. 굳~ :)

2023-01-30 15:42 UTC, merged