[Feature] 썸네일 클릭 시 동작
Samsamhada/Giwazip-Client-App pull request #31
Opened 2023-01-31 06:16 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 미선택 셀 white필터 추가
- 공통 사용되는 screenWidth를 BaseVC에 포함시키기 위함.

## Key Changes 🔥 (주요 구현/변경 사항)
- 미선택 셀 white필터 추가
- screenWidth BaseVC 추가

## ScreenShot 📷 (참고 사진)
https://user-images.githubusercontent.com/98405970/215681439-d94d7fb7-b302-4cf3-869f-a937a3eff69f.mp4

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 초 심플 코드

## Close Issues 🔒 (닫을 Issue)
Close #30.

2023-01-31 07:26 UTC, taek0622 requested changes
고생하셨습니다.
전체적으로 간단하고 깔끔한 코드라서 볼게 많진 않네요.
수정되면 좋을 것 같은 부분과 조금 더 고민해볼 부분 리뷰 남겼습니다. 확인 부탁드려요~

2023-01-31 07:26 UTC, taek0622 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
p2;
해당 부분에서 `$0.layer.backgroundColor`를 사용한 이유가 있을까요?
별다른 이유가 없다면 `$0.backgroundColor`를 사용했어도 됐을 것 같습니다.
`$0.backgroundColor`를 사용한다고 하면, `$0.backgroundColor = UIColor(white: 1, alpha: 0.5)`와 같이도 사용할 수 있어서, 조금 더 무슨 색인지 명확하게 보여줄 수 있지 않았을까요?

2023-01-31 07:26 UTC, taek0622 commented on GiwazipClient/Cells/PostCell.swift
> +    }(UIView())
해당 셀에서 스트로크와 오퍼시티 레이어, 이미지를 위한 부분이 총 3개나 들어가서 줄여보려고 시도했는데, 여러가지 방법으로 같은 모양을 만들 수는 있었으나, 코드의 의미상으로 현재처럼 `isHidden`을 하는 것이 가장 깔끔하네요. 굳 입니다~ :)

2023-01-31 07:26 UTC, taek0622 commented on GiwazipClient/Supports/BaseViewController.swift
> +
누가 알려준 코드인지 매우 깔끔하네요 ^^

2023-01-31 07:26 UTC, taek0622 commented on GiwazipClient/Views/PostViewController.swift
> +        }
이 부분은 뭔가 클릭 이벤트와도 관련있는 부분인 것 같은데, 어디론가 옮기기도 애매하고, 그냥 두자니 그것도 좀 애매하네요..
조금 더 로직에 대한 고민이 필요할지도 모르겠습니다.

2023-01-31 15:04 UTC, JUNY0110 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
> p2;
> 해당 부분에서 `$0.layer.backgroundColor`를 사용한 이유가 있을까요?
> 별다른 이유가 없다면 `$0.backgroundColor`를 사용했어도 됐을 것 같습니다.
> `$0.backgroundColor`를 사용한다고 하면, `$0.backgroundColor = UIColor(white: 1, alpha: 0.5)`와 같이도 사용할 수 있어서, 조금 더 무슨 색인지 명확하게 보여줄 수 있지 않았을까요?

Q. 
Layer.backgroundColor는 UIView의 Layer 프로퍼티에 직접 색을 반영해서 background에 색을 반영해주고,
backgroundColor는 UIView를 Delegate를 거쳐 Layer에 색을 반영하게 되는 것으로 알고 있는데 같다고 봐야할까요? 아니면 차이가 있을까요?

2023-01-31 15:04 UTC, JUNY0110 commented on GiwazipClient/Cells/PostCell.swift
> +    }(UIView())
> 해당 셀에서 스트로크와 오퍼시티 레이어, 이미지를 위한 부분이 총 3개나 들어가서 줄여보려고 시도했는데, 여러가지 방법으로 같은 모양을 만들 수는 있었으나, 코드의 의미상으로 현재처럼 `isHidden`을 하는 것이 가장 깔끔하네요. 굳 입니다~ :)

가장 쉽고 이해하기 쉬운 코드를 짜봤습니다 ^^

2023-01-31 15:04 UTC, JUNY0110 commented on GiwazipClient/Supports/BaseViewController.swift
> +
> 누가 알려준 코드인지 매우 깔끔하네요 ^^

미 선생 덕분이죠

2023-01-31 18:03 UTC, taek0622 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
> > p2;
> > 해당 부분에서 `$0.layer.backgroundColor`를 사용한 이유가 있을까요?
> > 별다른 이유가 없다면 `$0.backgroundColor`를 사용했어도 됐을 것 같습니다.
> > `$0.backgroundColor`를 사용한다고 하면, `$0.backgroundColor = UIColor(white: 1, alpha: 0.5)`와 같이도 사용할 수 있어서, 조금 더 무슨 색인지 명확하게 보여줄 수 있지 않았을까요?
> 
> Q. Layer.backgroundColor는 UIView의 Layer 프로퍼티에 직접 색을 반영해서 background에 색을 반영해주고, backgroundColor는 UIView를 Delegate를 거쳐 Layer에 색을 반영하게 되는 것으로 알고 있는데 같다고 봐야할까요? 아니면 차이가 있을까요?
> 
> [View, Layer 관계](https://woookdev.github.io/programming/iOS-View%EC%99%80-Layer-%EA%B4%80%EA%B3%84-%EC%A0%95%EB%A6%AC/)

이해가 약간 잘못된 것 같아서 설명해보자면, 우선 UIView만 보자면 결국 layer.backgroundColor와 backgroundColor가 같습니다. UIStackView, UILabel 등 다른 컴포넌트들은 동작이 다르지만, UIView는 이 둘이 완전히 동일한 동작을 해요.
UIView와 Layer에 대해 말해보자면, 실제로 UIView는 레이아웃을 그릴 때, UIView 자체에 레이아웃을 그리는 것이 아니고, Layer에 그리게 됩니다. 이 둘의 관계는 Layer는 UIView의 프로퍼티이고, UIView는 Layer의 Delegate 그 자체입니다.
즉, UIView에서 backgroundColor를 설정하면, 별도의 Delegate를 거치는 것이 아니라, UIView 자체가 Delegate 역할을 해서 layer의 backgroundColor에 반영하게 되요.
반대로 layer의 backgroundColor에 직접 색을 지정해주면 어떻게 되나 보자면, layer에 backgroundColor를 설정해도, layer에 backgroundColor가 설정됨과 동시에 layer의 Delegate인 UIView에도 backgroundColor를 적용하게 됩니다.
즉, 이 둘은 직접 레이어에 줘서 델리게이트에도 반영했느냐, 델리게이트에 적용해서 레이어에도 반영했느냐의 순서의 차이일 뿐 UIView에서는 같은 동작을 하게 됩니다.
둘의 차이가 있다면, layer.backgroundColor는 CGColor를 사용하고, UIView의 backgroundColor는 UIColor를 사용한다는 점인데요. CGColor는 CG라는 이름에서도 알 수 있듯이 코어 그래픽스 프레임워크와 연관된 색상 집합입니다. UIColor는 UI라는 이름에서 알 수 있듯이 UIKit 프레임워크와 연관된 색상 집합이구요.
일반적으로 용도에 따라 적합한 것을 사용하는 것이 맞지만, 둘 다 사용할 수 있는 경우, CGColor가 코어 애니메이션의 색상 집합인 만큼 배열과 함께 사용해야 하는 경우가 많아서 UIColor를 사용한다고 합니다.
또한, UIColor에는 필요에 따라 .cgColor나 .ciColor 같은 메서드를 이용하여 원하는 용도의 색상 집합으로 변경할 수도 있기 때문에 UIColor를 많이 사용하는 듯해요.
추가로, UIColor의 경우 CGColor보다 더 많은 색에 대한 편리한 메서드들을 제공하기 때문에 UIKit에서는 특수한 경우를 제외하고는 UIColor를 더 많이 사용하는 것 같습니다.

2023-02-01 00:21 UTC, creohwan reviewed
코드가 굉장히 깔끔해졌네요! 고생하셨습니다~!

2023-02-01 00:21 UTC, creohwan commented on GiwazipClient/Supports/BaseViewController.swift
> +    let screenWidth = UIScreen.main.bounds.width
오호! 좋군요~

2023-02-01 06:24 UTC, JUNY0110 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
> 

음, 제 질문은 동작이 같냐 다르냐가 아닌, delegate를 사용해서 보여주는 것과 직접 Layer에 반영을 해서 보여주는 것의 성능이나 메모리에서의 차이가 있는지에 대한 질문이었습니다. 동작도 같고 적용되는 바도 같지만 정말 모든 면에서 완전히 같을 수 있을까? 라는 것입니다.

2023-02-01 06:28 UTC, taek0622 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
> > 
> 
> 음, 제 질문은 동작이 같냐 다르냐가 아닌, delegate를 사용해서 보여주는 것과 직접 Layer에 반영을 해서 보여주는 것의 성능이나 메모리에서의 차이가 있는지에 대한 질문이었습니다. 동작도 같고 적용되는 바도 같지만 정말 모든 면에서 완전히 같을 수 있을까? 라는 것입니다.

네 이 둘은 UIView에서 완전히 같은 동작을 하기 때문에 메모리나 성능에서도 같다고 볼 수 있습니다.

2023-02-02 12:13 UTC, JUNY0110 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
de2a0e9

2023-02-02 12:58 UTC, taek0622 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
> [de2a0e9](https://github.com/Samsamhada/Giwazip-Client-App/commit/de2a0e9c7ab3f3c3af810b61b15d60cedf5d7442)

rebase가 잘못된건지 수정사항이 이상하게 반영된 것 같습니다. 다시 한번 확인 부탁드려요.

2023-02-02 14:11 UTC, JUNY0110 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
> > [de2a0e9](https://github.com/Samsamhada/Giwazip-Client-App/commit/de2a0e9c7ab3f3c3af810b61b15d60cedf5d7442)
> 
> rebase가 잘못된건지 수정사항이 이상하게 반영된 것 같습니다. 다시 한번 확인 부탁드려요.

리베이스 에러같은데, 코드는 반영되어있습니다~

2023-02-02 14:12 UTC, taek0622 approved these changes
고생하셨습니다.
도중에 수정사항이 리베이스 문제로 확인이 제대로 안되었었는데, 이제야 제대로 확인이 되네요.
고생 많으셨습니다~

2023-02-02 14:12 UTC, merged

2023-02-02 14:12 UTC, taek0622 commented on GiwazipClient/Cells/PostCell.swift
> +        $0.layer.backgroundColor = CGColor(red: 1, green: 1, blue: 1, alpha: 0.5)
> 

확인했습니다~