[Feature] 문의내역 작성하기 버튼 동작
Samsamhada/Giwazip-Client-App pull request #35
Opened 2023-02-02 11:51 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 버튼 애니메이션 추가하기 위함
- 네비게이션 추가하기 위함(Coordinator)
- 일부 셀 레이아웃 에러를 바로잡기 위함.

## Key Changes 🔥 (주요 구현/변경 사항)
- [ ] 시공내역 탭일 때 버튼 내려가게
- [ ] 문의내역 탭일 때 버튼이 올라오게
- [ ] 버튼 클릭 시 FullScreen Modal
- [ ] 셀 레이아웃 수정

## ScreenShot 📷 (참고 사진)
https://user-images.githubusercontent.com/98405970/216266493-3070769c-aec6-48f9-a923-f7d5217894f1.mp4

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 코드자체는 간단하지만, 일부 셀 레이아웃에 대한 ambiguous error가 있어 해당 부분에 대해 수정하였습니다.
```swift
if self.currentViewNum == 1 {
    self.inquiryButton.bounds = CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: 90)
} else {
    self.inquiryButton.bounds = CGRect(x: 0, y: -90, width: UIScreen.main.bounds.width, height: 90)
}

pageContentView.addSubview(inquiryButton)
inquiryButton.snp.makeConstraints {
    $0.horizontalEdges.bottom.equalToSuperview()
    $0.height.equalTo(90)
}
```
- layout으로 `heightAnchor = 90`으로 잡았기 때문에, height = 90인 inquiryButton의 좌상단을 기준으로 (0,0)좌표를 가짐.
- 또한 inquiryButton의 bottom Constraint가 view.bottom을 기준으로 height = 90을 잡았기 때문에, origin좌표는 변하지 않음
- inquiryButton의 y축 -90만큼 내려 버튼이 내려가는 동작 구현
- inquiryButton의 y축을 0으로 돌려 버튼이 올라가는 동작 구현
  - y축을 -90내려도 실제 constraint는 bottom기준 height = 90을 받고 있기 때문에, isEnable = false를 하지않으면 보이지 않더라도 버튼동작이 가능함. 따라서 isEnable.toggle이 반영됨.
  - currentViewNum == 0일 때, bounds에서 'y= 0' 'height= -90'으로 하여도 동작은 동일하지만, hierarchy를 보면 y값이 -90, height = 90으로, 실제는 y축이 변동되기 때문에 height를 변경하지 않고 y축을 변경하였음.

- frame이 아닌 bounds를 사용한 이유는, 
  - frame은 inquiryButton의 superView 즉 view의 기준좌표(0, 0)를 기준으로 하지만,
  - bounds는 inquiryButton 본인의 기준좌표(0, 0)을 기준으로 하기 때문에 bounds를 사용해야 정상동작 구현이 가능.

- 설명 오류이거나 잘못된 코드라면 리뷰 남겨주시면 감사함:) :) :)

## Reference 🔗
- [Animation](https://jinnify.tistory.com/66)

## Close Issues 🔒 (닫을 Issue)
Close #32.

2023-02-02 13:02 UTC, taek0622 requested changes
고생하셨습니다.
이번에는 교체된 파일이 많아서 확인하는데 조금 어려웠네요 ㅠㅠ
그치만 많은 작업 해주셔서 너무 감사합니다.
일부 수정이 필요한 곳에 리뷰 남겼습니다. 확인 부탁드려요~

또한, rebase가 약간 잘못되어서 문제가 발생한 곳이 몇 군데 보이는데, 같이 확인 부탁드립니다.

2023-02-02 13:02 UTC, ikanic commented on GiwazipClient/Cells/PostDateCell.swift
>          }
p1;
현재 데이트셀의 constraint가 전체적으로 잘못된 것 같습니다.
아래의 하이어라키를 보시면 아시겠지만, 데이트셀의 선들과 레이블을 포함하고 있는 UIView의 높이가 1로 잡혀있는 것을 볼 수 있습니다.
<img width="777" alt="스크린샷 2023-02-02 21 15 07" src="https://user-images.githubusercontent.com/81027256/216322149-444e787b-bbe8-4fea-acbf-bc4ade572766.png">

이 부분은 아래와 같이 변경해서 해결할 수 있을 것 같네요.
suggestion이 정상적으로 먹지 않아서 코드 라인을 말씀드려보자면 60~80번째 줄 전부입니다.
```suggestion
        dateStack.addSubview(leftDashLine)
        leftDashLine.snp.makeConstraints {
            $0.left.centerY.equalToSuperview()
            $0.width.equalTo(UIScreen.main.bounds.width / 3)
            $0.height.equalTo(1)
        }
        
        dateStack.addSubview(postingDate)
        postingDate.snp.makeConstraints {
            $0.left.equalTo(leftDashLine.snp.right)
            $0.width.equalTo(UIScreen.main.bounds.width / 3)
            $0.verticalEdges.equalToSuperview()
            $0.centerY.equalToSuperview()
        }
        
        dateStack.addSubview(rightDashLine)
        rightDashLine.snp.makeConstraints {
            $0.right.centerY.equalToSuperview()
            $0.left.equalTo(postingDate.snp.right)
            $0.width.equalTo(UIScreen.main.bounds.width / 3)
            $0.height.equalTo(1)
        }
```

해당 부분을 위와 같이 변경시 하이어라키가 아래와 같이 정상 반영되는 것을 확인할 수 있습니다.
<img width="751" alt="스크린샷 2023-02-02 21 20 03" src="https://user-images.githubusercontent.com/81027256/216323163-b32e34fb-cccc-4256-a623-89513033a661.png">

또한, 그 동안 데이트셀이 이상하게 정렬되었던 이유도 이 부분의 문제로 보이네요.

2023-02-02 13:02 UTC, ikanic commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +    // MARK: - ViewController
p5;
중요한 부분은 아니지만, ViewController라고 하면 조금 애매한 감이 있어서 showVC Method 등 조금 더 알아보기 쉬운 명칭은 어떨까요?

2023-02-02 13:02 UTC, ikanic commented on GiwazipClient/Coordinators/PostingPhotoCoordinator.swift
> +    }
분명 맞는 코드인데, 왜 이렇게 안읽히나 모르겟네요.. ㅠㅠ

2023-02-02 13:02 UTC, ikanic commented on GiwazipClient/Coordinators/SegmentCoordinator.swift
> +    }
p5;
MARK로 property와 method를 구분해주시면 어떨까요?

2023-02-02 13:02 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +
p3;
해당 뷰에 버튼이 없는데 Configure만 있어서 뭔가 싶었는데, rebase하면서 뭔가 잘못된거 같네요.
삭제가 필요해보입니다.

2023-02-02 13:02 UTC, ikanic commented on GiwazipClient/Views/SegmentViewController.swift
> +            $0.height.equalTo(90)
p1;
이렇게 저렇게 테스트해봐도 동작이 뭔가 이상해서 계속 보다가 발견했는데, inquiryButton이 2번이나 들어가있네요.
하나 삭제 부탁드립니다.

2023-02-02 13:02 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +                    self.inquiryButton.bounds = CGRect(x: 0, y: -90, width: UIScreen.main.bounds.width, height: 90)
이 부분에 대해서 에디의 PR 설명을 보고 많이 고민하고 실험해보았는데, 실제로 height를 죽이는 것보다는 y 값을 조정하는 것이 의미상으로나 동작상으로 훨씬 깔끔한 것 같습니다. 너무 잘 구현해주셨네요. 굳~ :)

2023-02-03 08:36 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +
> p3;
> 해당 뷰에 버튼이 없는데 Configure만 있어서 뭔가 싶었는데, rebase하면서 뭔가 잘못된거 같네요.
> 삭제가 필요해보입니다.

f3f661e
확인 감사합니다

2023-02-03 08:36 UTC, JUNY0110 commented on GiwazipClient/Coordinators/SegmentCoordinator.swift
> +    }
> p5;
> MARK로 property와 method를 구분해주시면 어떨까요?

b09d823

2023-02-03 08:37 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +            $0.height.equalTo(90)
> p1;
> 이렇게 저렇게 테스트해봐도 동작이 뭔가 이상해서 계속 보다가 발견했는데, inquiryButton이 2번이나 들어가있네요.
> 하나 삭제 부탁드립니다.

65e83bf 엥.. 생각도 못했네요. 확인감사합니다.

2023-02-03 08:38 UTC, JUNY0110 commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +    // MARK: - ViewController
> p5;
> 중요한 부분은 아니지만, ViewController라고 하면 조금 애매한 감이 있어서 showVC Method 등 조금 더 알아보기 쉬운 명칭은 어떨까요?

00e840d 수정~

2023-02-03 08:41 UTC, JUNY0110 commented on GiwazipClient/Cells/PostDateCell.swift
>          }
> p1; 현재 데이트셀의 constraint가 전체적으로 잘못된 것 같습니다. 아래의 하이어라키를 보시면 아시겠지만, 데이트셀의 선들과 레이블을 포함하고 있는 UIView의 높이가 1로 잡혀있는 것을 볼 수 있습니다. <img alt="스크린샷 2023-02-02 21 15 07" width="777" src="https://user-images.githubusercontent.com/81027256/216322149-444e787b-bbe8-4fea-acbf-bc4ade572766.png">
> 
> 이 부분은 아래와 같이 변경해서 해결할 수 있을 것 같네요. suggestion이 정상적으로 먹지 않아서 코드 라인을 말씀드려보자면 60~80번째 줄 전부입니다.
> 
> 해당 부분을 위와 같이 변경시 하이어라키가 아래와 같이 정상 반영되는 것을 확인할 수 있습니다. <img alt="스크린샷 2023-02-02 21 20 03" width="751" src="https://user-images.githubusercontent.com/81027256/216323163-b32e34fb-cccc-4256-a623-89513033a661.png">
> 
> 또한, 그 동안 데이트셀이 이상하게 정렬되었던 이유도 이 부분의 문제로 보이네요.

f4c3a7a
dateStack에 높이가 지정될만한 요소가 없어서 그랬던 것 같습니다. 
dateStack의 top, bottom constraint를 잡고, offSet(8)을 주는 것이 의미가 맞는 것 같아 이처럼 수정하였습니다.
또한 DashLine에 top, bottom constraint를 제거하여 라인 굵기도 유지했습니다.
꼼꼼한 확인 감사합니다.

2023-02-03 08:47 UTC, taek0622 commented on GiwazipClient/Cells/PostDateCell.swift
>          }
> > p1; 현재 데이트셀의 constraint가 전체적으로 잘못된 것 같습니다. 아래의 하이어라키를 보시면 아시겠지만, 데이트셀의 선들과 레이블을 포함하고 있는 UIView의 높이가 1로 잡혀있는 것을 볼 수 있습니다.
> > 또한, 그 동안 데이트셀이 이상하게 정렬되었던 이유도 이 부분의 문제로 보이네요.
> 
> [f4c3a7a](https://github.com/Samsamhada/Giwazip-Client-App/commit/f4c3a7aa09bac30a2bcdf18b79000f5eb778296b) dateStack에 높이가 지정될만한 요소가 없어서 그랬던 것 같습니다. dateStack의 top, bottom constraint를 잡고, offSet(8)을 주는 것이 의미가 맞는 것 같아 이처럼 수정하였습니다. 또한 DashLine에 top, bottom constraint를 제거하여 라인 굵기도 유지했습니다. 꼼꼼한 확인 감사합니다.

확인했습니다. 리뷰 리졸브합니다.

2023-02-03 08:48 UTC, taek0622 commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +    // MARK: - ViewController
> > p5;
> > 중요한 부분은 아니지만, ViewController라고 하면 조금 애매한 감이 있어서 showVC Method 등 조금 더 알아보기 쉬운 명칭은 어떨까요?
> 
> [00e840d](https://github.com/Samsamhada/Giwazip-Client-App/commit/00e840d1db959a3c4b53db3728ed5ae9fb90440f) 수정~

확인했습니다. 리뷰 리졸브합니다~

2023-02-03 08:49 UTC, taek0622 commented on GiwazipClient/Coordinators/SegmentCoordinator.swift
> +    }
> > p5;
> > MARK로 property와 method를 구분해주시면 어떨까요?
> 
> [b09d823](https://github.com/Samsamhada/Giwazip-Client-App/commit/b09d823a5f9d187cf7f865c2e8c2a1e2c66821b3)

확인했습니다. 리뷰 리졸브합니다~

2023-02-03 08:49 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +
> > p3;
> > 해당 뷰에 버튼이 없는데 Configure만 있어서 뭔가 싶었는데, rebase하면서 뭔가 잘못된거 같네요.
> > 삭제가 필요해보입니다.
> 
> [f3f661e](https://github.com/Samsamhada/Giwazip-Client-App/commit/f3f661e12b9264662bcd5606cda01f438e029c5c) 확인 감사합니다

확인했습니다. 리뷰 리졸브합니다~

2023-02-03 08:49 UTC, ikanic commented on GiwazipClient/Views/SegmentViewController.swift
> +            $0.height.equalTo(90)
> > p1;
> > 이렇게 저렇게 테스트해봐도 동작이 뭔가 이상해서 계속 보다가 발견했는데, inquiryButton이 2번이나 들어가있네요.
> > 하나 삭제 부탁드립니다.
> 
> [65e83bf](https://github.com/Samsamhada/Giwazip-Client-App/commit/65e83bf0ae4e5154b0649e786d8fb01e0c91e371) 엥.. 생각도 못했네요. 확인감사합니다.

확인했습니다. 리뷰 리졸브합니다~

2023-02-03 09:01 UTC, taek0622 commented on GiwazipClient/Cells/PostDateCell.swift
>          }
> > p1; 현재 데이트셀의 constraint가 전체적으로 잘못된 것 같습니다. 아래의 하이어라키를 보시면 아시겠지만, 데이트셀의 선들과 레이블을 포함하고 있는 UIView의 높이가 1로 잡혀있는 것을 볼 수 있습니다.
> > 또한, 그 동안 데이트셀이 이상하게 정렬되었던 이유도 이 부분의 문제로 보이네요.
> 
> [f4c3a7a](https://github.com/Samsamhada/Giwazip-Client-App/commit/f4c3a7aa09bac30a2bcdf18b79000f5eb778296b) dateStack에 높이가 지정될만한 요소가 없어서 그랬던 것 같습니다. dateStack의 top, bottom constraint를 잡고, offSet(8)을 주는 것이 의미가 맞는 것 같아 이처럼 수정하였습니다. 또한 DashLine에 top, bottom constraint를 제거하여 라인 굵기도 유지했습니다. 꼼꼼한 확인 감사합니다.

확인했습니다. 다만, 올바른 동작으로 수정된 것 같지는 않네요.

2023-02-05 06:28 UTC, JUNY0110 commented on GiwazipClient/Cells/PostDateCell.swift
>          }
> 이 세 문제를 다 해결해야 더 자연스러운 모습으로 보일 수 있을 것 같네요.

음 그냥 cell을 header로 옮겨서 해결했습니다. 
PostDateHeader가 날짜별 반복되어야하기 때문이고,
ASCell은 항상 최상단 고정이고, 클릭모션이 추가되어야하기 때문에 Cell로 수정했습니다.
날짜값이 눈에 띄지 않는다는 문제가 있지만, 나중에 재논의하면 좋을 것 같네요.

2023-02-05 06:40 UTC, taek0622 commented on GiwazipClient/Cells/PostDateCell.swift
>          }
> > 이 세 문제를 다 해결해야 더 자연스러운 모습으로 보일 수 있을 것 같네요.
> 
> [1969460](https://github.com/Samsamhada/Giwazip-Client-App/commit/1969460c9f9a182ecda35d781147f7c6e48b3677) 음 그냥 cell을 header로 옮겨서 해결했습니다. PostDateHeader가 날짜별 반복되어야하기 때문이고, ASCell은 항상 최상단 고정이고, 클릭모션이 추가되어야하기 때문에 Cell로 수정했습니다. 날짜값이 눈에 띄지 않는 것 같지만, 나중에 재논의하면 좋을 것 같네요.

확인했습니다. 날짜가 눈에 안띄어서 간격이 필요하다면 셀 아이템과 헤더 사이의 간격을 주는 방법을 사용할 수 있을 것 같네요.
후에 회의에서 다시 이야기 해보아요. 고생하셨습니다.

2023-02-05 06:44 UTC, taek0622 approved these changes
고생하셨습니다.
BaseViewController도 그렇고 이것 저것 공통적인 부분이나 이동에 대한 부분 같은 것이 많이 추가된 것 같네요.
실제 에디 태스크가 엄청나게 크지 않았음에도 이것 저것 함께하다보니 줄 수가 어느새 270 라인이나 되어버렸군요 ㅠㅠ
고생 너무 많으셨습니다. 항상 감사해요 에디~

2023-02-05 09:43 UTC, merged