Design:iphone:: #33 Textview Design
Samsamhada/Giwazip-Client-App pull request #37
Opened 2023-02-06 10:18 UTC by creohwan

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 문의 내역 텍스트 뷰

## Key Changes 🔥 (주요 구현/변경 사항)
- 문의 내역 텍스트 뷰 생성

## ToDo 📆 (남은 작업)
- [ ] todo

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 늦어서 죄송합니다~!

## Reference 🔗

## Close Issues 🔒 (닫을 Issue)
Close #33

2023-02-06 10:40 UTC, taek0622 requested changes
고생하셨습니다.
그런데 파일 하나가 빠져서 빌드가 안되네요 ㅠㅠ
우선 그 부분을 억지로 무시하고 빌드해서 확인한 만큼만 리뷰 남겼습니다.
빌드 안되는 문제부터 해결되고 나서 나머지 리뷰 확인 부탁드립니다.

2023-02-06 10:40 UTC, taek0622 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		43C8EA3B299096B1002DBCFC /* MainButton.swift in Sources */ = {isa = PBXBuildFile; fileRef = 43C8EA3A299096B1002DBCFC /* MainButton.swift */; };
p1;
pbx 파일에는 MainButton이 포함되어 있는데, 이번 PR에 MainButton.Swift 파일 자체가 없어서 빌드 자체가 되지 않습니다.

2023-02-06 10:40 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.font = UIFont.systemFont(ofSize: 18, weight: .regular)
p2;
textView의 텍스트 사이즈는 피그마 상에서 16으로 되어있네요.

2023-02-06 10:40 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.backgroundColor = .lightGray
텍스트 뷰의 색상과 섀도우가 피그마와 다른 것 같긴 하지만, 아직 해당 부분 색이 온전히 정해진 것이 아니니 후에 다시 논의해보도록 하죠.

2023-02-06 10:40 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.layer.cornerRadius = 10
p1;
해당 부분은 피그마에서 radius 8로 되어있습니다.

2023-02-06 10:40 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration?.attributedTitle?.font = UIFont.systemFont(ofSize: 18, weight: .semibold)
p1;
요 부분은 피그마 상에서 bold로 되어있네요.
다만, 각 뷰마다 버튼의 폰트 사이즈와 weight가 다르게 되어 있어서 이부분에 대해서는 다시 한번 이야기해보아야 할 것 같습니다.

2023-02-06 10:40 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration?.background.backgroundColor = .gray
p1;
해당 부분을 아래와 같이 바꾸면 일일이 색상 조정할 필요 없이, 버튼의 `isEnabled` 속성만 바꾸는 것으로 색을 같이 바꿀 수 있습니다.
```suggestion
        $0.configuration?.baseForegroundColor = .white
        $0.configuration?.baseBackgroundColor = .blue
```

이 코드가 적용된다면 아래의 `textViewDidChange` function 내부에서 일일이 색상을 바꾸지 않고, `isEnabled` 값만 true, false로 조절해도 되겠네요.

2023-02-06 10:40 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +            $0.top.equalTo(textGuideLabel).offset(30)
p1;
여기 constraint가 30씩이나 되는데 보여지기엔 간격이 넓지 않아서 확인해보니, textView의 top을 textGuideLabel의 top에서 30 떨어지게 주었네요.
해당 부분은 `textGuideLabel.snp.bottom`으로 bottom 값과 간격을 줘야할 것 같습니다.

2023-02-07 00:14 UTC, creohwan commented on GiwazipClient.xcodeproj/project.pbxproj
> +		43C8EA3B299096B1002DBCFC /* MainButton.swift in Sources */ = {isa = PBXBuildFile; fileRef = 43C8EA3A299096B1002DBCFC /* MainButton.swift */; };
> p1; pbx 파일에는 MainButton이 포함되어 있는데, 이번 PR에 MainButton.Swift 파일 자체가 없어서 빌드 자체가 되지 않습니다.

dfb7b01 으악 죄송합니다~

2023-02-07 00:15 UTC, taek0622 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		43C8EA3B299096B1002DBCFC /* MainButton.swift in Sources */ = {isa = PBXBuildFile; fileRef = 43C8EA3A299096B1002DBCFC /* MainButton.swift */; };
> > p1; pbx 파일에는 MainButton이 포함되어 있는데, 이번 PR에 MainButton.Swift 파일 자체가 없어서 빌드 자체가 되지 않습니다.
> 
> [dfb7b01](https://github.com/Samsamhada/Giwazip-Client-App/commit/dfb7b0162ce835688e0701e562bd0a14dcfea218) 으악 죄송합니다~

확인했습니다.

2023-02-07 00:16 UTC, creohwan commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.font = UIFont.systemFont(ofSize: 18, weight: .regular)
> p2; textView의 텍스트 사이즈는 피그마 상에서 16으로 되어있네요.

8e38d69 반영했습니다~

2023-02-07 00:16 UTC, creohwan commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.layer.cornerRadius = 10
> p1; 해당 부분은 피그마에서 radius 8로 되어있습니다.

8e38d69 반영했습니다~

2023-02-07 00:16 UTC, creohwan commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration?.attributedTitle?.font = UIFont.systemFont(ofSize: 18, weight: .semibold)
> p1; 요 부분은 피그마 상에서 bold로 되어있네요. 다만, 각 뷰마다 버튼의 폰트 사이즈와 weight가 다르게 되어 있어서 이부분에 대해서는 다시 한번 이야기해보아야 할 것 같습니다.

8e38d69 반영했습니다~

2023-02-07 00:18 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.font = UIFont.systemFont(ofSize: 18, weight: .regular)
> > p2; textView의 텍스트 사이즈는 피그마 상에서 16으로 되어있네요.
> 
> [8e38d69](https://github.com/Samsamhada/Giwazip-Client-App/commit/8e38d692c9b407812674ce52f80ca1c94f0bd587) 반영했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-02-07 00:18 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.layer.cornerRadius = 10
> > p1; 해당 부분은 피그마에서 radius 8로 되어있습니다.
> 
> [8e38d69](https://github.com/Samsamhada/Giwazip-Client-App/commit/8e38d692c9b407812674ce52f80ca1c94f0bd587) 반영했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-02-07 00:18 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration?.attributedTitle?.font = UIFont.systemFont(ofSize: 18, weight: .semibold)
> > p1; 요 부분은 피그마 상에서 bold로 되어있네요. 다만, 각 뷰마다 버튼의 폰트 사이즈와 weight가 다르게 되어 있어서 이부분에 대해서는 다시 한번 이야기해보아야 할 것 같습니다.
> 
> [8e38d69](https://github.com/Samsamhada/Giwazip-Client-App/commit/8e38d692c9b407812674ce52f80ca1c94f0bd587) 반영했습니다~

확인했습니다. 리뷰 리졸브합니다~

2023-02-07 03:50 UTC, creohwan commented on GiwazipClient/Views/PostingTextViewController.swift
> +            $0.top.equalTo(textGuideLabel).offset(30)
8fbcdd4 반영했습니다~ 16으로 반영했습니다~ (피그마엔 17로 나와있는데 뭔가 숫자가 애매해서 16으로 했습니다!)

2023-02-07 03:56 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +            $0.top.equalTo(textGuideLabel).offset(30)
> [8fbcdd4](https://github.com/Samsamhada/Giwazip-Client-App/commit/8fbcdd4ab2efc42627102d06f2ba2f6909541cad) 반영했습니다~ 16으로 반영했습니다~ (피그마엔 17로 나와있는데 뭔가 숫자가 애매해서 16으로 했습니다!)

확인했습니다. 리뷰 리졸브합니다.

2023-02-07 04:03 UTC, creohwan commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration?.background.backgroundColor = .gray
> p1; 해당 부분을 아래와 같이 바꾸면 일일이 색상 조정할 필요 없이, 버튼의 `isEnabled` 속성만 바꾸는 것으로 색을 같이 바꿀 수 있습니다.
> 
> 이 코드가 적용된다면 아래의 `textViewDidChange` function 내부에서 일일이 색상을 바꾸지 않고, `isEnabled` 값만 true, false로 조절해도 되겠네요.

923a0ea 오호 이런 방법이~! base 친구들을 쓰면 아주 좋군요!

2023-02-07 04:04 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration?.background.backgroundColor = .gray
> > p1; 해당 부분을 아래와 같이 바꾸면 일일이 색상 조정할 필요 없이, 버튼의 `isEnabled` 속성만 바꾸는 것으로 색을 같이 바꿀 수 있습니다.
> > 이 코드가 적용된다면 아래의 `textViewDidChange` function 내부에서 일일이 색상을 바꾸지 않고, `isEnabled` 값만 true, false로 조절해도 되겠네요.
> 
> [923a0ea](https://github.com/Samsamhada/Giwazip-Client-App/commit/923a0ea98215c8ef829936e678739aabfed5a34b) 오호 이런 방법이~! base 친구들을 쓰면 아주 좋군요!

확인했습니다.

2023-02-07 04:17 UTC, taek0622 approved these changes
고생하셨습니다.
TextView라서 그런지 String과 Text와 관련된 신기한 어트리뷰트랑 메서드들을 많이 보게 되는 것 같네요.
아주 좋습니다~ :)
딱 한군데 제안사항 남겼습니다. 확인 부탁드려요~

2023-02-07 04:17 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.textAlignment = .natural
그동안 `.left`만 생각하고 있었는데, localization을 생각한다면 `.natural`이 더 좋은 선택지가 되겠네요. 굳~ :)

2023-02-07 04:17 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration = buttonConfiguration
p5;
`buttonConfiguration`이 이 안에서 한번만 사용될 것이라면 아래와 같이 한줄로 합치는 것은 어떨까요?
```suggestion
        $0.configuration = UIButton.Configuration.filled()
```

2023-02-07 04:17 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +            (textView.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)  {
이렇게 사용하면 내용 없이 띄어쓰기나, 줄 바꿈만 했을 때도 걸러낼 수 있겠네요. 굳~ :)

2023-02-07 13:33 UTC, JUNY0110 approved these changes
수고하셨습니다! 저는 버튼은 textView를 클릭하면 같이 올라오거나, 아니면 키보드가 내려가지 않아도 될 것 같습니다.

2023-02-07 13:33 UTC, JUNY0110 commented on GiwazipClient/Views/PostingTextViewController.swift
> +    private lazy var finishButton: UIButton = {
p2.
private let이어도 될 것 같습니다!

2023-02-07 13:33 UTC, JUNY0110 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        if (textView.text == textViewPlaceHolder) ||
p2.
`(textView.text == textViewPlaceHolder) ||`는 없어도 동작이 동일한데, 있어야하는 이유가 따로 있을까요?

2023-02-08 00:17 UTC, creohwan commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration = buttonConfiguration
> p5; `buttonConfiguration`이 이 안에서 한번만 사용될 것이라면 아래와 같이 한줄로 합치는 것은 어떨까요?

a27ab55 감사합니다~

2023-02-08 00:18 UTC, creohwan commented on GiwazipClient/Views/PostingTextViewController.swift
> +    private lazy var finishButton: UIButton = {
> p2. private let이어도 될 것 같습니다!

e6779f0 감사합니다~

2023-02-08 00:25 UTC, taek0622 commented on GiwazipClient/Views/PostingTextViewController.swift
> +        $0.configuration = buttonConfiguration
> > p5; `buttonConfiguration`이 이 안에서 한번만 사용될 것이라면 아래와 같이 한줄로 합치는 것은 어떨까요?
> 
> [a27ab55](https://github.com/Samsamhada/Giwazip-Client-App/commit/a27ab55c577dc5f065e61ed1919446fbd76d1cbb) 감사합니다~

확인했습니다. 리뷰 리졸브합니다~

2023-02-08 07:41 UTC, creohwan reviewed
b6bee97 버튼 애니메이션 추가했습니다~! 감사합니다 :)

https://user-images.githubusercontent.com/92836045/217465323-f30e71c6-0bf8-48ca-9893-cfbc738bee29.mp4

2023-02-08 07:55 UTC, JUNY0110 commented
> [b6bee97](https://github.com/Samsamhada/Giwazip-Client-App/commit/b6bee97faedf3afbccbbd7bd63b49030628b2541) 버튼 애니메이션 추가했습니다~! 감사합니다 :)
> 
>  KakaoTalk_Video_2023-02-08-16-40-18.mp4

버튼이 올라왔을 때, 사이즈가 20 줄어드는 동작이 있어야할 것 같습니다
노션에 미뉴가 정리해뒀으니 참고해주세요~

2023-02-09 01:48 UTC, creohwan commented
c6f25f1 마지막 커밋!

2023-02-09 14:14 UTC, merged

2023-02-09 14:15 UTC, taek0622 commented
> [c6f25f1](https://github.com/Samsamhada/Giwazip-Client-App/commit/c6f25f18303cf7bf75b316f63162c9e7fec527bb) 마지막 커밋!
> 
> 20밖에 차이가 안 나서, 긴가민가 하실 수 있습니다. 30 200 이런 식으로 바꿔서 동작해보면, 잘 되는 거 확인하실 수 있으실 겁니다~! 그동안 정말로 감사했습니다.

그동안 고생하셨어요 디너~ :)