[Design] 진행률 셀 추가
Samsamhada/Giwazip-Client-App pull request #40
Opened 2023-02-12 19:01 UTC by taek0622

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 시공내역에서 상단에 카테고리별 진행률을 보여주기 위한 셀을 추가하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- 카테고리별 진행률을 보여주기 위한 `ProgressCell` 추가
- HistoryViewController에 시공내역, 문의내역을 분기하기 위한 `isWorkingView` 프로퍼티 추가
- 시공내역, 문의내역에 따라 컬렉션 뷰의 진행률, AS 셀을 분기하기 위한 구문 추가

## ToDo 📆 (남은 작업)
- [ ] 진행률 물결 형태로 변경

## ScreenShot 📷 (참고 사진)
<img src="https://user-images.githubusercontent.com/81027256/218331126-4fb6b8cd-0cff-429a-ad4c-31c055a35efa.gif" width="300">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 상당히 간만에 클라이언트를 만져보네요. 드디어 클라이언트를 할 수 있어서 너무 기쁩니다..!
- 사진상으로 눈에 띄지 않을 수 있지만, 현재 Opacity가 적용되어 있는 상태입니다. 선택된 아이템만 opacity가 Hidden되고 있습니다. 해당 부분은 현재 색상이 전체적으로 밝아서 생기는 문제로, 후에 배경색과 차트 색이 바뀌면 눈에 띄게 바뀌게 될 것 같습니다.
- 진행률 부분을 물결선으로 적용해서 올리고 싶었으나, 아직 BezierPath 사용에 미숙한 관계로 우선 물결선을 제외하고 올립니다. 해당 부분은 계속 시도 중이니 완성되는대로 해당 부분에 대한 새로운 PR 올리겠습니다.

## Reference 🔗
- [개발자 키우기 - [iOS] CollectionView 선택한 아이템 UI 변경하기](https://superwony.tistory.com/158)

## Close Issues 🔒 (닫을 Issue)
Close #No.

2023-02-14 08:28 UTC, JUNY0110 requested changes
고생하셨습니다. 오랜만에 클라작업이셨네요! 베지에를 사용하는 작업이라 까다로웠을텐데 잘 해주셔서 감사합니다.

2023-02-14 08:28 UTC, JUNY0110 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		2614F251299802BE0051EE51 /* WaveView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 2614F250299802BE0051EE51 /* WaveView.swift */; };
p3.
파일 위치를 ASCell 위로 조정하는 게 어떨까요? 
뷰의 상단부터 하단순으로 Cell 위치를 조정하면 파일을 찾기 더 수월할 것 같습니다.

2023-02-14 08:28 UTC, JUNY0110 commented on GiwazipClient/Cells/ProgressCell.swift
> +        $0.layer.borderColor = UIColor.black.cgColor
p2.
border는 default Color가 black이라 없어도 삭제해도 무방할 것 같습니다.

2023-02-14 08:28 UTC, JUNY0110 commented on GiwazipClient/Cells/ProgressCell.swift
> +    private let view: UIView = {
p3.
이름이 view라고 하니, 뷰의 역할을 알기 어렵네요.
progressBaseView, baseView, borderView처럼 어떤 역할을 갖는 뷰인지 명시해주면 좋을 것 같습니다.

2023-02-14 08:28 UTC, JUNY0110 commented on GiwazipClient/Cells/ProgressCell.swift
> +    override private init(frame: CGRect) {
p2.
private은 빠지는 것으로 회의되었던 것 같습니다~

2023-02-14 08:28 UTC, JUNY0110 commented on GiwazipClient/Cells/WaveView.swift
> +        shape.addLine(to: CGPoint(x: 0, y: bounds.maxY / 100 * (100 - progress)))
p2.
읽기가.. 힘드네요.. 줄바꿈이 필요할 것 같습니다.
가능한 100자 이내에서는 줄바꿈하는 컨벤션이 있죠!

2023-02-14 08:28 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +
굿. 간단하게 분기하는 역할로 좋네요

의견)
isWorkingView으로 정한 이유가 있으신가요? isConverted 같은 이름은 어떤가요?

2023-02-14 08:28 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            cell.progress = Double((indexPath.item % 10 + 1) * 10)
Q.
서버에서 Float로 받는 것으로 알고 있는데, Double로 작성한 이유가 있을까요?
어차피 서버에서 변환해준다면, 처음부터 Float로 하는 건 어떨까요?

2023-02-14 08:28 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
p3.
뷰 동작과 관련된 코드라고 생각되어지는데, didSelectItemAt에서 사용하는게 자연스러울 것 같습니다.

Q.
animated: false
scrollPosition: ___
해당 내용이 다른 값으로 변경되어도 동작이 동일한데, 이유를 아실까요??

2023-02-14 08:35 UTC, taek0622 commented on GiwazipClient/Cells/ProgressCell.swift
> +    private let view: UIView = {
> p3. 이름이 view라고 하니, 뷰의 역할을 알기 어렵네요. progressBaseView, baseView, borderView처럼 어떤 역할을 갖는 뷰인지 명시해주면 좋을 것 같습니다.

해당 부분은 baseView, progressView 같은 느낌보다는 Frame 자체를 잡기위해 존재하는 뷰이기 때문에 view로 잡았습니다.

2023-02-14 08:37 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +
> 굿. 간단하게 분기하는 역할로 좋네요
> 
> 의견) isWorkingView으로 정한 이유가 있으신가요? isConverted 같은 이름은 어떤가요?

`isConverted`는 무엇을 convert 한다는 것인지 명확해 보이지 않는 것 같습니다. 문의내역인지 시공내역인지 판단한다는 느낌에서 `isWorkingView`가 조금 더 명확한 것 같네요.

2023-02-14 08:38 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +            cell.progress = Double((indexPath.item % 10 + 1) * 10)
> Q. 서버에서 Float로 받는 것으로 알고 있는데, Double로 작성한 이유가 있을까요? 어차피 서버에서 변환해준다면, 처음부터 Float로 하는 건 어떨까요?

해당 부분은 현재 정수이기 때문에 변환시켜주기 위해 필요했던 부분으로, 서버가 바뀐 현재는 Double로 형변환이 필요하지 않을 것 같습니다.

2023-02-14 08:40 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
> p3. 뷰 동작과 관련된 코드라고 생각되어지는데, didSelectItemAt에서 사용하는게 자연스러울 것 같습니다.
> 
> Q. animated: false scrollPosition: ___ 해당 내용이 다른 값으로 변경되어도 동작이 동일한데, 이유를 아실까요??

해당 부분은 초기값을 지정하는 부분으로 터치 동작과 직접 연관이 있지 않고, didSelectItemAt으로 뺄 수 있는 부분도 아니기에 현재와 같이 넣었습니다.

2023-02-14 08:43 UTC, taek0622 commented on GiwazipClient/Cells/ProgressCell.swift
> +        $0.layer.borderColor = UIColor.black.cgColor
> p2. border는 default Color가 black이라 없어도 삭제해도 무방할 것 같습니다.

d5327f5 로 반영했습니다. 감사합니다.

2023-02-14 08:44 UTC, taek0622 commented on GiwazipClient/Cells/ProgressCell.swift
> +    override private init(frame: CGRect) {
> p2. private은 빠지는 것으로 회의되었던 것 같습니다~

직접 넣어준 부분은 아니고, 자동 완성이 저렇게 넣어줘서 미쳐 확인하지 못했네요. fa57a2d 로 반영했습니다.

2023-02-14 08:47 UTC, taek0622 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		2614F251299802BE0051EE51 /* WaveView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 2614F250299802BE0051EE51 /* WaveView.swift */; };
> p3. 파일 위치를 ASCell 위로 조정하는 게 어떨까요? 뷰의 상단부터 하단순으로 Cell 위치를 조정하면 파일을 찾기 더 수월할 것 같습니다.

8432abb 로 반영했습니다. 다만, 이렇게 변경했을 때 오히려 약간 눈에 잘 안들어오는데, abc 순으로 변경하는 것은 어떨까요?

2023-02-14 08:49 UTC, taek0622 commented on GiwazipClient/Cells/WaveView.swift
> +        shape.addLine(to: CGPoint(x: 0, y: bounds.maxY / 100 * (100 - progress)))
> p2. 읽기가.. 힘드네요.. 줄바꿈이 필요할 것 같습니다. 가능한 100자 이내에서는 줄바꿈하는 컨벤션이 있죠!

코드 자체가 좀 복잡하긴 합니다. 해당 부분 e962eb7 로 반영했습니다.

2023-02-14 14:14 UTC, JUNY0110 commented on GiwazipClient/Cells/ProgressCell.swift
> +    private let view: UIView = {
> 해당 부분은 baseView, progressView 같은 느낌보다는 Frame 자체를 잡기위해 존재하는 뷰이기 때문에 view로 잡았습니다.

view는 VC에서 흔히 사용하는 이름이라, 혼용되기 쉬울 것 같습니다. 최소 frameView정도의 이름을 부여하는 것은 어떨까요?

2023-02-14 15:01 UTC, JUNY0110 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		2614F251299802BE0051EE51 /* WaveView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 2614F250299802BE0051EE51 /* WaveView.swift */; };
> [8432abb](https://github.com/Samsamhada/Giwazip-Client-App/commit/8432abb3206fcfa9263f57492c104303af2dcea0) 로 반영했습니다. 다만, 이렇게 변경했을 때 오히려 눈에 잘 안들어오는데, abc 순으로 변경하는 것은 어떨까요?

화면이 다양하지 않아 폴더링으로 구분하는건 애매하니, 알파벳순으로라도 하면 규칙성이 생겨 보기에 낫겠네요.
현재는 화면단위로 파일을 모아두기만 했을뿐, 별다른 규칙성이 없어서 화면단위로 나눈 것처럼 보이지도 않기도 하구요.

2023-02-14 15:04 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +
> `isConverted`는 무엇을 convert 한다는 것인지 명확해 보이지 않는 것 같습니다. 문의내역인지 시공내역인지 판단한다는 느낌에서 `isWorkingView`가 조금 더 명확한 것 같네요.

뷰를 작동하고 있는지? 정도로 보였는데, workingView인지? 라는 의미였군요.
View이름이 Bool과 같이 사용하니 모호한 감이 있긴하네요. 확인했습니다

2023-02-14 19:38 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +
> > `isConverted`는 무엇을 convert 한다는 것인지 명확해 보이지 않는 것 같습니다. 문의내역인지 시공내역인지 판단한다는 느낌에서 `isWorkingView`가 조금 더 명확한 것 같네요.
> 
> 뷰를 작동하고 있는지? 정도로 보였는데, workingView인지? 라는 의미였군요. View이름이 Bool과 같이 사용하니 모호한 감이 있긴하네요. 확인했습니다

621dc8e 에서 workingView가 workView로 바뀜에 따라 isWorkView로 변수 이름이 변경되었습니다.

2023-02-14 19:41 UTC, taek0622 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		2614F251299802BE0051EE51 /* WaveView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 2614F250299802BE0051EE51 /* WaveView.swift */; };
> > [8432abb](https://github.com/Samsamhada/Giwazip-Client-App/commit/8432abb3206fcfa9263f57492c104303af2dcea0) 로 반영했습니다. 다만, 이렇게 변경했을 때 오히려 눈에 잘 안들어오는데, abc 순으로 변경하는 것은 어떨까요?
> 
> 화면이 다양하지 않아 폴더링으로 구분하는건 애매하니, 알파벳순으로라도 하면 규칙성이 생겨 보기에 낫겠네요. 현재는 화면단위로 파일을 모아두기만 했을뿐, 별다른 규칙성이 없어서 화면단위로 나눈 것처럼 보이지도 않기도 하구요.

fa0c3f0 에서 우선 셀 부분만 abc 순으로 정렬 변경했습니다. 삭제 예정인 cell은 최상단에 우선 그냥 두었습니다. 감사합니다.

2023-02-14 19:47 UTC, taek0622 commented on GiwazipClient/Cells/ProgressCell.swift
> +    private let view: UIView = {
> > 해당 부분은 baseView, progressView 같은 느낌보다는 Frame 자체를 잡기위해 존재하는 뷰이기 때문에 view로 잡았습니다.
> 
> view는 VC에서 흔히 사용하는 이름이라, 혼용되기 쉬울 것 같습니다. 최소 frameView정도의 이름을 부여하는 것은 어떨까요?

264cd61 에서 view는 categoryFrame으로 silhouette은 unselectOpacity로 변경되었습니다. 감사합니다.

2023-02-14 19:50 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +            cell.progress = Double((indexPath.item % 10 + 1) * 10)
> Q. 서버에서 Float로 받는 것으로 알고 있는데, Double로 작성한 이유가 있을까요? 어차피 서버에서 변환해준다면, 처음부터 Float로 하는 건 어떨까요?

최종적으로 필요한 타입이 CGFloat이기 때문에 535f9e8 으로 해당 부분 Double에서 CGFloat으로 변경 반영하였습니다.

2023-02-15 01:38 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +
> 
> [621dc8e](https://github.com/Samsamhada/Giwazip-Client-App/commit/621dc8e5314eaefa362e5c9f24dd17b37d620a89) [f26c3cb](https://github.com/Samsamhada/Giwazip-Client-App/commit/f26c3cbde823ab58475063341da4495c508c8b04) 에서 workingView가 workView로 바뀜에 따라 isWorkView로 변수 이름이 변경되었습니다.

확인했습니다.

2023-02-15 01:39 UTC, JUNY0110 commented on GiwazipClient/Cells/ProgressCell.swift
> +    private let view: UIView = {
> [264cd61](https://github.com/Samsamhada/Giwazip-Client-App/commit/264cd619f64c4ac25b1f7054e7b35acfe9952bc5) 에서 view는 categoryFrame으로 silhouette은 unselectOpacity로 변경되었습니다. 감사합니다.

확인했습니다.

2023-02-15 01:39 UTC, JUNY0110 commented on GiwazipClient.xcodeproj/project.pbxproj
> +		2614F251299802BE0051EE51 /* WaveView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 2614F250299802BE0051EE51 /* WaveView.swift */; };
> > > [8432abb](https://github.com/Samsamhada/Giwazip-Client-App/commit/8432abb3206fcfa9263f57492c104303af2dcea0) 로 반영했습니다. 다만, 이렇게 변경했을 때 오히려 눈에 잘 안들어오는데, abc 순으로 변경하는 것은 어떨까요?
> > 
> > 
> > 화면이 다양하지 않아 폴더링으로 구분하는건 애매하니, 알파벳순으로라도 하면 규칙성이 생겨 보기에 낫겠네요. 현재는 화면단위로 파일을 모아두기만 했을뿐, 별다른 규칙성이 없어서 화면단위로 나눈 것처럼 보이지도 않기도 하구요.
> 
> [fa0c3f0](https://github.com/Samsamhada/Giwazip-Client-App/commit/fa0c3f02c6dc52bbfcba94769f2742275cd5d4de) 에서 우선 셀 부분만 abc 순으로 정렬 변경했습니다. 삭제 예정인 빈 cell은 최상단에 우선 그냥 두었습니다. 감사합니다.

확인했습니다.

2023-02-15 01:40 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            cell.progress = Double((indexPath.item % 10 + 1) * 10)
> > Q. 서버에서 Float로 받는 것으로 알고 있는데, Double로 작성한 이유가 있을까요? 어차피 서버에서 변환해준다면, 처음부터 Float로 하는 건 어떨까요?
> 
> 최종적으로 필요한 타입이 CGFloat이기 때문에 [535f9e8](https://github.com/Samsamhada/Giwazip-Client-App/commit/535f9e857f66d7212eca0dca6c31c487354ec180) 으로 해당 부분 Double에서 CGFloat으로 변경 반영하였습니다.

확인했습니다.

2023-02-15 01:40 UTC, JUNY0110 approved these changes
빠른 반영 감사합니다^^

2023-02-15 01:41 UTC, merged