[Feature] NetworkManager(Get) + Model
Samsamhada/Giwazip-Client-App pull request #45
Opened 2023-02-19 15:08 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 네트워크 통신을 위한 모델 및 코드 추가

## Key Changes 🔥 (주요 구현/변경 사항)
- UserData Get통신을 위한 NetworkManager 추가
- Get에 사용할 Model 추가

## ToDo 📆 (남은 작업)
- [ ] Post, Put

## ScreenShot 📷 (참고 사진)
<img src="https://user-images.githubusercontent.com/98405970/219955719-965a4ebe-0e40-4fa2-b786-173ce90421cb.png" width="300">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 실행코드는 아직 반영하지 않았습니다. 필요 시 SceneDelegate에서 임의로 동작하는 코드를 임의로 작성해두었습니다.
  - 다음 PR에서는 다른 코드로 AppDelegate에 작성될 예정입니다.
- APIEnvironment는 notion 확인 후, 별도 파일 생성하셔야 합니다.
- 원래 일찍이 반영되었어야할 코드인데 처음 `RxSwift`, `NetworkManager`, `Alamofire`를 사용하니 많이 늦어졌네요.ㅠㅠ

```swift
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {

        window?.rootViewController = UIStoryboard(name: "LaunchScreen", bundle: nil).instantiateInitialViewController()
        window?.makeKeyAndVisible()
        
        NetworkManager.shared
        
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 2) {
            guard let scene = (scene as? UIWindowScene) else { return }
            self.window = UIWindow(windowScene: scene)

            let navigationController = UINavigationController()
            self.window?.rootViewController = navigationController

            let coordinator = AppCoordinator(navigationController: navigationController)
            coordinator.start()

            self.window?.makeKeyAndVisible()
        }

        guard let _ = (scene as? UIWindowScene) else { return }
    }
```

```swift
 titleName.text = NetworkManager.shared.userData?.userrooms![0].room!.name   // ViewController 사용 예
```

## Reference 🔗
[김종권 - RxSwift개념](https://ios-development.tistory.com/95)
[Github - RxSwift](https://github.com/ReactiveX/RxSwift)
[ddosang - RxSwift](https://velog.io/@ddosang/RxSwift-1-개념잡기)
[nTom - RxSwift와 Combine 코드비교](https://ntomios.tistory.com/17)
[Youable Dev - RxSwift Relay알아보기](https://youbidan-project.tistory.com/193)
[JinShine블로그 - [RxSwift] Subject와 Relay](https://jinshine.github.io/2019/01/05/RxSwift/3.Subject란/)
[BillnJoyce - Subject 와 Relay 의 기본 개념 및 특징을 살펴보자](https://joycestudios.tistory.com/88)
[나초에 체다치즈 - Subject 와 Relay](https://nacho.tistory.com/21)
[고무망치 - Subject란?](https://rhammer.tistory.com/289)
[Formagran - Subject란?](https://fomaios.tistory.com/entry/RxSwift-Subject와-Relay란)
[삼삼하다 참고자료 - RxSwift란?](https://github.com/Samsamhada/MacC-Team-Samsamhada/discussions/207)

[Github - Alamofire](https://github.com/Alamofire/Alamofire)
[Hoojeong - Alamofire사용하기](https://velog.io/@gnwjd309/iOS-Alamofire)
[지혜의 개발공부로그 - Alamofire란 무엇이고 어떻게 사용하는가?](https://www.zehye.kr/ios/2020/04/01/12iOS_alamofire/)
[후리스콜링개발 - Alamofire사용 서버통신](https://roniruny.tistory.com/141)
[HUISOO - Alamofire설치 및 사용방법](https://huisoo.tistory.com/22)
[taehoon95 - Network예제 살펴보기](https://taehoon95.tistory.com/164)

2023-02-19 17:59 UTC, taek0622 requested changes
고생하셨습니다.
Rx, Alamofire 등 어려운 내용이 많네요.
아직 코드를 봐도 온전히 이해가 가지 않아서 개인적으로 코드를 보면서 더 공부해야 될 것 같습니다.

우선 확인 가능한 부분에 리뷰 남겼습니다. 확인 부탁드려요~

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/SceneDelegate.swift
> +
p5;
요기 빈칸은 삭제해주시면 감사하겠습니다~

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/SceneDelegate.swift
> +        guard let _ = (scene as? UIWindowScene) else { return }
p2;
이미 해당 코드가 DispathQueue 내부에서 실행되고 있어서 별도로 필요하지 않을 것 같습니다.

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
p2;
해당 부분이 이미 DispatchQueue 안에 있고, 실질적으로 필요한 부분이 DispatchQueue 내부의 부분이라 이곳에서는 삭제되어도 될 것 같습니다.

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    init() {
p1;
싱글톤에서는 인스턴스가 추가로 생성되는 것을 방지하기 위해 `private init`으로 선언합니다.

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +import RxCocoa
p2;
컨벤션 중 라이브러리는 ABC 순으로 정렬하는 컨벤션이 있습니다.

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +class NetworkManager {
p4;
해당 싱글톤 클래스를 `final`로 선언하면 어떨까요?
final로 선언하면 실수로 다른 class에서 상속할 가능성을 방지해줍니다.

추가로 Swift.org 공식 문서에는 명시되어 있지 않지만,
Apple의 Swift Repository에 있는 Optimization Tips 문서의 [Advice: Use 'final' when you know the declaration does not need to be overridden](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#id17) 부분을 보시면,
final로 선언된 요소들은 직접 호출되는 반면, 그렇지 않은 요소들은 `vtable`을 통해 간접 호출되어 직접 호출되는 경우보다 느리게 작동한다고 명시되어 있습니다.

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    }
p5;
여기부터 아래 코드들은 비슷한 부분이 많아서 후에 하나로 합칠 수도 있을 것 같네요.

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/Models/Models.swift
> +    let worker: Worker
p2;
worker는 고객의 경우 nil이 되기 때문에 옵셔널 타입이 되어야할 것 같습니다.

다른 모델들의 경우 더 확인하고 싶어도, 정확한 확인이 어려워서 앞으로의 기능에 따라 변경될 것 같네요.

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +        loadRoomData(url: APIEnvironment.roomsURL + "/user/1")
p5;
아직은 전부 사용 중이진 않은 것 같은데, 먼저 사용되는 메서드들만 살려두면 어떨까요?
현재 사용되고 있지 않은 메서드들 때문에 서버에 요청이 한번에 7개씩 들어옵니다.
사용되지 않는 부분 때문에 부하가 너무 큰 것 같아요 ㅠㅠ

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +            }
p4;
해당 부분 indentation이 약간의 혼란을 야기하는 것 같습니다.
아래와 같이 변경되면 어떨까요?
```suggestion
            AF
                .request(url,
                         method: .get,
                         encoding: JSONEncoding.default,
                         headers: self.header)
                .responseData { response in
                    switch response.result {
                    case .success:
                        guard let data = response.data,
                              let statusCode = response.response?.statusCode
                        else { return }

                        let networkResult = self.judgeStatus(by: statusCode,
                                                             self.isValidUserData(data: data))
                        observer.onNext(networkResult)
                        observer.onCompleted()
                    case .failure:
                        break
                    }
```

2023-02-19 17:59 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    func requestUserData(url: String) -> Observable<NetworkResult<Any>> {
p5;
해당 부분은 현재 loadUserData, loadRoomData 같은 곳에서만 사용되고 있는 것 같은데, 해당 메서드들에서는 이 메서드의 return 값을 사용하지 않고 있습니다.
그렇다면 loadUserData 등에서 _ = 로 선언하는 것보다는 해당 메서드를 `@discardableResult`로 선언해서 사용하는 것이 어떨까요?

와일드 카드는 실제 리턴을 받아서 사용할 수 없게 만드는 트릭이지만, discardableResult는 리턴 값이 사용되지 않을 때를 위해 만든 정식 어노테이션이므로 해당 어노테이션을 사용하는 것이 더 좋을 것 같습니다.

물론, discardableResult 또한 권장 문법은 아니며, 정말 결과값이 사용되지 않는 경우에만 사용합니다.
되도록 return 값을 사용하며, discardableResult 등으로 return이 정말 사용되지 않을 때를 확실히 생각하고 사용하라고 경고하고 있긴 합니다.

2023-02-20 11:52 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    func requestUserData(url: String) -> Observable<NetworkResult<Any>> {
> p5; 해당 부분은 현재 loadUserData, loadRoomData 같은 곳에서만 사용되고 있는 것 같은데, 해당 메서드들에서는 이 메서드의 return 값을 사용하지 않고 있습니다. 그렇다면 loadUserData 등에서 _ = 로 선언하는 것보다는 해당 메서드를 `@discardableResult`로 선언해서 사용하는 것이 어떨까요?
> 
> 와일드 카드는 실제 리턴을 받아서 사용할 수 없게 만드는 트릭이지만, discardableResult는 리턴 값이 사용되지 않을 때를 위해 만든 정식 어노테이션이므로 해당 어노테이션을 사용하는 것이 더 좋을 것 같습니다.
> 
> 물론, discardableResult 또한 권장 문법은 아니며, 정말 결과값이 사용되지 않는 경우에만 사용합니다. 되도록 return 값을 사용하며, discardableResult 등으로 return이 정말 사용되지 않을 때를 확실히 생각하고 사용하라고 경고하고 있긴 합니다.

해당 RxSwift의 subscribe 메소드에 의해 발생하는 알림으로, discardableResult 사용과는 관련이 없습니다. 따라서 와일드카드를 유지했습니다.
<img width="811" alt="Screenshot 2023-02-20 at 8 51 41 PM" src="https://user-images.githubusercontent.com/98405970/220098948-234be88f-d646-45a1-804a-d7bc60eb0e7f.png">

2023-02-20 11:58 UTC, JUNY0110 commented on GiwazipClient/Models/Models.swift
> +    let worker: Worker
> p2; worker는 고객의 경우 nil이 되기 때문에 옵셔널 타입이 되어야할 것 같습니다.
> 
> 다른 모델들의 경우 더 확인하고 싶어도, 정확한 확인이 어려워서 앞으로의 기능에 따라 변경될 것 같네요.

7be3653 ~~

2023-02-20 11:59 UTC, JUNY0110 commented on GiwazipClient/SceneDelegate.swift
> +        guard let _ = (scene as? UIWindowScene) else { return }
> p2; 이미 해당 코드가 DispathQueue 내부에서 실행되고 있어서 별도로 필요하지 않을 것 같습니다.

49fead0

2023-02-20 11:59 UTC, JUNY0110 commented on GiwazipClient/SceneDelegate.swift
> +
> p5; 요기 빈칸은 삭제해주시면 감사하겠습니다~

49fead0

2023-02-20 11:59 UTC, JUNY0110 commented on GiwazipClient/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
> p2; 해당 부분이 이미 DispatchQueue 안에 있고, 실질적으로 필요한 부분이 DispatchQueue 내부의 부분이라 이곳에서는 삭제되어도 될 것 같습니다.

49fead0

2023-02-20 12:00 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +            }
> p4; 해당 부분 indentation이 약간의 혼란을 야기하는 것 같습니다. 아래와 같이 변경되면 어떨까요?

36f1287 붙여쓰는게 더 깔끔해보여서 들여쓰기를 확인 못했네요

2023-02-20 12:00 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +        loadRoomData(url: APIEnvironment.roomsURL + "/user/1")
> p5; 아직은 전부 사용 중이진 않은 것 같은데, 먼저 사용되는 메서드들만 살려두면 어떨까요? 현재 사용되고 있지 않은 메서드들 때문에 서버에 요청이 한번에 7개씩 들어옵니다. 사용되지 않는 부분 때문에 부하가 너무 큰 것 같아요 ㅠㅠ

36f1287 서버에 더 부하를 줄 수 있었는데,, 아쉽네요

2023-02-20 12:01 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    init() {
> p1; 싱글톤에서는 인스턴스가 추가로 생성되는 것을 방지하기 위해 `private init`으로 선언합니다.

36f1287 작업하다가 분실했나보네요. 확인감사합니다.

2023-02-20 12:02 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +import RxCocoa
> p3; 컨벤션 중 라이브러리는 ABC 순으로 정렬하는 컨벤션이 있습니다.

36f1287

2023-02-20 12:37 UTC, taek0622 commented on GiwazipClient/SceneDelegate.swift
> +
> > p5; 요기 빈칸은 삭제해주시면 감사하겠습니다~
> 
> [49fead0](https://github.com/Samsamhada/Giwazip-Client-App/commit/49fead0f090688bf10552f4ba235d3b894af5f2c)

확인했습니다. 리뷰 리졸브합니다.

2023-02-20 12:37 UTC, taek0622 commented on GiwazipClient/SceneDelegate.swift
> +        guard let _ = (scene as? UIWindowScene) else { return }
> > p2; 이미 해당 코드가 DispathQueue 내부에서 실행되고 있어서 별도로 필요하지 않을 것 같습니다.
> 
> [49fead0](https://github.com/Samsamhada/Giwazip-Client-App/commit/49fead0f090688bf10552f4ba235d3b894af5f2c)

확인했습니다. 리뷰 리졸브합니다.

2023-02-20 12:38 UTC, taek0622 commented on GiwazipClient/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
> > p2; 해당 부분이 이미 DispatchQueue 안에 있고, 실질적으로 필요한 부분이 DispatchQueue 내부의 부분이라 이곳에서는 삭제되어도 될 것 같습니다.
> 
> [49fead0](https://github.com/Samsamhada/Giwazip-Client-App/commit/49fead0f090688bf10552f4ba235d3b894af5f2c)

확인했습니다. 리뷰 리졸브합니다.

2023-02-20 12:38 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    init() {
> > p1; 싱글톤에서는 인스턴스가 추가로 생성되는 것을 방지하기 위해 `private init`으로 선언합니다.
> 
> [36f1287](https://github.com/Samsamhada/Giwazip-Client-App/commit/36f1287163010568c9999857ae3127a0d0a4e892) 작업하다가 분실했나보네요. 확인감사합니다.

확인했습니다. 리뷰 리졸브합니다.

2023-02-20 12:38 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +import RxCocoa
> > p3; 컨벤션 중 라이브러리는 ABC 순으로 정렬하는 컨벤션이 있습니다.
> 
> [36f1287](https://github.com/Samsamhada/Giwazip-Client-App/commit/36f1287163010568c9999857ae3127a0d0a4e892)

확인했습니다. 리뷰 리졸브합니다.

2023-02-20 12:39 UTC, taek0622 commented on GiwazipClient/Models/Models.swift
> +    let worker: Worker
> > p2; worker는 고객의 경우 nil이 되기 때문에 옵셔널 타입이 되어야할 것 같습니다.
> > 다른 모델들의 경우 더 확인하고 싶어도, 정확한 확인이 어려워서 앞으로의 기능에 따라 변경될 것 같네요.
> 
> [7be3653](https://github.com/Samsamhada/Giwazip-Client-App/commit/7be365343a88dfc8762eed20d7a512ca4f8e7c3a) ~~

확인했습니다. 리뷰 리졸브합니다.

2023-02-20 12:39 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +        loadRoomData(url: APIEnvironment.roomsURL + "/user/1")
> > p5; 아직은 전부 사용 중이진 않은 것 같은데, 먼저 사용되는 메서드들만 살려두면 어떨까요? 현재 사용되고 있지 않은 메서드들 때문에 서버에 요청이 한번에 7개씩 들어옵니다. 사용되지 않는 부분 때문에 부하가 너무 큰 것 같아요 ㅠㅠ
> 
> [36f1287](https://github.com/Samsamhada/Giwazip-Client-App/commit/36f1287163010568c9999857ae3127a0d0a4e892) 수정했습니다 ^^

확인했습니다. 이제 서버에 부하가 조금 줄겠네요. 감사합니다. 리뷰 리졸브할게요.

2023-02-20 12:41 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +            }
> > p4; 해당 부분 indentation이 약간의 혼란을 야기하는 것 같습니다. 아래와 같이 변경되면 어떨까요?
> 
> [36f1287](https://github.com/Samsamhada/Giwazip-Client-App/commit/36f1287163010568c9999857ae3127a0d0a4e892) 붙여쓰는게 더 깔끔해보여서 들여쓰기를 확인 못했네요

사실 여기 들여쓰기의 핵심은 chaining 되고 있는 responseData가 눈에 안들어와서 그 부분의 수정이 우선이었는데, 해당 부분은 수정이 안되어있네요..

2023-02-20 12:42 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    func requestUserData(url: String) -> Observable<NetworkResult<Any>> {
> > p5; 해당 부분은 현재 loadUserData, loadRoomData 같은 곳에서만 사용되고 있는 것 같은데, 해당 메서드들에서는 이 메서드의 return 값을 사용하지 않고 있습니다. 그렇다면 loadUserData 등에서 _ = 로 선언하는 것보다는 해당 메서드를 `@discardableResult`로 선언해서 사용하는 것이 어떨까요?
> > 와일드 카드는 실제 리턴을 받아서 사용할 수 없게 만드는 트릭이지만, discardableResult는 리턴 값이 사용되지 않을 때를 위해 만든 정식 어노테이션이므로 해당 어노테이션을 사용하는 것이 더 좋을 것 같습니다.
> > 물론, discardableResult 또한 권장 문법은 아니며, 정말 결과값이 사용되지 않는 경우에만 사용합니다. 되도록 return 값을 사용하며, discardableResult 등으로 return이 정말 사용되지 않을 때를 확실히 생각하고 사용하라고 경고하고 있긴 합니다.
> 
> 해당 RxSwift의 subscribe 메소드에 의해 발생하는 알림으로, discardableResult 사용과는 관련이 없습니다. 따라서 와일드카드를 유지했습니다. <img alt="Screenshot 2023-02-20 at 8 51 41 PM" width="811" src="https://user-images.githubusercontent.com/98405970/220098948-234be88f-d646-45a1-804a-d7bc60eb0e7f.png">

네, 저도 코멘트를 달고나서 바로 확인하긴 했습니다만, 그냥 DescardableResult 자체에 대해 알면 좋을것 같아서 코멘트 그냥 유지해뒀었습니다. 우선 불필요한 코멘트이므로 리졸브하겠습니다~

2023-02-20 15:36 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +            }
> > > p4; 해당 부분 indentation이 약간의 혼란을 야기하는 것 같습니다. 아래와 같이 변경되면 어떨까요?
> > 
> > 
> > [36f1287](https://github.com/Samsamhada/Giwazip-Client-App/commit/36f1287163010568c9999857ae3127a0d0a4e892) 붙여쓰는게 더 깔끔해보여서 들여쓰기를 확인 못했네요
> 
> 사실 여기 들여쓰기의 핵심은 chaining 되고 있는 responseData가 눈에 안들어와서 그 부분의 수정이 우선이었는데, 해당 부분은 수정이 안되어있네요..

77aad40 인덴트가 컨벤션을 지키지 않아 수정하지 않았으나, 가독성면에서는 더 좋아보여 수정했습니다.

2023-02-20 15:36 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    }
> p5; 여기부터 아래 코드들은 비슷한 부분이 많아서 후에 하나로 합칠 수도 있을 것 같네요.
> 
> 시도해본 결과 합치는데 성공했습니다. 제너릭을 적극 사용해서 시도해보시면 좋을 것 같아요.

27215b3 제네릭 맛있네요..

2023-02-20 15:37 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +class NetworkManager {
> p4; 해당 싱글톤 클래스를 `final`로 선언하면 어떨까요? final로 선언하면 실수로 다른 class에서 상속할 가능성을 방지해줍니다.
> 
> 추가로 Swift.org 공식 문서에는 명시되어 있지 않지만, Apple의 Swift Repository에 있는 Optimization Tips 문서의 [Advice: Use 'final' when you know the declaration does not need to be overridden](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#id17) 부분을 보시면, final로 선언된 요소들은 직접 호출되는 반면, 그렇지 않은 요소들은 `vtable`을 통해 간접 호출되어 직접 호출되는 경우보다 느리게 작동한다고 명시되어 있습니다.

27215b3

2023-02-20 15:53 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +class NetworkManager {
> > p4; 해당 싱글톤 클래스를 `final`로 선언하면 어떨까요? final로 선언하면 실수로 다른 class에서 상속할 가능성을 방지해줍니다.
> > 추가로 Swift.org 공식 문서에는 명시되어 있지 않지만, Apple의 Swift Repository에 있는 Optimization Tips 문서의 [Advice: Use 'final' when you know the declaration does not need to be overridden](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#id17) 부분을 보시면, final로 선언된 요소들은 직접 호출되는 반면, 그렇지 않은 요소들은 `vtable`을 통해 간접 호출되어 직접 호출되는 경우보다 느리게 작동한다고 명시되어 있습니다.
> 
> [27215b3](https://github.com/Samsamhada/Giwazip-Client-App/commit/27215b304321ff4e62474cbfed22ae28323d9d84)

확인했습니다. 리뷰 리졸브합니다.

2023-02-20 15:53 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +            }
> > > > p4; 해당 부분 indentation이 약간의 혼란을 야기하는 것 같습니다. 아래와 같이 변경되면 어떨까요?
> > > 
> > > 
> > > [36f1287](https://github.com/Samsamhada/Giwazip-Client-App/commit/36f1287163010568c9999857ae3127a0d0a4e892) 붙여쓰는게 더 깔끔해보여서 들여쓰기를 확인 못했네요
> > 
> > 
> > 사실 여기 들여쓰기의 핵심은 chaining 되고 있는 responseData가 눈에 안들어와서 그 부분의 수정이 우선이었는데, 해당 부분은 수정이 안되어있네요..
> 
> [77aad40](https://github.com/Samsamhada/Giwazip-Client-App/commit/77aad4073073afcfdf937b3c49a30937e1cfe262) 인덴트가 컨벤션을 지키지 않아 수정하지 않았으나, 가독성면에서는 더 좋아보여 수정했습니다.

확인했습니다. 리뷰 리졸브합니다~

2023-02-20 15:54 UTC, ikanic commented on GiwazipClient/ViewModels/NetworkManager.swift
> +    }
> > p5; 여기부터 아래 코드들은 비슷한 부분이 많아서 후에 하나로 합칠 수도 있을 것 같네요.
> > 시도해본 결과 합치는데 성공했습니다. 제너릭을 적극 사용해서 시도해보시면 좋을 것 같아요.
> 
> [27215b3](https://github.com/Samsamhada/Giwazip-Client-App/commit/27215b304321ff4e62474cbfed22ae28323d9d84) 제네릭 맛있네요..

WhooWhoo.. 제네릭 참 맛있죠. 저도 참 좋아하는데요 ㅎㅎ 제가 한번 리졸브 해보겠습니다~

2023-02-20 16:04 UTC, taek0622 approved these changes
고생하셨습니다.
Rx에 Alamofire에 NetworkManager도 처음 해보는 것 투성이라 진짜 고생 많으셨을텐데, 열심히 해주셔서 감사해요.
제안 사항 하나 리뷰 남겼습니다.
추가로, gitignore에는 APIEnvironment가 있는데, 실제로 APIEnvironment 파일을 생성하면 ignore가 먹히지 않네요.
그리고, APIEnvrionment 자체는 올리지 않아야하지만, pbx에는 있어야하는데 pbx에도 APIEnvironment 부분이 빠진 것 같습니다.

2023-02-20 16:04 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +}
p5;
이 부분은 NetworkManager 안에서만 사용되는 것 같은데, private이 되어도 될 것 같네요.

2023-02-21 03:04 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +}
> p5;
> 이 부분은 NetworkManager 안에서만 사용되는 것 같은데, private이 되어도 될 것 같네요.

cd336e9

2023-02-21 03:05 UTC, merged