Fix/47 progress cell bug
Samsamhada/Giwazip-Client-App pull request #50
Opened 2023-02-21 03:19 UTC by taek0622

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 뷰를 아래로 스크롤 한 뒤 위로 돌아오면 선택한 카테고리가 첫번째 카테고리로 돌아가는 문제를 해결하기 위함
- 게시물을 클릭하면 선택된 카테고리가 취소되는 문제를 해결하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- select item을 section당 한개 선택 가능하도록 변경
- 처음 뷰에 들어왔을 때만, 첫번째 아이템이 선택되어 있도록 변경

## ToDo 📆 (남은 작업)
- [ ] 없음

## ScreenShot 📷 (참고 사진)
<img src="https://user-images.githubusercontent.com/81027256/220218436-a53ca649-fb64-4187-9634-d050c3d7eb76.gif">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 카테고리 부분에서 문제가 있던 것을 수정했습니다.
- 생각보다 어려운 코드는 아니었는데, 약간의 트릭 코드인 것 같아서 썩 맘에 드는 편은 아니네요..
- 짧은 코드이니 가볍게 살펴보셔도 좋습니다만, 잘못된 동작이 없나 잘 확인 부탁드려요.

## Reference 🔗
- [stackoverflow - iOS UICollectionView cell selection per section](https://stackoverflow.com/questions/15372940/ios-uicollectionview-cell-selection-per-section)

## Close Issues 🔒 (닫을 Issue)
- Close #47.

2023-02-21 17:43 UTC, JUNY0110 requested changes
셀 취소 기능은 없었던 것 같은데, 셀이 취소가 되네요. 확인 부탁드립니다.

2023-02-21 17:43 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +        historyCollectionView.allowsMultipleSelection = true
p1.
multipleSelection을 true로 한 이유가 있을까요?
현재 같은 category를 2번 클릭하면 셀 선택이 취소되고 있습니다. 의도한 동작이 맞을까요?
해당 코드를 지우면 셀 취소문제는 사라지는 것으로 확인되었습니다.

2023-02-21 18:14 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +        historyCollectionView.allowsMultipleSelection = true
> p1. multipleSelection을 true로 한 이유가 있을까요? 현재 같은 category를 2번 클릭하면 셀 선택이 취소되고 있습니다. 의도한 동작이 맞을까요? 해당 코드를 지우면 셀 취소문제는 사라지는 것으로 확인되었습니다.

multiSelection을 true로 한 이유는 게시물이 선택되었을 때, 카테고리가 선택 취소되지 않게하기 위함입니다.
다만, 재클릭시 취소 동작은 미처 확인하지 못했네요. 해당 부분 해결을 위한 코드를 생각해보겠습니다.

2023-02-22 15:09 UTC, JUNY0110 reviewed
의견입니당

2023-02-22 15:09 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }
multiSelection이 있기에 선택취소가 되는 것 같습니다.
단일 선택에서 값만 변하는 방법이어야 할 것 같은데, 잘 떠오르진 않네요 ㅠㅠ

2023-02-22 17:55 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }
> multiSelection이 있기에 선택취소가 되는 것 같습니다. 단일 선택에서 값만 변하는 방법이어야 할 것 같은데, 잘 떠오르진 않네요 ㅠㅠ

multiSelection 유지하면서 선택 취소만 되지 않게 9c52fb8 에서 수정하여 반영 했습니다.

2023-03-01 04:00 UTC, JUNY0110 approved these changes
고생하셨습니다:)

2023-03-01 04:01 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    }
> multiSelection 유지하면서 선택 취소만 되지 않게 [9c52fb8](https://github.com/Samsamhada/Giwazip-Client-App/commit/9c52fb84369af149c2df7756aeb04eff69b15bd4) 에서 추가하여 반영 했습니다. 해당 부분 if문이 한 줄에 100자를 넘어가지만, 줄을 나누는 것 보다 한 줄이 가독성이 더 나아 나누지 않았습니다.

확인했습니다.

2023-03-01 04:39 UTC, merged