[Design] SegmentViewController 구분선 및 PostDateHeader 점선 추가
Samsamhada/Giwazip-Client-App pull request #59
Opened 2023-03-05 15:29 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- SegmentViewController의 SegmentedControl과 Cell 사이 구분선을 추가하기 위함
- PostDateHeader의 선을 점선으로 변경하기 위함.

## Key Changes 🔥 (주요 구현/변경 사항)
- SegmentViewController 구분선 추가
- LineDashPattern Extension추가

## ToDo 📆 (남은 작업)
- [ ] 없음

## ScreenShot 📷 (참고 사진)
<img src="https://user-images.githubusercontent.com/98405970/222969683-3dca007a-32ca-4060-911e-07505123ce92.png" width="300">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- LineDashPattern Extension은 사실 2회 사용이며, postHeaderCell에서만 사용되기에 extension으로 빠지지 않아도 무관합니다. 
- Cell에 내부에 보이지 않아도 되는 코드를 별도로 빼기 위해 extension으로 두었으나, 별도로 빼지 않는 것이 낫다하면 PostDateHeader 내부로 옮기겠습니다.
- 오랜만의 뷰 작업이라 조금 헷갈리긴 하네요. 수정사항이 있으면 알려주시면 감사하겠습니다.

## Reference 🔗
[Apple공식문서 - LineDashPattern](https://developer.apple.com/documentation/quartzcore/cashapelayer/1521921-linedashpattern#2825198)

## Close Issues 🔒 (닫을 Issue)
Close #58.

2023-03-05 16:11 UTC, taek0622 requested changes
고생하셨습니다.
꽤 오랜만에 뷰 작업이셨는데 빠르게 처리해주셔서 감사합니다.
일부 코멘트 남겼으니 확인 부탁드려요~

2023-03-05 16:11 UTC, ikanic commented on GiwazipClient/Extensions+/LineDashPattern.swift
> +        shapeLayer.fillColor = UIColor.red.cgColor
p2;
이 부분은 점선을 만드는데 불필요한 부분인 것 같습니다.

2023-03-05 16:11 UTC, ikanic commented on GiwazipClient/Cells/PostDateHeader.swift
> +        $0.layer.addSublayer(lineDashPattern(start: UIScreen.main.bounds.width / 3, end: 0))
p4;
rightDashLine과 다르게 left는 start, end가 반대로 되어있네요. 이 부분도 같게 맞춰주면 읽기 좋을 것 같습니다.

이와 별도로 addSublayer가 전체 뷰에 영향을 줘서 최대한 빼는 방향으로 바꿔보고 싶었는데, 잘 안되네요. 아쉽게도 이 부분은 그냥 유지해야할 것 같습니다.

2023-03-06 03:45 UTC, JUNY0110 commented on GiwazipClient/Cells/PostDateHeader.swift
> +        $0.layer.addSublayer(lineDashPattern(start: UIScreen.main.bounds.width / 3, end: 0))
> p4; rightDashLine과 다르게 left는 start, end가 반대로 되어있네요. 이 부분도 같게 맞춰주면 읽기 좋을 것 같습니다.
> 
> 이와 별도로 addSublayer가 전체 뷰에 영향을 줘서 최대한 빼는 방향으로 바꿔보고 싶었는데, 잘 안되네요. 아쉽게도 이 부분은 그냥 유지해야할 것 같습니다.

해당부분은 날짜를 중심으로 좌우로 점선이 뻗어나가게 하기 위함입니다.
기기에 따라 점선이 전부 보여지기도 하고, 일부 점선은 잘려보이는 경우가 있는데,
점선이 잘리더라도 사용자가 확인하는 날짜 옆이 아닌, 
화면 끝부분에서 잘리는 것이 사용자에게 더 자연스러울 것이라 판단했습니다.

2023-03-06 03:47 UTC, JUNY0110 commented on GiwazipClient/Extensions+/LineDashPattern.swift
> +        shapeLayer.fillColor = UIColor.red.cgColor
> p2;
> 이 부분은 점선을 만드는데 불필요한 부분인 것 같습니다.

5ee35ea 테스트하다가 깜빡했네요. 확인 감사합니다.

2023-03-06 05:33 UTC, taek0622 commented on GiwazipClient/Extensions+/LineDashPattern.swift
> +        shapeLayer.fillColor = UIColor.red.cgColor
> > p2;
> > 이 부분은 점선을 만드는데 불필요한 부분인 것 같습니다.
> 
> [5ee35ea](https://github.com/Samsamhada/Giwazip-Client-App/commit/5ee35ea2a79f3ffe904acbc6df18a6703a9ae52a) 테스트하다가 깜빡했네요. 확인 감사합니다.

확인했습니다. 리뷰 리졸브합니다.

2023-03-06 05:33 UTC, taek0622 commented on GiwazipClient/Cells/PostDateHeader.swift
> +        $0.layer.addSublayer(lineDashPattern(start: UIScreen.main.bounds.width / 3, end: 0))
> > p4; rightDashLine과 다르게 left는 start, end가 반대로 되어있네요. 이 부분도 같게 맞춰주면 읽기 좋을 것 같습니다.
> > 이와 별도로 addSublayer가 전체 뷰에 영향을 줘서 최대한 빼는 방향으로 바꿔보고 싶었는데, 잘 안되네요. 아쉽게도 이 부분은 그냥 유지해야할 것 같습니다.
> 
> 해당부분은 날짜를 중심으로 좌우로 점선이 뻗어나가게 하기 위함입니다. 기기에 따라 점선이 전부 보여지기도 하고, 일부 점선은 잘려보이는 경우가 있는데, 점선이 잘리더라도 사용자가 확인하는 날짜 옆이 아닌, 화면 끝부분에서 잘리는 것이 사용자에게 더 자연스러울 것이라 판단했습니다.

회의에서 확인했습니다. 리뷰 리졸브합니다.

2023-03-06 05:35 UTC, taek0622 approved these changes
고생하셨습니다.
오랜만에 뷰 작업인데도 빠른 작업 감사해요~

2023-03-06 05:46 UTC, merged