[Design] 공지사항 뷰 추가
Samsamhada/Giwazip-Client-App pull request #60
Opened 2023-03-05 15:32 UTC by taek0622

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 공지사항을 보여주기 위한 뷰를 추가하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- 공지사항을 보여주는 NoticeViwController 추가
- 전체 뷰를 UICollectionViewController 사용해 구현

## ToDo 📆 (남은 작업)
- [ ] 없음

## ScreenShot 📷 (참고 사진)
<img src="https://user-images.githubusercontent.com/81027256/222969911-f414b136-be0e-42b2-95bf-e4716449e69d.gif" width="400">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 공지사항 뷰가 추가되었습니다.
- 간단한 뷰이니 가볍게 봐주셔도 좋습니다.
- 테스트를 위해서는 SceneDelegate의 scene function이 아래와 같이 변경되야 합니다.
```swift
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    guard let scene = (scene as? UIWindowScene) else { return }
    self.window = UIWindow(windowScene: scene)

    let navigationController = UINavigationController(rootViewController: NoticeViewController())
    self.window?.rootViewController = navigationController

    self.window?.makeKeyAndVisible()
}
```

## Reference 🔗
- [Swift Senpai - Building an Expandable List Using UICollectionView: Part 1](https://swiftsenpai.com/development/collectionview-expandable-list-part1/)

## Close Issues 🔒 (닫을 Issue)
- Close #56.

2023-03-06 04:31 UTC, JUNY0110 requested changes
고생하셨습니다. 여러 시행착오 끝에 DiffableCollectionView에 상당히 익숙해지신 것 같네요.
회의로 결정된 사항과 몇가지 질문을 남겼습니다.

2023-03-06 04:31 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +        var sectionSnapShot = NSDiffableDataSourceSectionSnapshot<NoticeItem>()
p3.
snapshot은 소문자인데, sectionSnapShot으로 대문자인 것이 통일감이 아쉽네요 sectionSnapshot을 작성하려고 하셨던 것 같습니다.

2023-03-06 04:31 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +    ]
p2.
접근지정자가 없고, 인덴트가 지켜지지 않고 있습니다.

Q.
author는 권한 이라는 의미의 authorization일까요? 아니면, 저자 라는 의미의 author일까요?
저자라는 의미라면, 작성자라는 의미의 writer, 또는 관리자라는 의미의 administrator 등이 어떨까요?

Q.
추후 서버데이터로 전환되는 부분인 것으로 보입니다. 서버에서 배열을 가져온 뒤, for문을 reversed하는 방식으로 구현되는것이 맞을까요?

서버에서 역순으로 저장하는 건 어려울까 라는 질문도 하려 했는데, 가능성여부와 공수뿐만 아니라 그다지 효율적이지 못한 것 같군요

2023-03-06 04:31 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +        content.secondaryTextProperties.color = .gray
날짜가 상단, 공지사항 타이틀이 하단으로 구성하기로 회의하여, 치매방지로 남겨둡니다:)

2023-03-06 04:31 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +        cell.accessories = [.outlineDisclosure(options: headerDisclosureOption)]
파란색 화살표가 가능한지 체크 부탁드립니다~

2023-03-06 04:31 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +        dataSource.apply(sectionSnapShot, to: .noticeList, animatingDifferences: true)
Q.
dataSource.apply가 위, 아래에서 각각 사용 중인데, 일부러 snapshot에 대한 부분과 sectionSnapshot이 작성된 부분으로 나눈 것일까요?

2023-03-06 04:35 UTC, taek0622 commented on GiwazipClient/Views/NoticeViewController.swift
> +    ]
> p2. 접근지정자가 없고, 인덴트가 지켜지지 않고 있습니다.
> 
> Q. author는 권한 이라는 의미의 authorization일까요? 아니면, 저자 라는 의미의 author일까요? 저자라는 의미라면, 작성자라는 의미의 writer, 또는 관리자라는 의미의 administrator 등이 어떨까요?
> 
> Q. 추후 서버데이터로 전환되는 부분인 것으로 보입니다. 서버에서 배열을 가져온 뒤, for문을 reversed하는 방식으로 구현되는것이 맞을까요?
> 
> 서버에서 역순으로 저장하는 건 어려울까 라는 질문도 하려 했는데, 가능성여부와 공수뿐만 아니라 그다지 효율적이지 못한 것 같군요

해당 부분은 접근지정자를 일부러 뺀것이 맞습니다.
현재 들어가 있는 것이 테스트 데이터이기도 하고, 실제로 서버에서 데이터를 가져오더라도 해당 변수에 집어 넣어야하기 때문에 외부에서 접근이 필요할 것 같습니다.

A.
author는 저자라는 의미입니다. 이미 서버가 author로 되어있어 통일했습니다.

A.
해당 부분은 서버 배열을 reverse하는 부분이 맞습니다.

2023-03-06 04:36 UTC, taek0622 commented on GiwazipClient/Views/NoticeViewController.swift
> +        content.secondaryTextProperties.color = .gray
> 날짜가 상단, 공지사항 타이틀이 하단으로 구성하기로 회의하여, 치매방지로 남겨둡니다:)

나이가 몇살인데 벌써 치매라뇨.. 너무하시네..

2023-03-06 04:36 UTC, taek0622 commented on GiwazipClient/Views/NoticeViewController.swift
> +        dataSource.apply(sectionSnapShot, to: .noticeList, animatingDifferences: true)
> Q. dataSource.apply가 위, 아래에서 각각 사용 중인데, 일부러 snapshot에 대한 부분과 sectionSnapshot이 작성된 부분으로 나눈 것일까요?

네 순서적으로 snapshot이 먼저 apply이 되어야만 그 다음 로직들이 가능하기 때문에 의도적으로 나눠논 것이 맞습니다.

2023-03-06 04:41 UTC, taek0622 commented on GiwazipClient/Views/NoticeViewController.swift
> +        var sectionSnapShot = NSDiffableDataSourceSectionSnapshot<NoticeItem>()
> p3. snapshot은 소문자인데, sectionSnapShot으로 대문자인 것이 통일감이 아쉽네요 sectionSnapshot을 작성하려고 하셨던 것 같습니다.

그렇네요. 확인 감사합니다. 해당 부분 28c9e1b6 으로 반영했습니다.

2023-03-06 04:57 UTC, taek0622 commented on GiwazipClient/Views/NoticeViewController.swift
> +        content.secondaryTextProperties.color = .gray
> 날짜가 상단, 공지사항 타이틀이 하단으로 구성하기로 회의하여, 치매방지로 남겨둡니다:)

해당 부분 65b40862 로 반영했습니다.

2023-03-06 04:58 UTC, taek0622 commented on GiwazipClient/Views/NoticeViewController.swift
> +        cell.accessories = [.outlineDisclosure(options: headerDisclosureOption)]
> 파란색 화살표가 가능한지 체크 부탁드립니다~

변경이 가능해서 검정색으로 임의 변경하여 51285a30 으로 반영했습니다.

2023-03-07 13:39 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +        dataSource.apply(sectionSnapShot, to: .noticeList, animatingDifferences: true)
> > Q. dataSource.apply가 위, 아래에서 각각 사용 중인데, 일부러 snapshot에 대한 부분과 sectionSnapshot이 작성된 부분으로 나눈 것일까요?
> 
> 네 순서적으로 snapshot이 먼저 apply이 되어야만 그 다음 로직들이 가능하기 때문에 의도적으로 나눠논 것이 맞습니다. 본래 리팩토링을 염두해두고 일부러 나눠놓은 것이 맞긴 합니다만, 아직 적용되지 않은 상황이므로 [7662796](https://github.com/Samsamhada/Giwazip-Client-App/commit/7662796cd49709df597c9f2ced7f83c7d513e07d) 으로 한 곳으로 몰아 놓는 것 반영했습니다.

확인했습니다. 리졸브합니다.

2023-03-07 13:40 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +        cell.accessories = [.outlineDisclosure(options: headerDisclosureOption)]
> 변경이 가능해서 검정색으로 임의 변경하여 [51285a3](https://github.com/Samsamhada/Giwazip-Client-App/commit/51285a307c5845fcbf5057b19082a6163bee4f98) 으로 반영했습니다.

생각보다 더 간단했군요. 확인했습니다.

2023-03-07 13:43 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +        var sectionSnapShot = NSDiffableDataSourceSectionSnapshot<NoticeItem>()
> 그렇네요. 확인 감사합니다. 해당 부분 [28c9e1b](https://github.com/Samsamhada/Giwazip-Client-App/commit/28c9e1b643c0f9845be76b8eff2a19e598a2b955) 으로 반영했습니다.

확인했습니다. 리졸브합니다.

2023-03-07 13:53 UTC, JUNY0110 approved these changes
고생하셨습니다. 그냥 어프루브하기 아쉬워서 가볍게 질문 하나 남겼습니다:) 확인부탁드립니다

2023-03-07 13:53 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +    ]
테스트가 굉장히 시끌시끌하군요. 박제시켜두겠습니다.:)

2023-03-07 13:53 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +    }
case가 하나뿐인데, 혹시 enum없이 단독으로 사용하는 방법은 없을까요?

2023-03-07 13:53 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +        content.secondaryTextProperties.color = .gray
> 해당 부분 [65b4086](https://github.com/Samsamhada/Giwazip-Client-App/commit/65b408627d81730c3ae59a98242c1d56ce87e59f) 로 반영했습니다. ~또한, 내용 부분도 회의 때 말한 것 처럼 변경하기 위해 새 셀을 추가했습니다. 해당 부분 [b2665a3](https://github.com/Samsamhada/Giwazip-Client-App/commit/b2665a3c1c6746d3e5352a46157af315049dbb35) 에서 반영되었으며, 이에 따라 스크린샷도 변경되었으니 확인해주시면 감사하겠습니다.~ 상의를 통해 닉네임이 빠지기로 하여 새 셀은 다시 삭제되었고, 해당 부분은 [7b3114a](https://github.com/Samsamhada/Giwazip-Client-App/commit/7b3114a8f384b774217c9a86253fc259e280c904) 를 통해 반영되었습니다. 스크린샷도 재확인 부탁드립니다.

확인했습니다. 리졸브합니다.

2023-03-07 13:53 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +    ]
> 해당 부분은 접근지정자를 일부러 뺀것이 맞습니다. 현재 들어가 있는 것이 테스트 데이터이기도 하고, 실제로 서버에서 데이터를 가져오더라도 해당 변수에 집어 넣어야하기 때문에 외부에서 접근이 필요할 것 같습니다. 인덴트는 struct가 수정되면서 반영되지 않은 것 같네요. 해당 부분 [b4ce537](https://github.com/Samsamhada/Giwazip-Client-App/commit/b4ce53710536fd9ebcf9d90013b5519d336a7955) 로 반영했습니다. 추가로 해당 부분이 서버에 맞는 데이터를 가져오도록 변경됨에 따라 [18bbab6](https://github.com/Samsamhada/Giwazip-Client-App/commit/18bbab6dac120d27dbeb897d5acd05821e453074) 에서 다시 한번 수정되었습니다. 추가로 [7b3114a](https://github.com/Samsamhada/Giwazip-Client-App/commit/7b3114a8f384b774217c9a86253fc259e280c904) 에서 구조가 한번 더 수정되었습니다. noticeItems는 아마 이 뷰에서 완전 삭제되고 NetworkManager에서 처리하도록 변경될 것 같습니다.
> 
> A. author는 저자라는 의미입니다. 이미 서버가 author로 되어있어 통일했습니다. ~서버에서 데이터를 따와야하는 관계로 해당 부분은 [8b5531b](https://github.com/Samsamhada/Giwazip-Client-App/commit/8b5531ba30dff3aa71bedf2eb530c5ca24793ceb) 와 [18bbab6](https://github.com/Samsamhada/Giwazip-Client-App/commit/18bbab6dac120d27dbeb897d5acd05821e453074) 에서 `admin.name`으로 변경되었습니다.~ 상의를 통해 닉네임을 빼기로 결정해서 [7b3114a](https://github.com/Samsamhada/Giwazip-Client-App/commit/7b3114a8f384b774217c9a86253fc259e280c904) 에서 최종 반영되었습니다.
> 
> A. 해당 부분은 서버 배열을 reverse하는 부분이 맞습니다. 서버에서 보내줄 때, 배열 자체를 id 역순으로 보내주는 방법이 있긴 합니다만, 이 경우 조회시 무조건 역순으로만 나오기 때문에 논의가 필요해 보입니다.

확인했습니다.

2023-03-07 13:59 UTC, taek0622 commented on GiwazipClient/Views/NoticeViewController.swift
> +    }
> case가 하나뿐인데, 혹시 enum없이 단독으로 사용하는 방법은 없을까요?

enum 없이 `Hashable`한 타입이라면 무엇이든 집어 넣는 것이 가능합니다.
예제에서는 enum을 사용하고 있으며, 그 외에는 Int나 String 정도를 넣어볼 만 할 것 같습니다만, Int나 String이라고 하더라도 Section 부분에는 반드시 단일 값이 아닌 배열이 들어가야하며, 오히려 이 경우에 하드 코딩으로 인한 휴먼 에러를 발생시킬 가능성이 있다고 판단해서 enum으로 사용했습니다.

2023-03-07 14:00 UTC, taek0622 commented on GiwazipClient/Views/NoticeViewController.swift
> +    ]
> 테스트가 굉장히 시끌시끌하군요. 박제시켜두겠습니다.:)

줄 수를 여러줄 쓰려고 하다보니 상당히 시끌시끌해졌네요. 후후

2023-03-07 14:03 UTC, merged

2023-03-07 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/NoticeViewController.swift
> +    }
> > case가 하나뿐인데, 혹시 enum없이 단독으로 사용하는 방법은 없을까요?
> 
> enum 없이 `Hashable`한 타입이라면 무엇이든 집어 넣는 것이 가능합니다. 예제에서는 enum을 사용하고 있으며, 그 외에는 Int나 String 정도를 넣어볼 만 할 것 같습니다만, Int나 String이라고 하더라도 Section 부분에는 반드시 단일 값이 아닌 배열이 들어가야하며, 오히려 이 경우에 하드 코딩으로 인한 휴먼 에러를 발생시킬 가능성이 있다고 판단해서 enum으로 사용했습니다.

확인했습니다~