[Feature] 히스토리 뷰 데이터 연동
Samsamhada/Giwazip-Client-App pull request #70
Opened 2023-03-14 15:54 UTC by taek0622

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- 선택한 카테고리의 게시물을 보여주기 위함
- 게시물을 보기 위해 스크롤을 위 아래로 스크롤시 카테고리가 다시 보여지게 되는 순간 카테고리의 진행률이 마음대로 바뀌는 문제를 해결하기 위함
- 카테고리 및 AS 부분에 자연스럽게 사라지고 생기는 애니메이션을 추가하기 위함
- 게시물에 데이터를 연동하기 위함
- 방 정보를 가져오기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- HistoryViewController 전체 구조 변경 (indexPath 기반이었던 기존 CollectionView에서 Modern CollectionView로 변경 및 Category와 Post를 위한 CollectionView 분리)
- 데이터 연동
- 카테고리 및 ASView 애니메이션 추가
- 방 정보 연동

## ToDo 📆 (남은 작업)
- [ ] 공통 뷰 UIComponent로 빼기

## ScreenShot 📷 (참고 사진)
<img src="https://user-images.githubusercontent.com/81027256/225052438-7df46341-42b0-40a4-978a-b50b0eabaefa.gif" width="400">

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- 기능 추가와 문제 해결을 위해 너무 많은 시간이 소요되었네요.
- 지난 주 대면으로 함께 고민한 내용 덕분에 그나마 이 정도 시간으로 마무리할 수 있었던 것 같습니다.
- collectionView 부분은 전체적으로 구조가 전부 변경되어 주의깊게 확인 부탁드립니다.
- 깃허브 오류로 아예 새 브랜치를 팠습니다. 도중에 유실된 코드가 있을 우려가 있으니, 동작 확인 부탁드립니다.

## Reference 🔗
- 없음

## Close Issues 🔒 (닫을 Issue)
- Close #38.
- Close #62.
- Close #67.
- Close #69.

2023-03-16 15:23 UTC, JUNY0110 requested changes
내용이 많아 HistoryViewController는 아직 리뷰가 끝나지 않았습니다.
그 외 다른 내용을 먼저 올렸습니다.
고생하셨습니다

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Supports/BaseViewController.swift
> +    }
p3.
baseViewController에 놓은 이유가 있을까요?
baseViewController를 만든 이유는 VC에서 불필요한 코드 재작성을 줄이기 위함이지만,
상속에서는 불필요한 상속을 줄이는 것도 중요한데, 일부에서만 사용되는 함수가 상속된다면, 사용하지 않는 함수가 상속되는 VC들이 생겨 불필요한 상속이 되는 것 같습니다.

그러니 extension에 작성되는게 낫지않을까요?
아니면 HistoryViewController와 SegmentViewController는 연결되어있어서 HistoryViewController에서 생성하고, 불러올 수도 있을 것 같네요. 하지만 VC를 가볍게 하기 위함이라면 빼는게 나을 것 같습니다.

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/UIComponents/ASView.swift
> +    private let asDateContainer = UIView()
AS보다 as처럼 보이긴하네요..

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +        }
Q.
상단 카테고리를 2회이상 클릭했을 때에도 print가 되고 있는데, 어떤 기능을 고려하고 else로 상단 카테고리와 게시물을 묶어둔걸까요?

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/UIComponents/ASView.swift
> +    }(UILabel())
p5.
아마 기존에 사용하던 네이밍을 그대로 사용하신 것 같지만,
remain은 동사의미의 어휘인데, view 이름으로 사용되는 것은 부적절해보입니다.
remained처럼 과거형을 사용하는게 어떨까요?
동의하신다면, 함수를 제외한 변수, 상수. 클래스, 구조체는 명사형으로 해야한다는 내용을 컨벤션에 추가하면 좋을 것 같습니다.

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +                print("디코딩 에러가 발생했습니다. 디코딩 하려는 모델과, API 명세를 다시 확인해주세요.")
p3
디코딩에러에 대한 별도의 동작이 있을까요?
따로 있어서 임시로 남겨둔 것이 아니라면 TextLitieral에 선언 후, 가져오는 것이 나을 것 같습니다.

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +        loadOrCreateData(url: APIEnvironment.roomsURL + "/category-post/1", type: Room.self) { data in
확인했습니다.

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +    private let networkManager = NetworkManager.shared
Q.
기존에는 viewModel이라는 상수명으로 선언했는데, networkManager라는 이름을 사용하셨기에 
이후 networkManager로 통일되는 것인지, 습관적으로 작성한 상수명인지 궁금하네요.

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +        $0.text = "23.01.10~23.03.15"
Q.
딱히 영향은 없을 것 같은데, 수정된 이유가 있을까요?

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
>      }
p1.
날짜 계산에 약간 오류가 있는 것 같습니다.
asDateText는 마감일
asDate는 미국시간 15시
interval은 미국시간 - 현재날짜
days는 interval을 일수로 계산한 값으로,
days가 한국시간 기준으로 나타나지 않고 있는 것 같네요.
한국시 기준으로 23년 3월 16일(오늘)부터 24년 2월 6일까지 계산시 327일이 되어야 합니다.

[일수 계산 사이트](https://kr.calc-date.com/index.php)입니다.

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                let itemSize = NSCollectionLayoutSize(widthDimension: .absolute(self.screenWidth/6), heightDimension: .absolute(self.screenWidth/6))
p5.
컨벤션은 없었지만, 다른 코드와의 통일성을 위해 `self.screenWidth/6`의 나누기(/) 및 기타 수식의 좌우를 한칸씩 띄어주는 게 어떨까요?

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
>      }(UILabel())
Q.
만약 titleName을
```swift
    private lazy var titleName: UILabel = {
        $0.text = networkManager.roomData?.name
       ...
        return $0
    }(UILabel())
```
이처럼 하면 어떻게 될까요? 일단 정상적으로 출력되고 있는데, 어차피 네트워크 에러 시 방 입장을 제한시키고 알림을 띄운다면 괜찮지않을까요?

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    static let sectionHeaderElementKind = "section-header-element-kind"
p3.
아예 TextLitaral로 빼는 게 어떨까요?

2023-03-16 15:23 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    private let networkManager = NetworkManager.shared
어차피 전반적으로 networkManager를 불러오는 뷰가 많은데, BaseViewController에 두는게 나을 것 같습니다.
BaseViewController(UIViewController타입)이 아닌 경우에만 별도로 작성하면 좋을 것 같네요.

2023-03-16 15:29 UTC, ikanic commented on GiwazipClient/Supports/BaseViewController.swift
> +    }
> p3. baseViewController에 놓은 이유가 있을까요? baseViewController를 만든 이유는 VC에서 불필요한 코드 재작성을 줄이기 위함이지만, 상속에서는 불필요한 상속을 줄이는 것도 중요한데, 일부에서만 사용되는 함수가 상속된다면, 사용하지 않는 함수가 상속되는 VC들이 생겨 불필요한 상속이 되는 것 같습니다.
> 
> 그러니 extension에 작성되는게 낫지않을까요? 아니면 HistoryViewController와 SegmentViewController는 연결되어있어서 HistoryViewController에서 생성하고, 불러올 수도 있을 것 같네요. 하지만 VC를 가볍게 하기 위함이라면 빼는게 나을 것 같습니다.

상속에 대한 문제는 extension에서도 마찬가지입니다.
결국 Extension으로 빼더라도 UIViewController의 Extension, 혹은 BaseViewController의 Extension이 될텐데, 이 경우 UIViewController, 혹은 BaseViewController를 상속 받았을 때, BaseViewController의 내부에 작성하는 것과 다르지 않습니다.

결론은 불필요한 상속이라고 하셨지만, 결국 Extension에 작성하더라도 마찬가지로 상속되기 때문에 크게 다르지 않다 입니다.

2023-03-16 15:29 UTC, taek0622 commented on GiwazipClient/UIComponents/ASView.swift
> +    private let asDateContainer = UIView()
> AS보다 as처럼 보이긴하네요..

ㅎㅎ 하지만 변수 이름이다 보니 어쩔수 없죠.. 필요하다면 warranty로 변경할 수는 있습니다.

2023-03-16 15:31 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +        }
> Q. 상단 카테고리를 2회이상 클릭했을 때에도 print가 되고 있는데, 어떤 기능을 고려하고 else로 상단 카테고리와 게시물을 묶어둔걸까요?

그 부분은 아직 뷰 연결이 되지 않아서 임시로 나눠놓은 부분입니다.
뷰 연결 후에 조건을 다시 나눌 예정이에요.

2023-03-16 15:33 UTC, taek0622 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +                print("디코딩 에러가 발생했습니다. 디코딩 하려는 모델과, API 명세를 다시 확인해주세요.")
> p3 디코딩에러에 대한 별도의 동작이 있을까요? 따로 있어서 임시로 남겨둔 것이 아니라면 TextLitieral에 선언 후, 가져오는 것이 나을 것 같습니다.

클라이언트에서 print는 전부 사라집니다. 해당 부분도 alert나 오류 보고 등으로 변경될 내용이기에 임시로 print를 넣어둔 것 입니다.

2023-03-16 15:34 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +    private let networkManager = NetworkManager.shared
> Q. 기존에는 viewModel이라는 상수명으로 선언했는데, networkManager라는 이름을 사용하셨기에 이후 networkManager로 통일되는 것인지, 습관적으로 작성한 상수명인지 궁금하네요.

viewModel이라는 변수명이 임시라고 생각했는데 아니었나요?
현재 전체 뷰에서 ViewModel이 존재하지 않지만, 뷰 연결 이후에 ViewModel 들이 하나씩 생겨날 예정이라 networkManager 부분과 분리될 것이라고 생각하여 networkManager로 선언했습니다.

2023-03-16 15:35 UTC, ikanic commented on GiwazipClient/Views/SegmentViewController.swift
> +        $0.text = "23.01.10~23.03.15"
> Q. 딱히 영향은 없을 것 같은데, 수정된 이유가 있을까요?

딱히 영향이 없는 것이 맞습니다. 다만 년도가 바뀜에 따라 기본 값도 바꿨을 뿐입니다.
사실 기본 값은 "00.00.00", 혹은 "xx.xx.xx" 등으로 줘서 제대로 통신이 완료되지 않았다고 표시해주는 것이 더 바람직하긴 합니다.

2023-03-16 15:39 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
>      }
> 

날짜 계산 로직상 오류는 없습니다.

해당 부분은 서버시간과 클라이언트 시간을 동기화할 수 없어서 생기는 문제로 해결 방법이 마땅치 않아요.
이 부분에 대해서는 Swift의 Date, mac의 Date, js 및 node의 Date, ubuntu의 Date, postgreSQL의 Date 등 최소 5가지 이상을 동기화해줘야하는 부분입니다만, swift와 Ubuntu, postgreSQL의 Date를 맞추는 방법이 마땅치 않습니다.

이 부분에 대한 소요시간이 너무 크기 때문에 현재는 그냥 두고 후에 수정하는 것이 더 맞다고 생각합니다.

2023-03-16 15:41 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
>      }(UILabel())
> Q. 만약 titleName을
> 
> ```swift
>     private lazy var titleName: UILabel = {
>         $0.text = networkManager.roomData?.name
>        ...
>         return $0
>     }(UILabel())
> ```
> 
> 이처럼 하면 어떻게 될까요? 일단 정상적으로 출력되고 있는데, 어차피 네트워크 에러 시 방 입장을 제한시키고 알림을 띄운다면 괜찮지않을까요?

그렇게 해도 되지만, 처음부터 networkManager를 따오는 것과 초기값을 준 후에 networkManager를 따와서 대입시키는 것에서 후자가 UILabel을 그리는 속도가 조금 더 빠르기 때문에 현재와 같이 두는 것이 좋을 것 같습니다.

2023-03-16 15:41 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +    static let sectionHeaderElementKind = "section-header-element-kind"
> p3. 아예 TextLitaral로 빼는 게 어떨까요?

이 부분은 Text이지만 변동되지 않을 Text이며, HistoryViewController의 Identifier로 사용되고 있는 부분이기 때문에 별도로 빼는 것이 옳지 않은 것 같습니다.

2023-03-16 15:42 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +    private let networkManager = NetworkManager.shared
> 어차피 전반적으로 networkManager를 불러오는 뷰가 많은데, BaseViewController에 두는게 나을 것 같습니다. BaseViewController(UIViewController타입)이 아닌 경우에만 별도로 작성하면 좋을 것 같네요.

넵 빼고 싶었는데, 빼도 되나 싶어서 안빼고 있었습니다. 해당 부분 bb3d6d6 으로 반영했습니다.

2023-03-16 15:48 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +                let itemSize = NSCollectionLayoutSize(widthDimension: .absolute(self.screenWidth/6), heightDimension: .absolute(self.screenWidth/6))
> p5. 컨벤션은 없었지만, 다른 코드와의 통일성을 위해 `self.screenWidth/6`의 나누기(/) 및 기타 수식의 좌우를 한칸씩 띄어주는 게 어떨까요?

해당 부분 및 일부 라인 스페이싱 변경하여 89c0594 에 반영했습니다.

2023-03-16 15:51 UTC, taek0622 commented on GiwazipClient/UIComponents/ASView.swift
> +    }(UILabel())
> p5. 아마 기존에 사용하던 네이밍을 그대로 사용하신 것 같지만, remain은 동사의미의 어휘인데, view 이름으로 사용되는 것은 부적절해보입니다. remained처럼 과거형을 사용하는게 어떨까요? 동의하신다면, 함수를 제외한 변수, 상수. 클래스, 구조체는 명사형으로 해야한다는 내용을 컨벤션에 추가하면 좋을 것 같습니다.

해당 부분 26a942e 로 반영했습니다.
컨벤션은 조금 더 다듬은 뒤에 반영하겠습니다. 이미 이름은 명사형이며, 접두만 명사형이 아닌지라 명사형으로 해야한다! 보다 더 좋은 멘트 생각해서 반영하겠습니다.

2023-03-16 17:22 UTC, JUNY0110 requested changes
드디어.. 2차 리뷰가 끝났습니다.
다음부턴 250줄 지켜주시면 감사하겠습니다 ^^

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +        postCollectionView.delegate = self
p3.
attribute 내 코드가 정리되지 않아 읽기가 어렵습니다.
아래와 같이 정리하는 건 어떨까요?
```swift
    override func attribute() {
        super.attribute()
        
        collectionViewLayout()
        collectionViewAttribute()
        
        configureDataSource()
        
        applyPostSnapshot()
        
        if isWorkView {
            applyCategorySnapshot()
        } else {
            let asDate = extractDate(networkManager.roomData!.endDate, networkManager.roomData!.warrantyTime)
            asView.asDateLabel.text = asDate + ")"
            asView.remainDateLabel.text = extractRemainDate(asDate) + "일"
        }
    }
    
    func collectionViewLayout() {
        categoryCollectionView = UICollectionView(frame: CGRect(x: 0,
                                                                y: 0,
                                                                width: screenWidth,
                                                                height: categorySectionHeight),
                                                  collectionViewLayout: createCollectionViewLayout(.category))
        postCollectionView = UICollectionView(frame: view.bounds,
                                              collectionViewLayout: createCollectionViewLayout(.post))
    }
    
    func collectionViewAttribute() {
        categoryCollectionView.isScrollEnabled = false
        categoryCollectionView.delegate = self
        postCollectionView.delegate = self
    }
```

collectionViewLayout이라 한 것은, Layout보다 View지만 뭐라하기 애매해서 Layout이라 적어봤습니다.

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
p4.
회의 때 의미전달이 잘못되었던 것 같네요.
`categorySectionHeight+3`, `categoryCollectionView inset(2)`를 하지 않아도 될 것 같습니다.

카테고리 상단 구분선이 있어도 카테고리에 가려서 보이지 않는다면, 굳이 없어도 되지 않나? 라는 생각으로,
구분선을 삭제해야되나? 라는 의미에서 구분선을 언급했던 건데, 구분선을 보이도록 하는것으로 이해하신 것 같습니다.
그래서 구분선을 억지로 보여주려고 하다보니 오히려 뷰에 어색함이 생기게 되었네요.

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +        }
p3.
!isWorkView와 isWorkView else가 같은 의미로 사용되므로, `postCollectionView.contentInset.bottom = 90`이 따로 조건문 안에서 사용될 이유가 없겠네요.
```swift
            topContainerView.addSubview(asView)
            asView.snp.makeConstraints {
                $0.edges.equalToSuperview()
            }
            postCollectionView.contentInset.bottom = 90
        }
```

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
한번 선언으로 끝내고 싶었는데, 사실 category와 HistoryView에 동시에 존재해야 해서 2번 선언하는 거군요
한번 선언으로 끝내고 싶었는데, 사실 category와 HistoryView에 동시에 존재해야 해서 2번 선언하는 거군요
History와 Inquiry인줄 알았네요
History와 Inquiry인줄 알았네요

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
p4.
`postSections`에 `section.createDate`를 삽입하는 것과
`postSections`에 `post.createDate`를 삽입하는 것을 비교할 때,
`섹션 생성일`이라 해석되는 것보다, `게시물 생성일`이 이 삽입된다는 표현이 더 자연스러울 것 같습니다.

`for post in ~~~`으로 수정하는 건 어떨까요?

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                cell.chipLabel.text = item.category?.name
&&가 아니라 ,라서 눈에 잘 띄지가 않네요.. 아무래도 제 눈엔 &&가 더 익숙한가봅니다.
어차피 결국 같은 의미라 중요하지 않을지도 모르지만, ,(콤마)와 2개의 앰퍼샌드에 관해 좋았던 레퍼런스가 있어 남깁니다.
옛날에 제가 궁금해했던 내용으로 같이 찾아봤던 내용이라 미뉴도 기억할 것 같네요.

[노수진님 블로그 - 스위프트의 콤마와 &&의 차이: condition과 expression의 구분](https://soojin.ro/blog/swift-comma-vs-and-operator)

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                cell.chipLabel.text = item.category?.name
P4.
`self.selectedCategoryID == 1`가 조건에 들어있는 이유가 있을까요? 
없어도 동작상 이상을 찾지 못했습니다.

지운다면 삼항연산을 하면 좋겠네요
```swift
self.isWorkView ? (cell.chipLabel.text = item.category?.name) : (cell.chipFrame.isHidden = true)
```

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            AF.request(item.photos[0].url, method: .get).response{ response in
기본메소드가 `.get`로 설정되어있어 별도로 작성하지 않아도 될 것 같습니다.

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                for item in networkManager.roomData!.posts!.filter({ $0.category!.name != "문의" }).reversed() {
Q.
`networkManager.roomData!.posts!.filter({ $0.category!.name != "문의" })`
이 코드는 정말 많이 사용되는데 별도 변수로 선언하면 struct라서 변경사항이 반영되지 않게 될까요?
언뜻보기에도 6회 이상 사용되어 질문합니다.

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            selectedCategoryID = networkManager.roomData!.categories![indexPath.item].categoryID
p5.
코드가 길어서, 콤마를 기준으로 조건을 한칸 띄어주면 좋겠네요.
```swift
        if collectionView == categoryCollectionView,
           (selectedCategoryID != networkManager.roomData!.categories![indexPath.item].categoryID) {
```

2023-03-16 17:22 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
p3.
동작이 상당히 자연스럽기는 한데, 

|문제의 동작화면|
|:-:|
|<img src= "https://user-images.githubusercontent.com/98405970/225698742-f71ab4f9-e645-4313-9f38-2b694efcec4b.png" width=300>|

스크롤을 올렸다가 조금만 내리면 오히려 상단에 빈 공간이 많이 생기게 되어 여백이 많아지게 됩니다.

`currentOffset > -self.categorySectionHeight/7 * 5`처럼 해도 아쉬움이 남습니다.
혹시 categorySection이 등장하면서 아래의 카테고리를 밀어내는 동작은 어려울까요?

2023-03-16 17:27 UTC, JUNY0110 commented on GiwazipClient/Supports/BaseViewController.swift
> +    }
> > p3. baseViewController에 놓은 이유가 있을까요? baseViewController를 만든 이유는 VC에서 불필요한 코드 재작성을 줄이기 위함이지만, 상속에서는 불필요한 상속을 줄이는 것도 중요한데, 일부에서만 사용되는 함수가 상속된다면, 사용하지 않는 함수가 상속되는 VC들이 생겨 불필요한 상속이 되는 것 같습니다.
> > 그러니 extension에 작성되는게 낫지않을까요? 아니면 HistoryViewController와 SegmentViewController는 연결되어있어서 HistoryViewController에서 생성하고, 불러올 수도 있을 것 같네요. 하지만 VC를 가볍게 하기 위함이라면 빼는게 나을 것 같습니다.
> 
> 상속에 대한 문제는 extension에서도 마찬가지입니다. 결국 Extension으로 빼더라도 UIViewController의 Extension, 혹은 BaseViewController의 Extension이 될텐데, 이 경우 UIViewController, 혹은 BaseViewController를 상속 받았을 때, BaseViewController의 내부에 작성하는 것과 다르지 않습니다.
> 
> 결론은 불필요한 상속이라고 하셨지만, 결국 Extension에 작성하더라도 마찬가지로 상속되기 때문에 크게 다르지 않다 입니다.

음, 그럼 기존의 UIViewController extension으로 되어있는 코드를 BaseVC로 옮길건가요?
둘 중 하나로 통일하는 것이 좋지 않을까요? 어떻게 생각하시나요?

2023-03-16 17:31 UTC, JUNY0110 commented on GiwazipClient/UIComponents/ASView.swift
> +    }(UILabel())
> 해당 부분 [26a942e](https://github.com/Samsamhada/Giwazip-Client-App/commit/26a942eb90d00a894f00efdfd55abb5bd61375a4) 로 반영했습니다. 컨벤션은 조금 더 다듬은 뒤에 반영하겠습니다. 이미 이름은 명사형이며, 접두만 명사형이 아닌지라 명사형으로 해야한다! 보다 더 좋은 멘트 생각해서 반영하겠습니다.

확인했습니다.

2023-03-16 17:31 UTC, JUNY0110 commented on GiwazipClient/ViewModels/NetworkManager.swift
> +                print("디코딩 에러가 발생했습니다. 디코딩 하려는 모델과, API 명세를 다시 확인해주세요.")
> 클라이언트에서 print는 전부 사라집니다. 해당 부분도 alert나 오류 보고 등으로 변경될 내용이기에 임시로 print를 넣어둔 것 입니다.

확인했습니다.

2023-03-16 17:33 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +    private let networkManager = NetworkManager.shared
> > Q. 기존에는 viewModel이라는 상수명으로 선언했는데, networkManager라는 이름을 사용하셨기에 이후 networkManager로 통일되는 것인지, 습관적으로 작성한 상수명인지 궁금하네요.
> 
> viewModel이라는 변수명이 임시라고 생각했는데 아니었나요? 현재 전체 뷰에서 ViewModel이 존재하지 않지만, 뷰 연결 이후에 ViewModel 들이 하나씩 생겨날 예정이라 networkManager 부분과 분리될 것이라고 생각하여 networkManager로 선언했습니다.

viewModel이 임시명은 맞습니다. :0
그래서 networkManager로 사용할 것인지가 궁금하네요. 사용한다면 다른 VC에서도 수정해야하기 때문이죠!

2023-03-16 17:33 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +        $0.text = "23.01.10~23.03.15"
> > Q. 딱히 영향은 없을 것 같은데, 수정된 이유가 있을까요?
> 
> 딱히 영향이 없는 것이 맞습니다. 다만 년도가 바뀜에 따라 기본 값도 바꿨을 뿐입니다. 사실 기본 값은 "00.00.00", 혹은 "xx.xx.xx" 등으로 줘서 제대로 통신이 완료되지 않았다고 표시해주는 것이 더 바람직하긴 합니다.

확인했습니다.

2023-03-16 17:35 UTC, taek0622 commented on GiwazipClient/Supports/BaseViewController.swift
> +    }
> > > p3. baseViewController에 놓은 이유가 있을까요? baseViewController를 만든 이유는 VC에서 불필요한 코드 재작성을 줄이기 위함이지만, 상속에서는 불필요한 상속을 줄이는 것도 중요한데, 일부에서만 사용되는 함수가 상속된다면, 사용하지 않는 함수가 상속되는 VC들이 생겨 불필요한 상속이 되는 것 같습니다.
> > > 그러니 extension에 작성되는게 낫지않을까요? 아니면 HistoryViewController와 SegmentViewController는 연결되어있어서 HistoryViewController에서 생성하고, 불러올 수도 있을 것 같네요. 하지만 VC를 가볍게 하기 위함이라면 빼는게 나을 것 같습니다.
> > 
> > 
> > 상속에 대한 문제는 extension에서도 마찬가지입니다. 결국 Extension으로 빼더라도 UIViewController의 Extension, 혹은 BaseViewController의 Extension이 될텐데, 이 경우 UIViewController, 혹은 BaseViewController를 상속 받았을 때, BaseViewController의 내부에 작성하는 것과 다르지 않습니다.
> > 결론은 불필요한 상속이라고 하셨지만, 결국 Extension에 작성하더라도 마찬가지로 상속되기 때문에 크게 다르지 않다 입니다.
> 
> 음, 그럼 기존의 UIViewController extension으로 되어있는 코드를 BaseVC로 옮길건가요? 둘 중 하나로 통일하는 것이 좋지 않을까요? 어떻게 생각하시나요?

음.. 이 부분은 꼭 하나로 통일할 이유는 없어보입니다. 다만, 얼마나 사용되고 어디에 사용되냐에 따라 extension, 혹은 baseVC로 나누는 기준이 있으면 좋을 것 같긴합니다. Alert나 HideKeyboard와 같이 직접적으로 뷰에 영향을 주는 것들은 extension으로 빼고 해당 Function 같이 데이터를 다루는 것은 baseVC에 넣는다던가, 사용 빈도에 따라 나눈다던가 할 수 있을 것 같네요.

2023-03-16 17:37 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +    private let networkManager = NetworkManager.shared
> > > Q. 기존에는 viewModel이라는 상수명으로 선언했는데, networkManager라는 이름을 사용하셨기에 이후 networkManager로 통일되는 것인지, 습관적으로 작성한 상수명인지 궁금하네요.
> > 
> > 
> > viewModel이라는 변수명이 임시라고 생각했는데 아니었나요? 현재 전체 뷰에서 ViewModel이 존재하지 않지만, 뷰 연결 이후에 ViewModel 들이 하나씩 생겨날 예정이라 networkManager 부분과 분리될 것이라고 생각하여 networkManager로 선언했습니다.
> 
> viewModel이 임시명은 맞습니다. :0 그래서 networkManager로 사용할 것인지가 궁금하네요. 사용한다면 다른 VC에서도 수정해야하기 때문이죠!

넵 networkManager가 알아보기 좋을 것 같습니다. networkData로 해야하나 잠시 생각했으나, 뒤에 메서드가 붙을 경우도 있기 때문에 networkManager가 좋을 것 같네요.

2023-03-16 17:38 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +        $0.text = "23.01.10~23.03.15"
> > 딱히 영향이 없는 것이 맞습니다. 다만 년도가 바뀜에 따라 기본 값도 바꿨을 뿐입니다. 사실 기본 값은 "00.00.00", 혹은 "xx.xx.xx" 등으로 줘서 제대로 통신이 완료되지 않았다고 표시해주는 것이 더 바람직하긴 합니다.
> 
> 확인했습니다. 그럼 출시 전에는 수정하면 좋을 것 같네요!

바로 반영하겠습니다. "oo.oo.oo", "OO.OO.OO", "xx.xx.xx", "XX.XX.XX", "00.00.00" 중에 어느 것으로 반영하는 것이 좋을까요?

2023-03-16 17:42 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
>      }
> 날짜 계산 로직상 오류는 없습니다.
> 해당 부분은 서버시간과 클라이언트 시간을 동기화할 수 없어서 생기는 문제로 해결방법이 마땅치 않아요.
> 이 부분에 대해서는 Swift의 Date, mac의 Date, js 및 node의 Date, ubuntu의 Date, postgreSQL의 Date 등 최소 5가지 이상을 동기화해줘야하는 부분입니다만, swift와 Ubuntu, postgreSQL의 Date를 맞추는 방법이 마땅치 않습니다.
> 이 부분에 대한 소요시간이 너무 크기 때문에 현재는 그냥 두고 후에 수정하는 것이 더 맞다고 생각합니다.

그렇다면 asDate를 이용하면 어떨까요?
AS마감일의 00시를 기준으로 하고, asDate가 미국시 15시로 고정되어있음을 이용하면 될 것 같습니다. + 8시간만 하면 되니 days를 Interval를 86400초로 나눈것처럼하면 오차를 줄일 수 있지 않을까요?
그렇게하면 굳이 서버시간으로 골치아프지 않아도 될 것 같네요.

2023-03-16 17:42 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                let itemSize = NSCollectionLayoutSize(widthDimension: .absolute(self.screenWidth/6), heightDimension: .absolute(self.screenWidth/6))
> 해당 부분 및 일부 라인 스페이싱 변경하여 [89c0594](https://github.com/Samsamhada/Giwazip-Client-App/commit/89c0594a628f64e72670d53f8b1627f1dd2442c4) 에 반영했습니다.

확인했습니다.

2023-03-16 17:43 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
>      }(UILabel())
> > Q. 만약 titleName을
> > ```swift
> >     private lazy var titleName: UILabel = {
> >         $0.text = networkManager.roomData?.name
> >        ...
> >         return $0
> >     }(UILabel())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 이처럼 하면 어떻게 될까요? 일단 정상적으로 출력되고 있는데, 어차피 네트워크 에러 시 방 입장을 제한시키고 알림을 띄운다면 괜찮지않을까요?
> 
> 그렇게 해도 되지만, 처음부터 networkManager를 따오는 것과 초기값을 준 후에 networkManager를 따와서 대입시키는 것에서 후자가 UILabel을 그리는 속도가 조금 더 빠르기 때문에 현재와 같이 두는 것이 좋을 것 같습니다.

깜빡했네요. 확인했습니다.

2023-03-16 17:44 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    static let sectionHeaderElementKind = "section-header-element-kind"
> > p3. 아예 TextLitaral로 빼는 게 어떨까요?
> 
> 이 부분은 Text이지만 변동되지 않을 Text이며, HistoryViewController의 Identifier로 사용되고 있는 부분이기 때문에 별도로 빼는 것이 옳지 않은 것 같습니다.

확인했습니다.

2023-03-16 17:44 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +    private let networkManager = NetworkManager.shared
> 넵 빼고 싶었는데, 빼도 되나 싶어서 안빼고 있었습니다. 해당 부분 [bb3d6d6](https://github.com/Samsamhada/Giwazip-Client-App/commit/bb3d6d672742ae56e6d7acf114cca036e7115b95) 으로 반영했습니다.

확인했습니다.

2023-03-16 17:49 UTC, JUNY0110 commented on GiwazipClient/Supports/BaseViewController.swift
> +    }
> 음.. 이 부분은 꼭 하나로 통일할 이유는 없어보입니다. 다만, 얼마나 사용되고 어디에 사용되냐에 따라 extension, 혹은 baseVC로 나누는 기준이 있으면 좋을 것 같긴합니다. Alert나 HideKeyboard와 같이 직접적으로 뷰에 영향을 주는 것들은 extension으로 빼고 해당 Function 같이 데이터를 다루는 것은 baseVC에 넣는다던가, 사용 빈도에 따라 나눈다던가 할 수 있을 것 같네요.

통일하는 것은 필요한 코드를 찾고 이해하기 용이하기에 통일성을 유지하는건 꽤 중요하다 생각합니다.
다만, 미뉴의 의견대로 하는 것도 하나의 통일성이라 생각하고,
데이터를 다루듯 로직적인 부분은 BaseVC에 담는 것에 동의하며,
뷰와 관련된 것은 Extension에서 사용할 수 있겠네요.

하지만, 혹여나 BaseVC를 상속받지 않는 VC에서의 로직이라면 extension으로 빠져 예외가 될 수 있을텐데, 이런 예외를 줄이는 방법이 있을까요?
어떤 코드는 BaseVC에 있고, 어떤 코드는 Extension에 있는 이유가 뭐지? 라는 의문을 최소화하고 싶어 계속 질문을 남기게 되네요

2023-03-16 17:50 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +    private let networkManager = NetworkManager.shared
> 넵 networkManager가 알아보기 좋을 것 같습니다. networkData로 해야하나 잠시 생각했으나, 뒤에 메서드가 붙을 경우도 있기 때문에 networkManager가 좋을 것 같네요.

확인했습니다.

2023-03-16 17:58 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +        postCollectionView.delegate = self
> p3. attribute 내 코드가 정리되지 않아 읽기가 어렵습니다. 아래와 같이 정리하는 건 어떨까요?
> 
> ```swift
>     override func attribute() {
>         super.attribute()
>         
>         collectionViewLayout()
>         collectionViewAttribute()
>         
>         configureDataSource()
>         
>         applyPostSnapshot()
>         
>         if isWorkView {
>             applyCategorySnapshot()
>         } else {
>             let asDate = extractDate(networkManager.roomData!.endDate, networkManager.roomData!.warrantyTime)
>             asView.asDateLabel.text = asDate + ")"
>             asView.remainDateLabel.text = extractRemainDate(asDate) + "일"
>         }
>     }
>     
>     func collectionViewLayout() {
>         categoryCollectionView = UICollectionView(frame: CGRect(x: 0,
>                                                                 y: 0,
>                                                                 width: screenWidth,
>                                                                 height: categorySectionHeight),
>                                                   collectionViewLayout: createCollectionViewLayout(.category))
>         postCollectionView = UICollectionView(frame: view.bounds,
>                                               collectionViewLayout: createCollectionViewLayout(.post))
>     }
>     
>     func collectionViewAttribute() {
>         categoryCollectionView.isScrollEnabled = false
>         categoryCollectionView.delegate = self
>         postCollectionView.delegate = self
>     }
> ```
> 
> collectionViewLayout이라 한 것은, Layout보다 View지만 뭐라하기 애매해서 Layout이라 적어봤습니다.

해당 부분 cf899bf 에서 반영했습니다. 다만, collectionViewLayout은 UICollectionViewLayout 타입과 혼동의 여지가 있어 컬렉션뷰를 초기화하는 부분이므로 initializeCollectionView로 함수 이름을 정했습니다.

2023-03-16 18:00 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +        $0.text = "23.01.10~23.03.15"
> 바로 반영하겠습니다. "oo.oo.oo", "OO.OO.OO", "xx.xx.xx", "XX.XX.XX", "00.00.00" 중에 어느 것으로 반영하는 것이 좋을까요?

5번이 좋겠네요!

2023-03-16 18:04 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
> p4. 회의 때 의미전달이 잘못되었던 것 같네요. `categorySectionHeight+3`, `categoryCollectionView inset(2)`를 하지 않아도 될 것 같습니다.
> 
> 카테고리 상단 구분선이 있어도 카테고리에 가려서 보이지 않는다면, 굳이 없어도 되지 않나? 라는 생각으로, 구분선을 삭제해야되나? 라는 의미에서 구분선을 언급했던 건데, 구분선을 보이도록 하는것으로 이해하신 것 같습니다. 그래서 구분선을 억지로 보여주려고 하다보니 오히려 뷰에 어색함이 생기게 되었네요.

해당 부분 인지는 했었습니다만, 의견을 여쭤보려고 바꿨다가 회의때 물어보는 걸 까먹었네요.  해당 부분 bd2f12a 에서 수정 반영했습니다.

2023-03-16 18:05 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +        postCollectionView.delegate = self
> 해당 부분 [cf899bf](https://github.com/Samsamhada/Giwazip-Client-App/commit/cf899bfc9e4dcf40b9823fc43f14bbe5a912065a) 에서 반영했습니다. 다만, collectionViewLayout은 UICollectionViewLayout 타입과 혼동의 여지가 있어 컬렉션뷰를 초기화하는 부분이므로 initializeCollectionView로 함수 이름을 정했습니다.

확인했습니다.

2023-03-16 18:07 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +        }
> p3. !isWorkView와 isWorkView else가 같은 의미로 사용되므로, `postCollectionView.contentInset.bottom = 90`이 따로 조건문 안에서 사용될 이유가 없겠네요.
> 
> ```swift
>             topContainerView.addSubview(asView)
>             asView.snp.makeConstraints {
>                 $0.edges.equalToSuperview()
>             }
>             postCollectionView.contentInset.bottom = 90
>         }
> ```

postCollection Inset 부분이 나눠지는게 애매해서 따로 썼었는데, 전체적으로 관련 코드 위치 재조정해서 854eceb 로 반영했습니다.

2023-03-16 18:08 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
> 한번 선언으로 끝내고 싶었는데, 사실 category와 HistoryView에 동시에 존재해야 해서 2번 선언하는 거군요 한번 선언으로 끝내고 싶었는데, 사실 category와 HistoryView에 동시에 존재해야 해서 2번 선언하는 거군요 History와 Inquiry인줄 알았네요 History와 Inquiry인줄 알았네요

그렇습니콩!
그렇습니콩!

2023-03-16 18:10 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
> p4. `postSections`에 `section.createDate`를 삽입하는 것과 `postSections`에 `post.createDate`를 삽입하는 것을 비교할 때, `섹션 생성일`이라 해석되는 것보다, `게시물 생성일`이 이 삽입된다는 표현이 더 자연스러울 것 같습니다.
> 
> `for post in ~~~`으로 수정하는 건 어떨까요?

고민했던 부분이긴한데 확실히 post가 더 좋아보이네요. 225285b 로 반영했습니다. 의견 감사합니다.

2023-03-16 18:17 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +                cell.chipLabel.text = item.category?.name
> &&가 아니라 ,라서 눈에 잘 띄지가 않네요.. 아무래도 제 눈엔 &&가 더 익숙한가봅니다. 어차피 결국 같은 의미라 중요하지 않을지도 모르지만, ,(콤마)와 2개의 앰퍼샌드에 관해 좋았던 레퍼런스가 있어 남깁니다. 옛날에 제가 궁금해했던 내용으로 같이 찾아봤던 내용이라 미뉴도 기억할 것 같네요.
> 
> [노수진님 블로그 - 스위프트의 콤마와 &&의 차이: condition과 expression의 구분](https://soojin.ro/blog/swift-comma-vs-and-operator)

해당 부분은 사실 condition이자 bool expression이라서 어느 쪽을 써도 상관은 없습니다만, 가독성 측면에서 눈에 띄지 않는다면 수정하는 것이 맞다고 생각하여 ae96ca2 에서 반영했습니다.
추가적으로 이렇게 사용된 부분을 찾고 있는데 아직 발견을 못해서 혹시 추가적으로 발견한다면 수정하겠습니다.

2023-03-16 18:22 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +                cell.chipLabel.text = item.category?.name
> P4. `self.selectedCategoryID == 1`가 조건에 들어있는 이유가 있을까요? 없어도 동작상 이상을 찾지 못했습니다.
> 
> 지운다면 삼항연산을 하면 좋겠네요
> 
> ```swift
> self.isWorkView ? (cell.chipLabel.text = item.category?.name) : (cell.chipFrame.isHidden = true)
> ```

해당 부분은 지울 수 없습니다, selectedCategoryID가 1일 때 전체 카테고리를 보여주는 로직이며, 이것으로 칩의 내용과 가시성 여부를 결정하므로 칩 부분에서 옳지 않은 동작을 발생시킵니다.

추가로 해당 부분에 대한 답변을 적으면서 기존에 가지고 있던 문제인 다른 카테고리에서 전체로 왔을 때 일부 칩이 숨겨지는 버그를 수정하여 b05b04b 로 반영했습니다.

2023-03-16 18:27 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +            AF.request(item.photos[0].url, method: .get).response{ response in
> 기본메소드가 `.get`로 설정되어있어 별도로 작성하지 않아도 될 것 같습니다.

해당 부분 3241dba 로 반영했습니다.

2023-03-16 18:27 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +                for item in networkManager.roomData!.posts!.filter({ $0.category!.name != "문의" }).reversed() {
> Q. `networkManager.roomData!.posts!.filter({ $0.category!.name != "문의" })` 이 코드는 정말 많이 사용되는데 별도 변수로 선언하면 struct라서 변경사항이 반영되지 않게 될까요? 언뜻보기에도 6회 이상 사용되어 질문합니다.

네 이 부분은 변수로 선언 시에 값을 저장하고 있게 되기 때문에 문제가 발생할 수 있습니다.

2023-03-16 18:30 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +            selectedCategoryID = networkManager.roomData!.categories![indexPath.item].categoryID
> p5. 코드가 길어서, 콤마를 기준으로 조건을 한칸 띄어주면 좋겠네요.
> 
> ```swift
>         if collectionView == categoryCollectionView,
>            (selectedCategoryID != networkManager.roomData!.categories![indexPath.item].categoryID) {
> ```

해당 부분에 사용된 ,도 &&로 바꾸었으며 && 기준으로 한줄 띄어서 5acd118 로 반영했습니다.

2023-03-16 18:31 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
> p3. 동작이 상당히 자연스럽기는 한데,
> 
> 문제의 동작화면
> <img alt="" width="300" src="https://user-images.githubusercontent.com/98405970/225698742-f71ab4f9-e645-4313-9f38-2b694efcec4b.png">
> 스크롤을 올렸다가 조금만 내리면 오히려 상단에 빈 공간이 많이 생기게 되어 여백이 많아지게 됩니다.
> 
> `currentOffset > -self.categorySectionHeight/7 * 5`처럼 해도 아쉬움이 남습니다. 혹시 categorySection이 등장하면서 아래의 카테고리를 밀어내는 동작은 어려울까요?

layout을 직접적으로 변경하게 되는 애니메이션이라 현재로서는 어려울 것 같습니다.
후에 애니메이션에 대해 조금 더 공부한 후에는 변경할 수 있을지도 모르겠습니다만, 현재로선 무리로 판단됩니다.

2023-03-16 18:35 UTC, taek0622 commented on GiwazipClient/Supports/BaseViewController.swift
> +    }
> > 음.. 이 부분은 꼭 하나로 통일할 이유는 없어보입니다. 다만, 얼마나 사용되고 어디에 사용되냐에 따라 extension, 혹은 baseVC로 나누는 기준이 있으면 좋을 것 같긴합니다. Alert나 HideKeyboard와 같이 직접적으로 뷰에 영향을 주는 것들은 extension으로 빼고 해당 Function 같이 데이터를 다루는 것은 baseVC에 넣는다던가, 사용 빈도에 따라 나눈다던가 할 수 있을 것 같네요.
> 
> 통일하는 것은 필요한 코드를 찾고 이해하기 용이하기에 통일성을 유지하는건 꽤 중요하다 생각합니다. 다만, 미뉴의 의견대로 하는 것도 하나의 통일성이라 생각하고, 데이터를 다루듯 로직적인 부분은 BaseVC에 담는 것에 동의하며, 뷰와 관련된 것은 Extension에서 사용할 수 있겠네요.
> 
> 하지만, 혹여나 BaseVC를 상속받지 않는 VC에서의 로직이라면 extension으로 빠져 예외가 될 수 있을텐데, 이런 예외를 줄이는 방법이 있을까요? 어떤 코드는 BaseVC에 있고, 어떤 코드는 Extension에 있는 이유가 뭐지? 라는 의문을 최소화하고 싶어 계속 질문을 남기게 되네요

BaseVC를 상속받지 않는 UIVC가 있다면 extension으로 빠지는 것이 더 맞습니다만, 현재로서는 BaseVC를 상속받지 않는 VC가 없고, BaseVC 자체가 공통적으로 사용될 수 있는 부분을 빼놓는 것인지라 앞으로도 BaseVC를 상속받지 않는 뷰가 생길 가능성은 적다고 판단됩니다.

이 부분에 대해서는 별도로 컨벤션을 논의하거나 하는 편이 좋을 것 같아요.
extension을 사용하겠다고 하면, 사실 BaseVC 자체가 필요없어질 가능성이 존재하기 때문에 컨벤션을 논의하는 쪽이 더 올바를 것 같습니다.

2023-03-16 18:38 UTC, taek0622 commented on GiwazipClient/Views/SegmentViewController.swift
> +        $0.text = "23.01.10~23.03.15"
> > 바로 반영하겠습니다. "oo.oo.oo", "OO.OO.OO", "xx.xx.xx", "XX.XX.XX", "00.00.00" 중에 어느 것으로 반영하는 것이 좋을까요?
> 
> 5번이 좋겠네요!

날짜와 연관된 부분은 다 비슷한 형식으로 변경하여 ad10966 으로 반영했습니다.

2023-03-16 18:40 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
>      }
> > 날짜 계산 로직상 오류는 없습니다.
> > 해당 부분은 서버시간과 클라이언트 시간을 동기화할 수 없어서 생기는 문제로 해결방법이 마땅치 않아요.
> > 이 부분에 대해서는 Swift의 Date, mac의 Date, js 및 node의 Date, ubuntu의 Date, postgreSQL의 Date 등 최소 5가지 이상을 동기화해줘야하는 부분입니다만, swift와 Ubuntu, postgreSQL의 Date를 맞추는 방법이 마땅치 않습니다.
> > 이 부분에 대한 소요시간이 너무 크기 때문에 현재는 그냥 두고 후에 수정하는 것이 더 맞다고 생각합니다.
> 
> 그렇다면 asDate를 이용하면 어떨까요? AS마감일의 00시를 기준으로 하고, asDate가 미국시 15시로 고정되어있음을 이용하면 될 것 같습니다. + 8시간만 하면 되니 days를 Interval를 86400초로 나눈것처럼하면 오차를 줄일 수 있지 않을까요? 그렇게하면 굳이 서버시간으로 골치아프지 않아도 될 것 같네요.

현재도 asDate는 사용되고 있습니다. 이 부분은 조금 더 로직에 대한 고민이 필요해보여요.
asDate 보다는 Date() 부분을 변경해야 조금 더 나은 동작을 할 수 있을 것 같은데, 이 부분을 수정하게 되면 코드가 급격하게 증가하게 된다는 문제점이 있어서 여러 방면으로 고민해보고 있습니다.

2023-03-17 14:59 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
> 해당 부분 인지는 했었습니다만, 의견을 여쭤보려고 바꿨다가 회의때 물어보는 걸 까먹었네요. 해당 부분 [bd2f12a](https://github.com/Samsamhada/Giwazip-Client-App/commit/bd2f12a0f304201c95610b410b8dddeb06353a60) 에서 수정 반영했습니다.

확인했습니다.

2023-03-17 15:00 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +        }
> postCollection Inset 부분이 나눠지는게 애매해서 따로 썼었는데, 전체적으로 관련 코드 위치 재조정해서 [854eceb](https://github.com/Samsamhada/Giwazip-Client-App/commit/854ecebef36cbf7a586275675b25f1223b17c584) 로 반영했습니다.

확인했습니다.

2023-03-17 15:02 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
> 고민했던 부분이긴한데 확실히 post가 더 좋아보이네요. [225285b](https://github.com/Samsamhada/Giwazip-Client-App/commit/225285bc692eab3131ff259fc7b90346bb2bd278) 로 반영했습니다. 의견 감사합니다.

확인했습니다.

2023-03-17 15:03 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            AF.request(item.photos[0].url, method: .get).response{ response in
> 해당 부분 [3241dba](https://github.com/Samsamhada/Giwazip-Client-App/commit/3241dba54eec0435c4718501276ac33bb63c15e6) 로 반영했습니다.

확인했습니다.

2023-03-17 15:03 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                for item in networkManager.roomData!.posts!.filter({ $0.category!.name != "문의" }).reversed() {
> 네 이 부분은 변수로 선언 시에 값을 저장하고 있게 되기 때문에 문제가 발생할 수 있습니다.

안타깝네요..

2023-03-17 15:04 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            selectedCategoryID = networkManager.roomData!.categories![indexPath.item].categoryID
> 해당 부분에 사용된 ,도 &&로 바꾸었으며 && 기준으로 한줄 띄어서 [5acd118](https://github.com/Samsamhada/Giwazip-Client-App/commit/5acd1188cfbc8f078b1d3c014c2800eb71cb7ff7) 로 반영했습니다.

확인했습니다.

2023-03-17 15:05 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +            }
> layout을 직접적으로 변경하게 되는 애니메이션이라 현재로서는 어려울 것 같습니다. 후에 애니메이션에 대해 조금 더 공부한 후에는 변경할 수 있을지도 모르겠습니다만, 현재로선 무리로 판단됩니다.

안타깝네요..

2023-03-17 15:10 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                cell.chipLabel.text = item.category?.name
> 해당 부분은 사실 condition이자 bool expression이라서 어느 쪽을 써도 상관은 없습니다만, 가독성 측면에서 눈에 띄지 않는다면 수정하는 것이 맞다고 생각하여 [ae96ca2](https://github.com/Samsamhada/Giwazip-Client-App/commit/ae96ca2f29632d13cd2400c95d5f38f79fab119f) 에서 반영했습니다. 추가적으로 이렇게 사용된 부분을 찾고 있는데 아직 발견을 못해서 혹시 추가적으로 발견한다면 수정하겠습니다.

확인했습니다

2023-03-17 15:12 UTC, JUNY0110 commented on GiwazipClient/Views/SegmentViewController.swift
> +        $0.text = "23.01.10~23.03.15"
> 날짜와 연관된 부분은 다 비슷한 형식으로 변경하여 [ad10966](https://github.com/Samsamhada/Giwazip-Client-App/commit/ad109662f307ee1a98ab737cd6b86edca802e1b4) 으로 반영했습니다.

확인했습니다.

2023-03-17 15:31 UTC, JUNY0110 commented on GiwazipClient/Supports/BaseViewController.swift
> +    }
> BaseVC를 상속받지 않는 UIVC가 있다면 extension으로 빠지는 것이 더 맞습니다만, 현재로서는 BaseVC를 상속받지 않는 VC가 없고, BaseVC 자체가 공통적으로 사용될 수 있는 부분을 빼놓는 것인지라 앞으로도 BaseVC를 상속받지 않는 뷰가 생길 가능성은 적다고 판단됩니다.
> 
> 이 부분에 대해서는 별도로 컨벤션을 논의하거나 하는 편이 좋을 것 같아요. extension을 사용하겠다고 하면, 사실 BaseVC 자체가 필요없어질 가능성이 존재하기 때문에 컨벤션을 논의하는 쪽이 더 올바를 것 같습니다.

회의결과
1. BaseViewController의 기본 함수를 제외한 기능 및 뷰와 관련된 확장코드는 extension에서 사용
2. Extension의 파일 순서는 type(String 등) - view(UIView 등) - viewcontroller(UIVC 등) 순
3. Extension은 UIViewController+, UIView+ 등으로 통합 (기존 makeAlert+)
4. Extension 내부에서 주석(MARK: - MakeAlert 등)으로 정리

2023-03-17 15:32 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
>      }
> 현재도 asDate는 사용되고 있습니다. 이 부분은 조금 더 로직에 대한 고민이 필요해보여요. asDate 보다는 Date() 부분을 변경해야 조금 더 나은 동작을 할 수 있을 것 같은데, 이 부분을 수정하게 되면 코드가 급격하게 증가하게 된다는 문제점이 있어서 여러 방면으로 고민해보고 있습니다.

안타깝네요..

2023-03-18 14:39 UTC, JUNY0110 commented on GiwazipClient/UIComponents/ASView.swift
> +    let remainDateContainer = UIView()
p2.
접근지정자 추가 및 remained로 변수명을 수정해주세요~

2023-03-18 14:39 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
>          $0.layer.borderColor = UIColor.black.cgColor
p3.
borderColor는 기본값이 black이라 없어도 되겠네요:)

2023-03-18 14:39 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                section.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0)
|적용 전|적용 후|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/98405970/226112173-bc3d3271-9a95-4491-a9f8-61a98fa5f8a6.png" width=300>|<img src="https://user-images.githubusercontent.com/98405970/226112195-e03d486d-8a77-4b37-9e3d-1be2768811e0.png" width=300>|

카테고리의 경계면이 옆 카테고리가 있는지 없는지에 따라 경계면이 연장되어 더 두껍게 보이는 부분이 있습니다.
옆에 다른 카테고리 유무와 관계없이 동일한 두께의 경계면을 보일 필요가 있을 것 같네요.
group과 section에 있는 spacing 메소드를 활용하면 될 것 같습니다 :)
하지만, 이를 반영하면 우측에 여백이 발생하니 이 점을 주의해서 수정해주시면 좋을 것 같습니다.

2023-03-18 14:39 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                cell.chipLabel.text = item.category?.name
> 해당 부분은 지울 수 없습니다, selectedCategoryID가 1일 때 전체 카테고리를 보여주는 로직이며, 이것으로 칩의 내용과 가시성 여부를 결정하므로 칩 부분에서 옳지 않은 동작을 발생시킵니다.
> 
> 추가로 해당 부분에 대한 답변을 적으면서 기존에 가지고 있던 문제인 다른 카테고리에서 전체로 왔을 때 일부 칩이 숨겨지는 버그를 수정하여 [b05b04b](https://github.com/Samsamhada/Giwazip-Client-App/commit/b05b04b415cbbf878a0c6f5d082401e1d116d3ac) 로 반영했습니다.

어떤부분인가 했더니 chipFrame이었네요. 확인했습니다.

2023-03-18 14:43 UTC, JUNY0110 requested changes
몇가지 추가 수정사항이 있습니다 :)
이게 마지막일 것 같군요

2023-03-18 14:51 UTC, taek0622 commented on GiwazipClient/UIComponents/ASView.swift
> +    let remainDateContainer = UIView()
> p2. 접근지정자 추가 및 remained로 변수명을 수정해주세요~

해당 부분은 상위 뷰에서 hidden 처리를 해야해서 접근지정자를 추가할 수 없습니다.
변수명은 수정하여 c413b27 로 반영했습니다.

2023-03-18 14:54 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
>          $0.layer.borderColor = UIColor.black.cgColor
> p3. borderColor는 기본값이 black이라 없어도 되겠네요:)

지난번에 관련해서 추가해달라 하셔서 추가했는데, 다시 삭제되는군요.
해당 부분 ad2ec68 로 반영했습니다.

2023-03-18 15:00 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +                section.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0)
> p3.
> 
> 적용 전	적용 후
> <img alt="" width="300" src="https://user-images.githubusercontent.com/98405970/226112173-bc3d3271-9a95-4491-a9f8-61a98fa5f8a6.png">	<img alt="" width="300" src="https://user-images.githubusercontent.com/98405970/226112195-e03d486d-8a77-4b37-9e3d-1be2768811e0.png">
> 카테고리의 경계면이 옆 카테고리가 있는지 없는지에 따라 경계면이 연장되어 더 두껍게 보이는 부분이 있습니다. 옆에 다른 카테고리 유무와 관계없이 동일한 두께의 경계면을 보일 필요가 있을 것 같네요. group과 section에 있는 spacing 메소드를 활용하면 될 것 같습니다 :) 하지만, 이를 반영하면 우측에 여백이 발생하니 이 점을 주의해서 수정해주시면 좋을 것 같습니다.

해당 부분은 group과 section 만으로는 완전히 동일한 두께의 경계면을 보일 수 없습니다. 더 까다로운 조건이 필요하기 때문에 해당 PR에서는 반영하지 않겠습니다.

2023-03-18 15:34 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
>          $0.layer.borderColor = UIColor.black.cgColor
> > p3. borderColor는 기본값이 black이라 없어도 되겠네요:)
> 
> 지난번에 관련해서 추가해달라 하셔서 추가했는데, 다시 삭제되는군요. 해당 부분 [ad2ec68](https://github.com/Samsamhada/Giwazip-Client-App/commit/ad2ec682065426548346f74eb8dc4bb2e15988b2) 로 반영했습니다.

확인했습니다 후후:)

2023-03-18 15:53 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +                section.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0)
> 해당 부분은 group과 section 만으로는 완전히 동일한 두께의 경계면을 보일 수 없습니다. 더 까다로운 조건이 필요하기 때문에 우선 얼추 비슷해 보이도록 [5d1bdd2](https://github.com/Samsamhada/Giwazip-Client-App/commit/5d1bdd26f2dce18280198d43b314015f80d2bfc1) 로 반영했습니다만, 온전하게 동일하게 보여줄 수 없기에 추후에 이 부분이 수정 가능하다면 그때 다시 수정해서 반영하겠습니다.

흠 일단 알겠습니다.

2023-03-18 15:53 UTC, JUNY0110 commented on GiwazipClient/UIComponents/ASView.swift
> +    let remainDateContainer = UIView()
> > p2. 접근지정자 추가 및 remained로 변수명을 수정해주세요~
> 
> 해당 부분은 상위 뷰에서 hidden 처리를 해야해서 접근지정자를 추가할 수 없습니다. 변수명은 수정하여 [c413b27](https://github.com/Samsamhada/Giwazip-Client-App/commit/c413b2711806b8d2118ed1d5c68c96054989de83) 로 반영했습니다.

확인했습니다

2023-03-18 15:59 UTC, JUNY0110 approved these changes
꽤 많은 작업과 리뷰임에도 전부 수행해주셨네요. 고생하셨습니다.

2023-03-18 16:02 UTC, merged