[Chore] Coordinator Pattern 적용
Samsamhada/Giwazip-Client-App pull request #71
Opened 2023-03-18 12:45 UTC by JUNY0110

## Motivation 🥳 (코드를 추가/변경하게 된 이유)
- ViewController에서 navigation, modal 등 화면 이동에 대한 역할을 덜어내기 위함.
- EnterViewController를 ClientInfoViewController로 재사용하기 위함.
- PostingTextViewController를 EditingTextViewController로 재사용하기 위함.
- BackBarButton을 간편히 사용하기 위함
- 보여지는 이미지 비율 수정하기 위함

## Key Changes 🔥 (주요 구현/변경 사항)
- 전체 ViewController에 대한 `Coordinator 적용`
- `EnterViewController`, `ClientInfoViewController`에 대해 `isEnterView`를 이용해 분기처리
- `PostingTextViewController`, `EditingTextViewController`에 대해 `isEditView`를 이용해 분기처리
- BackBarButton extension 추가
- HistoryView 이미지 비율 수정 (기존 height: screenWidth / 4 * 3 -> 수정 height: (screenWidth-32) / 4 * 3)

## ToDo 📆 (남은 작업)
- [ ] HistoryViewController -> PostViewController 화면전환 및 코디네이터

## ScreenShot 📷 (참고 사진)

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)
- HistoryViewController의 대규모 수정으로, PostViewController로의 화면전환 코드는 미작성 상태입니다.
- AppCoordinator에 바로 실행가능한 showSegmentViewController, showPostViewController, showSplashViewController를 주석처리해두었으니, 확인하고싶은 파트를 빠르게 선택해 확인가능합니다.
- showPostViewController는 HistoryViewController에서 연결 시 삭제될 코드입니다.
- 추가 및 수정사항이 많습니다. 하지만 비슷한 코드가 많기때문에 보는 것은 어렵지 않을 것 같네요. (어쩌다보니 761줄이네요 :))

## Reference 🔗
- [[iOS] Coordinator Pattern(feat. Swift)이란?](https://jayb-log.tistory.com/321)
- [Zedd -Coordinator Pattern](https://zeddios.medium.com/coordinator-pattern-bf4a1bc46930)
- [Coordinator Tutorial for iOS: Getting Started](https://www.kodeco.com/158-coordinator-tutorial-for-ios-getting-started)
- [삼삼하다 Repo](https://github.com/Samsamhada/MacC-Team-Samsamhada/discussions/203)
- [hlung/AppCoordinatorPattern](https://github.com/hlung/AppCoordinatorPattern/tree/feature/async-coordinator)
- [How to use the coordinator pattern in iOS apps](https://www.hackingwithswift.com/articles/71/how-to-use-the-coordinator-pattern-in-ios-apps)
- [iOS) Coordinator pattern 적용해보자- Advanced](https://gyuios.tistory.com/85)
## Close Issues 🔒 (닫을 Issue)
Close #66.

2023-03-20 01:22 UTC, taek0622 requested changes
고생하셨습니다.
생각보다 많이 복잡하네요.
일단 보이는 부분에 리뷰 남겼고, 가장 큰 문제는 현재 HistoryCoordinator가 넘어오지 않아서 아예 빌드가 되지 않습니다. 확인 하시고 HistoryCoordinator 파일도 넣어주세요.

2023-03-20 01:22 UTC, ikanic commented on GiwazipClient/Views/HistoryViewController.swift
> +        return CGSize(width: screenWidth - 32, height: (screenWidth - 32) / 4 * 3)
p3;
해당 부분은 컬렉션 뷰 전면 수정에 따라 아예 사라질 부분인데, 컨플릭트가 생길 가능성이 있을 것 같네요.

2023-03-20 01:22 UTC, ikanic commented on GiwazipClient/Cells/HistoryCell.swift
> +    let postImage: UIImageView = {
이 부분은 이미 제가 필요해서 수정되었는데, 충돌은 피할 수 없겠군요.. 후 새드...

2023-03-20 01:22 UTC, ikanic commented on GiwazipClient/Supports/BaseCoordinator.swift
> +    var rootViewController = UINavigationController()
p1;
해당 부분은 바로 객체를 생성하지 않고, `var rootViewController: UINavigationController`처럼 선언하셔야 할 것 같습니다.
현재로서는 rootViewController가 사용되지 않을 때에도 무조건 객체를 생성하게 되어 있어서 불필요한 Navigation이 생기게 됩니다.

2023-03-20 01:22 UTC, ikanic commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +            showSegmentViewController()
p1;
해당 부분 조건이 반대로 된 것 같습니다.
isLoggenIn은 로그인 된 상태이므로 해당 부분에 segment가 와야할 것 같네요.
그리고 주석은 후에 사용하려고 삭제하지 않으신 걸까요?

2023-03-20 01:22 UTC, taek0622 commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +    }
이 친구들의 반복되는 부분을 합칠 아이디어가 하나 있긴 합니다만, 아직 코디네이터에 대한 이해가 부족해서 완전한 동작인지 불확실하네요.
후에 완전하게 동작 가능하다면 공유하겠습니다.

2023-03-20 01:22 UTC, taek0622 commented on GiwazipClient/Coordinators/EditingTextCoordinator.swift
> +//
p1;
요 주석은 뭘까요

2023-03-20 01:22 UTC, taek0622 commented on GiwazipClient/Coordinators/EnterCoordinator.swift
> +    let enterViewController = EnterViewController()
Q.
얜 왜 여기에서 초기화되고 있는 걸까요?

2023-03-20 01:22 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.configuration?.attributedTitle?.font = UIFont.systemFont(ofSize: 18, weight: .bold)
p3;
버튼이 변경됨에 따라 세그먼트 뷰와 같은 버튼인 것 같은데, 그렇다면 weight가 bold가 아니라 semibold가 되어야 할 것 같네요.
피그마 상에 수정되지 않은 16 bold와 수정 후인 18 semibold가 섞여있어서 헷갈리신 것 같습니다.

2023-03-20 01:22 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +            inviteCodeGuideLabel.isHidden = false
p5;
이렇게 많은 부분이 hidden되어야 한다면, 하나의 컨테이너 뷰로 묶어서 컨테이너 뷰만 hidden 시키는 것이 코드 가독성 면에서는 더 좋을 것 같네요.

2023-03-20 01:22 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +        guard let phoneNumber = phoneNumberInput.text?.replacingOccurrences(of: " - ", with: "") else { return }
p3;
한 라인이 100자를 넘어가네요. 이 부분은 라인을 나누기 어려운 부분도 아니므로 else 앞에서 한줄 띄어주면 좋을 것 같습니다.

2023-03-20 01:22 UTC, taek0622 commented on GiwazipClient/Coordinators/EditingTextCoordinator.swift
> +        navigationController.present(rootViewController, animated: true)
이 부분은 뭔가 이상하다는 생각이 듭니다만, 현재 확인이 불가능해서 ㅠㅠ

2023-03-20 01:24 UTC, JUNY0110 commented on GiwazipClient/Views/HistoryViewController.swift
> +        return CGSize(width: screenWidth - 32, height: (screenWidth - 32) / 4 * 3)
> p3;
> 해당 부분은 컬렉션 뷰 전면 수정에 따라 아예 사라질 부분인데, 컨플릭트가 생길 가능성이 있을 것 같네요.

해당부분 컨플릭트 해결하면서 삭제되었습니다.

2023-03-20 01:24 UTC, JUNY0110 commented on GiwazipClient/Cells/HistoryCell.swift
> +    let postImage: UIImageView = {
> 이 부분은 이미 제가 필요해서 수정되었는데, 충돌은 피할 수 없겠군요.. 후 새드...

이 부분은 괜찮습니다 :)

2023-03-20 01:36 UTC, JUNY0110 commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +            showSegmentViewController()
> p1;
> 해당 부분 조건이 반대로 된 것 같습니다.
> isLoggenIn은 로그인 된 상태이므로 해당 부분에 segment가 와야할 것 같네요.
> 그리고 주석은 후에 사용하려고 삭제하지 않으신 걸까요?

음, 해당부분은 PR에도 작성되어있다시피 모두 편하게 테스트하도록 일부러 isLoggedIn에 코드를 남겨둔 부분입니다.
일단 HistoryVC가 전반적으로 수정된지 얼마되지 않아 
HistoryViewController와 PostViewController가 연결하지 않았기때문에 더더욱 그렇게 뒀습니다.
다만, else 밑에 있는 showSegment는 착각한 부분이 맞네요 수정했습니다. a246a88

2023-03-20 01:37 UTC, JUNY0110 commented on GiwazipClient/Coordinators/EditingTextCoordinator.swift
> +//
> p1;
> 요 주석은 뭘까요

08ba416 시행착오의 산물이네요. 확인감사합니다.

2023-03-20 01:38 UTC, JUNY0110 commented on GiwazipClient/Coordinators/EnterCoordinator.swift
> +    let enterViewController = EnterViewController()
> Q.
> 얜 왜 여기에서 초기화되고 있는 걸까요?

AppCoordinator에서 조건분기를 위함입니다.
```swift
    func pushToEnterViewController() {
        let coordinator = EnterCoordinator(navigationController: navigationController)
        coordinator.enterViewController.isEnterView = true
        coordinator.delegate = self
        coordinator.start()
        self.childCoordinators.append(coordinator)
    }

    func pushToClientInfoViewController() {
        let coordinator = EnterCoordinator(navigationController: navigationController)
        coordinator.enterViewController.isEnterView = false
        coordinator.delegate = self
        coordinator.start()
        self.childCoordinators.append(coordinator)
    }
```

2023-03-20 01:41 UTC, taek0622 commented on GiwazipClient/Cells/HistoryCell.swift
> +    let postImage: UIImageView = {
> 

이미 수정되었네요.

2023-03-20 01:41 UTC, taek0622 commented on GiwazipClient/Views/HistoryViewController.swift
> +        return CGSize(width: screenWidth - 32, height: (screenWidth - 32) / 4 * 3)
> > p3;
> > 해당 부분은 컬렉션 뷰 전면 수정에 따라 아예 사라질 부분인데, 컨플릭트가 생길 가능성이 있을 것 같네요.
> 
> 해당부분 컨플릭트 해결하면서 삭제되었습니다.

넵 확인했습니다

2023-03-20 01:42 UTC, taek0622 commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +            showSegmentViewController()
> > p1;
> > 해당 부분 조건이 반대로 된 것 같습니다.
> > isLoggenIn은 로그인 된 상태이므로 해당 부분에 segment가 와야할 것 같네요.
> > 그리고 주석은 후에 사용하려고 삭제하지 않으신 걸까요?
> 
> 음, 해당부분은 PR에도 작성되어있다시피 모두 편하게 테스트하도록 일부러 isLoggedIn에 코드를 남겨둔 부분입니다. 일단 HistoryVC가 전반적으로 수정된지 얼마되지 않아 HistoryViewController와 PostViewController가 연결하지 않았기때문에 더더욱 그렇게 뒀습니다. 다만, else 밑에 있는 showSegment는 착각한 부분이 맞네요 수정했습니다. [a246a88](https://github.com/Samsamhada/Giwazip-Client-App/commit/a246a881fe9af9ea02db4e2af2006a4648152b54)

그렇다면 isLoggedIn 분기를 이렇게 하는 거보다는 isLoggedIn 자체의 값을 false로 변경해주는게 더 좋을 것 같네요.

2023-03-20 01:42 UTC, taek0622 commented on GiwazipClient/Coordinators/EditingTextCoordinator.swift
> +//
> > p1;
> > 요 주석은 뭘까요
> 
> [08ba416](https://github.com/Samsamhada/Giwazip-Client-App/commit/08ba4161e8f96c7e66129812f5dbb7f0196005f7) 시행착오의 산물이네요. 확인감사합니다.

확인했습니다. 리뷰 리졸브합니다.

2023-03-20 01:43 UTC, taek0622 commented on GiwazipClient/Coordinators/EnterCoordinator.swift
> +    let enterViewController = EnterViewController()
> > Q.
> > 얜 왜 여기에서 초기화되고 있는 걸까요?
> 
> AppCoordinator에서 조건분기를 위함입니다.
> 
> ```swift
>     func pushToEnterViewController() {
>         let coordinator = EnterCoordinator(navigationController: navigationController)
>         coordinator.enterViewController.isEnterView = true    // <--
>         coordinator.delegate = self
>         coordinator.start()
>         self.childCoordinators.append(coordinator)
>     }
> 
>     func pushToClientInfoViewController() {
>         let coordinator = EnterCoordinator(navigationController: navigationController)
>         coordinator.enterViewController.isEnterView = false    // <--
>         coordinator.delegate = self
>         coordinator.start()
>         self.childCoordinators.append(coordinator)
>     }
> ```

조건 분기를 위함이라면 위에서 EnterViewController를 초기화하는 것보다는 func의 파라미터로 bool 값을 받는 것이 더 옳을 것 같습니다. 우선 저기서 생성한 EnterViewController가 기존의 EnterViewController와 같은 뷰가 아닐 것이기 때문에 더더욱 이 부분은 변경되어야 할 것 같네요.

2023-03-20 01:44 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.configuration?.attributedTitle?.font = UIFont.systemFont(ofSize: 18, weight: .bold)
> p3;
> 버튼이 변경됨에 따라 세그먼트 뷰와 같은 버튼인 것 같은데, 그렇다면 weight가 bold가 아니라 semibold가 되어야 할 것 같네요.
> 피그마 상에 수정되지 않은 16 bold와 수정 후인 18 semibold가 섞여있어서 헷갈리신 것 같습니다.

PostingTextVC의 InquiryButton이 18 bold를 사용하고 있어 착각했네요.
EnterVC와 PostingTextVC 둘 다 18 semibold로 수정했습니다.
204e0b1

2023-03-20 01:55 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.configuration?.attributedTitle?.font = UIFont.systemFont(ofSize: 18, weight: .bold)
> 

확인했습니다. 그런데 알러트 조건 분기 부분이 주석처리된 이유가 있을까요?

2023-03-20 02:05 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +            inviteCodeGuideLabel.isHidden = false
> p5;
> 이렇게 많은 부분이 hidden되어야 한다면, 하나의 컨테이너 뷰로 묶어서 컨테이너 뷰만 hidden 시키는 것이 코드 가독성 면에서는 더 좋을 것 같네요.

f7da0f9
view의 constraint를 모두 잡지 않으면 내부 view에 대한 동작이 안 되는 거였네요.

2023-03-20 02:07 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +            inviteCodeGuideLabel.isHidden = false
> f7da0f9

넵넵 맞습니다. 수정 확인했습니다. 리뷰 리졸브합니다~

2023-03-20 02:07 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +        guard let phoneNumber = phoneNumberInput.text?.replacingOccurrences(of: " - ", with: "") else { return }
> p3;
> 한 라인이 100자를 넘어가네요. 이 부분은 라인을 나누기 어려운 부분도 아니므로 else 앞에서 한줄 띄어주면 좋을 것 같습니다.

88cf9a7 줄바꿈 했습니다.

2023-03-20 02:10 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +        guard let phoneNumber = phoneNumberInput.text?.replacingOccurrences(of: " - ", with: "") else { return }
> > p3;
> > 한 라인이 100자를 넘어가네요. 이 부분은 라인을 나누기 어려운 부분도 아니므로 else 앞에서 한줄 띄어주면 좋을 것 같습니다.
> 
> [88cf9a7](https://github.com/Samsamhada/Giwazip-Client-App/commit/88cf9a7ba0602460803359a7a4299b3ea5b50e2e) 줄바꿈 했습니다.

확인했습니다. 리뷰 리졸브합니다.

2023-03-20 02:11 UTC, JUNY0110 commented on GiwazipClient/Supports/BaseCoordinator.swift
> +    var rootViewController = UINavigationController()
> p1;
> 해당 부분은 바로 객체를 생성하지 않고, `var rootViewController: UINavigationController`처럼 선언하셔야 할 것 같습니다.
> 현재로서는 rootViewController가 사용되지 않을 때에도 무조건 객체를 생성하게 되어 있어서 불필요한 Navigation이 생기게 됩니다.

dfcd485 수정했습니다

2023-03-20 02:15 UTC, taek0622 commented on GiwazipClient/Supports/BaseCoordinator.swift
> +    var rootViewController = UINavigationController()
> > p1;
> > 해당 부분은 바로 객체를 생성하지 않고, `var rootViewController: UINavigationController`처럼 선언하셔야 할 것 같습니다.
> > 현재로서는 rootViewController가 사용되지 않을 때에도 무조건 객체를 생성하게 되어 있어서 불필요한 Navigation이 생기게 됩니다.
> 
> [dfcd485](https://github.com/Samsamhada/Giwazip-Client-App/commit/dfcd485e7d94fa5334a69960c459f1e9cfab18c1) 수정했습니다

확인했습니다. 리뷰 리졸브합니다.

2023-03-20 07:47 UTC, taek0622 commented on GiwazipClient/Coordinators/EnterCoordinator.swift
> +    let enterViewController = EnterViewController()
> > Q.
> > 얜 왜 여기에서 초기화되고 있는 걸까요?
> 
> AppCoordinator에서 조건분기를 위함입니다.
> 
> ```swift
>     func pushToEnterViewController() {
>         let coordinator = EnterCoordinator(navigationController: navigationController)
>         coordinator.enterViewController.isEnterView = true    // <--
>         coordinator.delegate = self
>         coordinator.start()
>         self.childCoordinators.append(coordinator)
>     }
> 
>     func pushToClientInfoViewController() {
>         let coordinator = EnterCoordinator(navigationController: navigationController)
>         coordinator.enterViewController.isEnterView = false    // <--
>         coordinator.delegate = self
>         coordinator.start()
>         self.childCoordinators.append(coordinator)
>     }
> ```

아 제가 착각했네요. 이 부분은 이게 맞는 것 같네요. 혼란 드려서 죄송합니다~

2023-03-22 07:29 UTC, JUNY0110 commented on GiwazipClient/Supports/BaseCoordinator.swift
> +    var rootViewController = UINavigationController()
> 수정 확인했습니다. 다만, rootViewController가 사용되지 않을때는 충돌 위험이 있어서 !가 ?로 변경되어야할 것 같습니다.

rootViewController를 PostingCoordinator로 이동했습니다.
PostingCoordinator 관련 코드가 다소 수정이 되었으니 확인 바랍니다.
d8d303e

2023-03-22 07:43 UTC, JUNY0110 commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +            showSegmentViewController()
> > > p1;
> > > 해당 부분 조건이 반대로 된 것 같습니다.
> > > isLoggenIn은 로그인 된 상태이므로 해당 부분에 segment가 와야할 것 같네요.
> > > 그리고 주석은 후에 사용하려고 삭제하지 않으신 걸까요?
> > 
> > 
> > 음, 해당부분은 PR에도 작성되어있다시피 모두 편하게 테스트하도록 일부러 isLoggedIn에 코드를 남겨둔 부분입니다. 일단 HistoryVC가 전반적으로 수정된지 얼마되지 않아 HistoryViewController와 PostViewController가 연결하지 않았기때문에 더더욱 그렇게 뒀습니다. 다만, else 밑에 있는 showSegment는 착각한 부분이 맞네요 수정했습니다. [a246a88](https://github.com/Samsamhada/Giwazip-Client-App/commit/a246a881fe9af9ea02db4e2af2006a4648152b54)
> 
> 그렇다면 isLoggedIn 분기를 이렇게 하는 거보다는 isLoggedIn 자체의 값을 false로 변경해주는게 더 좋을 것 같네요.

1af26db
isLoggedIn만 사용해서 테스트작업하도록 하는게 편할거라 생각했는데, Merge되는 내용이니 조금 귀찮아지더라도 정상적으로 보내는게 낫겠네요.

2023-03-22 07:45 UTC, JUNY0110 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.configuration?.attributedTitle?.font = UIFont.systemFont(ofSize: 18, weight: .bold)
> 확인했습니다. 그런데 알러트 조건 분기 부분이 주석처리된 이유가 있을까요?

이 또한 작업 편하게 하도록 주석한 것이었지만 되살렸습니다.
7223b59

2023-03-22 09:17 UTC, taek0622 commented on GiwazipClient/Supports/BaseCoordinator.swift
> +    var rootViewController = UINavigationController()
> > 수정 확인했습니다. 다만, rootViewController가 사용되지 않을때는 충돌 위험이 있어서 !가 ?로 변경되어야할 것 같습니다.
> 
> rootViewController를 PostingCoordinator로 이동했습니다. PostingCoordinator 관련 코드가 다소 수정이 되었으니 확인 바랍니다. [d8d303e](https://github.com/Samsamhada/Giwazip-Client-App/commit/d8d303e2ab3f29e1ae0d0b99f6cbde04637b0d1c)

확인했습니다. 그런데 이 부분과는 약간 별개일 수 있지만 현재 작성 마지막까지 가서 문의하기를 누르면 디코딩 에러가 발생한다는 메시지가 나오던데 이 부분에 별 문제는 없는 걸까요?

2023-03-22 09:18 UTC, taek0622 commented on GiwazipClient/Coordinators/AppCoordinator.swift
> +            showSegmentViewController()
> > > > p1;
> > > > 해당 부분 조건이 반대로 된 것 같습니다.
> > > > isLoggenIn은 로그인 된 상태이므로 해당 부분에 segment가 와야할 것 같네요.
> > > > 그리고 주석은 후에 사용하려고 삭제하지 않으신 걸까요?
> > > 
> > > 
> > > 음, 해당부분은 PR에도 작성되어있다시피 모두 편하게 테스트하도록 일부러 isLoggedIn에 코드를 남겨둔 부분입니다. 일단 HistoryVC가 전반적으로 수정된지 얼마되지 않아 HistoryViewController와 PostViewController가 연결하지 않았기때문에 더더욱 그렇게 뒀습니다. 다만, else 밑에 있는 showSegment는 착각한 부분이 맞네요 수정했습니다. [a246a88](https://github.com/Samsamhada/Giwazip-Client-App/commit/a246a881fe9af9ea02db4e2af2006a4648152b54)
> > 
> > 
> > 그렇다면 isLoggedIn 분기를 이렇게 하는 거보다는 isLoggedIn 자체의 값을 false로 변경해주는게 더 좋을 것 같네요.
> 
> [1af26db](https://github.com/Samsamhada/Giwazip-Client-App/commit/1af26db23e7656c692fc84f0d38fbddac1753394) isLoggedIn만 사용해서 테스트작업하도록 하는게 편할거라 생각했는데, Merge되는 내용이니 조금 귀찮아지더라도 정상적으로 보내는게 낫겠네요.

확인했습니다. 리뷰 리졸브합니다.

2023-03-22 09:18 UTC, taek0622 commented on GiwazipClient/Views/EnterViewController.swift
> +        $0.configuration?.attributedTitle?.font = UIFont.systemFont(ofSize: 18, weight: .bold)
> > 확인했습니다. 그런데 알러트 조건 분기 부분이 주석처리된 이유가 있을까요?
> 
> 이 또한 작업 편하게 하도록 주석한 것이었지만 되살렸습니다. [7223b59](https://github.com/Samsamhada/Giwazip-Client-App/commit/7223b59ec667a7893a18b08660fca722cd623d92)

확인했습니다. 리뷰 리졸브합니다.

2023-03-22 09:20 UTC, taek0622 approved these changes
고생하셨습니다.
원래도 큰 PR이었지만, 리베이스에 수정에 하다보니 868줄이나 되어버렸네요.
현재 post를 클릭했을 때 동작이 되지 않지만, 해당 부분은 후에 제가 다시 한 번 살펴보도록 하겠습니다.
추가로 디코딩 에러 발생에 대해서 질문 하나 남겼는데 확인하시고 머지해주시면 감사하겠습니다.

2023-03-24 06:21 UTC, JUNY0110 commented on GiwazipClient/Supports/BaseCoordinator.swift
> +    var rootViewController = UINavigationController()
> 확인했습니다. 그런데 이 부분과는 약간 별개일 수 있지만 현재 작성 마지막까지 가서 문의하기를 누르면 디코딩 에러가 발생한다는 메시지가 나오던데 괜찮은 것 일까요?

코디네이터 적용으로 ViewController간의 연결이 단절되어 생긴 문제입니다.
ViewModel 적용하게 된다면 정상 작동될 것이므로 문제없는 부분이 되겠네요.

테스트를 원하신다면, PostingTextViewController에서 `var imageDatas: [Data] = [UIImage(named: "cat")]`을 해보시면 정삭작동이 되는 것을 확인하실 수 있습니다.

1758614
추가로, 임시 viewModel변수로 사용되던 networkManager를 postingTextViewController에서 networkManager 사용으로 수정하였습니다.

2023-03-24 06:23 UTC, taek0622 commented on GiwazipClient/Supports/BaseCoordinator.swift
> +    var rootViewController = UINavigationController()
> > 확인했습니다. 그런데 이 부분과는 약간 별개일 수 있지만 현재 작성 마지막까지 가서 문의하기를 누르면 디코딩 에러가 발생한다는 메시지가 나오던데 괜찮은 것 일까요?
> 
> 코디네이터 적용으로 ViewController간의 연결이 단절되어 생긴 문제입니다. ViewModel 적용하게 된다면 정상 작동될 것이므로 문제없는 부분이 되겠네요.
> 
> 테스트를 원하신다면, PostingTextViewController에서 `var imageDatas: [Data] = [UIImage(named: "cat")]`을 해보시면 정삭작동이 되는 것을 확인하실 수 있습니다.
> 
> [1758614](https://github.com/Samsamhada/Giwazip-Client-App/commit/1758614a06e0052d05c7d706c16e5a4b9e55081f) 추가로, 임시 viewModel변수로 사용되던 networkManager를 postingTextViewController에서 networkManager 사용으로 수정하였습니다.

확인했습니다. 리뷰 리졸브합니다~

2023-03-24 06:25 UTC, merged